In [2]:
import pandas as pd
import csv
import numpy as np 

df = pd.read_csv(r'C:\Users\sofi\Downloads\wetransfer-3ab4ca\2018.csv',sep=';', encoding = 'ISO-8859-1',
                     names=['ID_ORDER', 'DATE-ADD','TIME-ADD','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE'],
                     dtype={'ID_ORDER':int,'DATE-ADD':object,'TIME-ADD':object,'LOCATION':int,'ID_CUSTOMER':object,'LAST_NAME':object,'FIRST_NAME':object,'YX_LIBELLE':object,'BIRTH_YEAR':object,'TELEX':object,'EMAIL':object,'ADRESS':object,'POSTAL_CODE':object,'CITY':object,'ITEM_CODE':object,'CC_LIBELLE':object,'CC_LIBELLE_1':object})

df

C:\Users\sofi\Anacondaa\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,66032518,2018-01-01 00:00:00.000,2018-01-01 12:06:50.000,66,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0000,NaN
1,80143573,2018-01-01 00:00:00.000,2018-01-01 16:03:37.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PUPH45NRS18H,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN
2,80143576,2018-01-01 00:00:00.000,2018-01-01 17:38:26.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6CR04NRS18H,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN
3,80143572,2018-01-01 00:00:00.000,2018-01-01 14:52:08.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN
4,80143574,2018-01-01 00:00:00.000,2018-01-01 16:56:04.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6SW00F071556F18H,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31 00:00:00.000,2018-12-31 13:40:18.000,24,S2020706,BEN HAMIDA,Sonia,NaN,1974,98691207,...,ZARZOUNA,17CHC00H10830DC19H,ISLAND CLUB,CHEMISE,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN
536844,24168598,2018-12-31 00:00:00.000,2018-12-31 13:39:30.000,24,S2020706,BEN HAMIDA,Sonia,NaN,1974,98691207,...,ZARZOUNA,17PA00H111360C19H,ISLAND CLUB,PANTALON,MARRON,129.0000,1,NaN,NaN,NaN
536845,24168602,2018-12-31 00:00:00.000,2018-12-31 14:40:15.000,24,BC0240557,ZEDDINI,Wael,PARTENAIRE,1900,21882114,...,NaN,4PU18CND18H,BLUE ISLAND,PULL,GRIS PALE,89.9000,1,NaN,NaN,NaN
536846,14142423,2018-12-31 00:00:00.000,2018-12-31 11:04:33.000,14,BC0080855,BRAIKI,Mariem,PARTENAIRE,1900,22494208,...,NaN,27PA00BS1105219H,BLEU & SON,PANTALON,CAMEL,59.9000,-1,-59.8,0.1669,NaN
536847,14142426,2018-12-31 00:00:00.000,2018-12-31 11:16:19.000,14,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PA00H111351F19H,BLUE ISLAND,PANTALON,BEIGE,109.0000,-1,-98.9,9.2661,NaN

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536848 entries, 0 to 536847
Data columns (total 23 columns):
ID_ORDER        536848 non-null int32
DATE-ADD        536848 non-null object
TIME-ADD        536848 non-null object
LOCATION        536848 non-null int32
ID_CUSTOMER     536848 non-null object
LAST_NAME       536848 non-null object
FIRST_NAME      271624 non-null object
YX_LIBELLE      426416 non-null object
BIRTH_YEAR      536833 non-null object
TELEX           267784 non-null object
EMAIL           134450 non-null object
ADRESS          177862 non-null object
POSTAL_CODE     439634 non-null object
CITY            439129 non-null object
ITEM_CODE       536847 non-null object
CC_LIBELLE      536387 non-null object
CC_LIBELLE_1    536387 non-null object
DESIGNATION     536387 non-null object
PVTTC           536848 non-null object
QTEFACT         536848 non-null object
PUTTCNET        445275 non-null object
MLR_REMISE      445214 non-null float64
GTR_LIBELLE     439960 non-null object
dtypes: float64(1), int32(2), object(20)
memory usage: 90.1+ MB

In [3]:
#convert DataFrame column to date-time:'GP_DATEPIECE'
df['DATE-ADD'] = pd.to_datetime(df['DATE-ADD'], format = '%Y-%m-%d')
df['DATE-ADD']= pd.to_datetime(df['DATE-ADD'], errors='ignore')
df.head()

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,66032518,2018-01-01,2018-01-01 12:06:50.000,66,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0,NaN
1,80143573,2018-01-01,2018-01-01 16:03:37.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PUPH45NRS18H,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN
2,80143576,2018-01-01,2018-01-01 17:38:26.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6CR04NRS18H,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN
3,80143572,2018-01-01,2018-01-01 14:52:08.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN
4,80143574,2018-01-01,2018-01-01 16:56:04.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6SW00F071556F18H,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN

In [4]:

df['TIME-ADD'] = pd.to_datetime(df['TIME-ADD'])

df

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,66032518,2018-01-01,2018-01-01 12:06:50,66,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0000,NaN
1,80143573,2018-01-01,2018-01-01 16:03:37,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PUPH45NRS18H,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN
2,80143576,2018-01-01,2018-01-01 17:38:26,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6CR04NRS18H,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN
3,80143572,2018-01-01,2018-01-01 14:52:08,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN
4,80143574,2018-01-01,2018-01-01 16:56:04,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6SW00F071556F18H,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31,2018-12-31 13:40:18,24,S2020706,BEN HAMIDA,Sonia,NaN,1974,98691207,...,ZARZOUNA,17CHC00H10830DC19H,ISLAND CLUB,CHEMISE,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN
536844,24168598,2018-12-31,2018-12-31 13:39:30,24,S2020706,BEN HAMIDA,Sonia,NaN,1974,98691207,...,ZARZOUNA,17PA00H111360C19H,ISLAND CLUB,PANTALON,MARRON,129.0000,1,NaN,NaN,NaN
536845,24168602,2018-12-31,2018-12-31 14:40:15,24,BC0240557,ZEDDINI,Wael,PARTENAIRE,1900,21882114,...,NaN,4PU18CND18H,BLUE ISLAND,PULL,GRIS PALE,89.9000,1,NaN,NaN,NaN
536846,14142423,2018-12-31,2018-12-31 11:04:33,14,BC0080855,BRAIKI,Mariem,PARTENAIRE,1900,22494208,...,NaN,27PA00BS1105219H,BLEU & SON,PANTALON,CAMEL,59.9000,-1,-59.8,0.1669,NaN
536847,14142426,2018-12-31,2018-12-31 11:16:19,14,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PA00H111351F19H,BLUE ISLAND,PANTALON,BEIGE,109.0000,-1,-98.9,9.2661,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536848 entries, 0 to 536847
Data columns (total 23 columns):
ID_ORDER        536848 non-null int32
DATE-ADD        536848 non-null datetime64[ns]
TIME-ADD        536848 non-null datetime64[ns]
LOCATION        536848 non-null int32
ID_CUSTOMER     536848 non-null object
LAST_NAME       536848 non-null object
FIRST_NAME      271624 non-null object
YX_LIBELLE      426416 non-null object
BIRTH_YEAR      536833 non-null object
TELEX           267784 non-null object
EMAIL           134450 non-null object
ADRESS          177862 non-null object
POSTAL_CODE     439634 non-null object
CITY            439129 non-null object
ITEM_CODE       536847 non-null object
CC_LIBELLE      536387 non-null object
CC_LIBELLE_1    536387 non-null object
DESIGNATION     536387 non-null object
PVTTC           536848 non-null object
QTEFACT         536848 non-null object
PUTTCNET        445275 non-null object
MLR_REMISE      445214 non-null float64
GTR_LIBELLE     439960 non-null object
dtypes: datetime64[ns](2), float64(1), int32(2), object(18)
memory usage: 90.1+ MB

In [6]:
# Create the dictionary for  ETABLISSEMENT
etab = {28:'Sasio Geant',31:'Blue Island Carrefour',62:'Central Park',16:'Sousse',8:'Lafayette',130:'Blue Island Palmarium',50:'Sasio Carrefour',24:'Bizerte',40:'Ennasr',56:'Sasio Manzah VI',14:'Blue Island Zephyr',61:'La Soukra',63:'Sasio Menzah V',54:'Nabeul',37:'Sasio Zephyr',134:'Sasio Palmarium',64:'Nabeul',65:'Blue Island Manar',36:'Sasio Manar',25:'Blue Island Djerba',52:'Blue Island Menzah VI',66:'Mehdia',42:'Lac 2',67:'Sfax',68:'Monastir',51:'Blue Island Menzah V',69:'El Kef',35:'Kairouan',15:'Sasio Mseken',27:'Sasio Mseken',60:'Sasio Djerba',18:'Kelibia',41:'Ksar Hellal',74:'Hammamet'}
df['LOCATION'] = df['LOCATION'].map(etab)
#display the first 5 lines
df

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,66032518,2018-01-01,2018-01-01 12:06:50,Mehdia,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0000,NaN
1,80143573,2018-01-01,2018-01-01 16:03:37,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PUPH45NRS18H,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN
2,80143576,2018-01-01,2018-01-01 17:38:26,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6CR04NRS18H,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN
3,80143572,2018-01-01,2018-01-01 14:52:08,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN
4,80143574,2018-01-01,2018-01-01 16:56:04,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6SW00F071556F18H,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31,2018-12-31 13:40:18,Bizerte,S2020706,BEN HAMIDA,Sonia,NaN,1974,98691207,...,ZARZOUNA,17CHC00H10830DC19H,ISLAND CLUB,CHEMISE,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN
536844,24168598,2018-12-31,2018-12-31 13:39:30,Bizerte,S2020706,BEN HAMIDA,Sonia,NaN,1974,98691207,...,ZARZOUNA,17PA00H111360C19H,ISLAND CLUB,PANTALON,MARRON,129.0000,1,NaN,NaN,NaN
536845,24168602,2018-12-31,2018-12-31 14:40:15,Bizerte,BC0240557,ZEDDINI,Wael,PARTENAIRE,1900,21882114,...,NaN,4PU18CND18H,BLUE ISLAND,PULL,GRIS PALE,89.9000,1,NaN,NaN,NaN
536846,14142423,2018-12-31,2018-12-31 11:04:33,Blue Island Zephyr,BC0080855,BRAIKI,Mariem,PARTENAIRE,1900,22494208,...,NaN,27PA00BS1105219H,BLEU & SON,PANTALON,CAMEL,59.9000,-1,-59.8,0.1669,NaN
536847,14142426,2018-12-31,2018-12-31 11:16:19,Blue Island Zephyr,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PA00H111351F19H,BLUE ISLAND,PANTALON,BEIGE,109.0000,-1,-98.9,9.2661,NaN

In [7]:
df['LOCATION'].value_counts()

Central Park             41495
Sousse                   37702
Nabeul                   37591
Sasio Geant              35923
Bizerte                  31605
Blue Island Carrefour    29947
Lafayette                25563
Sfax                     20199
Monastir                 19996
Blue Island Palmarium    17997
Kairouan                 17697
Sasio Manzah VI          17348
Sasio Carrefour          16039
Blue Island Zephyr       14134
Ennasr                   13632
El Kef                   13615
Sasio Mseken             13446
Sasio Palmarium          13233
Kelibia                  11111
Mehdia                   11095
Sasio Menzah V           11068
Ksar Hellal              10794
La Soukra                10347
Sasio Manar              10101
Hammamet                  9305
Blue Island Manar         8619
Sasio Zephyr              7305
Blue Island Menzah V      6688
Lac 2                     6264
Sasio Djerba              6048
Blue Island Djerba        5751
Blue Island Menzah VI     5190
Name: LOCATION, dtype: int64

In [8]:
df['DATE-ADD'] = pd.to_datetime(df['DATE-ADD'])

df['SEASON'] = (df['DATE-ADD'].dt.month - 1) // 3
df['SEASON'] += (df['DATE-ADD'].dt.month == 3)&(df['DATE-ADD'].dt.day>=20)
df['SEASON'] += (df['DATE-ADD'].dt.month == 6)&(df['DATE-ADD'].dt.day>=21)
df['SEASON'] += (df['DATE-ADD'].dt.month == 9)&(df['DATE-ADD'].dt.day>=23)
df['SEASON'] -= 3*((df['DATE-ADD'].dt.month == 12)&(df['DATE-ADD'].dt.day>=21)).astype(int)

In [9]:
df.iloc[130766,:]

ID_ORDER                        37017306
DATE-ADD             2018-03-21 00:00:00
TIME-ADD             2018-03-21 17:08:07
LOCATION                    Sasio Zephyr
ID_CUSTOMER                    SB0370063
LAST_NAME                       ISMAHENE
FIRST_NAME                       Khraifi
YX_LIBELLE                    PARTENAIRE
BIRTH_YEAR                          1982
TELEX                           25939290
EMAIL                                NaN
ADRESS          33rue Abdelaziz La Marsa
POSTAL_CODE                          NaN
CITY                                 NaN
ITEM_CODE                   6GL1009SL18H
CC_LIBELLE                   SASIO FEMME
CC_LIBELLE_1                     TUNIQUE
DESIGNATION                     MOUTARDE
PVTTC                            74.9000
QTEFACT                                1
PUTTCNET                           22.47
MLR_REMISE                            70
GTR_LIBELLE                       Soldes
SEASON                                 1
Name: 130766, dtype: object

In [10]:
season={0:'Winter',1:'Spring',2:'Summer',3:'Autumn'}

df['SEASON'] = df['SEASON'].map(season)
df

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE,SEASON
0,66032518,2018-01-01,2018-01-01 12:06:50,Mehdia,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0000,NaN,Winter
1,80143573,2018-01-01,2018-01-01 16:03:37,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,4PUPH45NRS18H,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN,Winter
2,80143576,2018-01-01,2018-01-01 17:38:26,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,6CR04NRS18H,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN,Winter
3,80143572,2018-01-01,2018-01-01 14:52:08,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN,Winter
4,80143574,2018-01-01,2018-01-01 16:56:04,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,6SW00F071556F18H,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31,2018-12-31 13:40:18,Bizerte,S2020706,BEN HAMIDA,Sonia,NaN,1974,98691207,...,17CHC00H10830DC19H,ISLAND CLUB,CHEMISE,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN,Winter
536844,24168598,2018-12-31,2018-12-31 13:39:30,Bizerte,S2020706,BEN HAMIDA,Sonia,NaN,1974,98691207,...,17PA00H111360C19H,ISLAND CLUB,PANTALON,MARRON,129.0000,1,NaN,NaN,NaN,Winter
536845,24168602,2018-12-31,2018-12-31 14:40:15,Bizerte,BC0240557,ZEDDINI,Wael,PARTENAIRE,1900,21882114,...,4PU18CND18H,BLUE ISLAND,PULL,GRIS PALE,89.9000,1,NaN,NaN,NaN,Winter
536846,14142423,2018-12-31,2018-12-31 11:04:33,Blue Island Zephyr,BC0080855,BRAIKI,Mariem,PARTENAIRE,1900,22494208,...,27PA00BS1105219H,BLEU & SON,PANTALON,CAMEL,59.9000,-1,-59.8,0.1669,NaN,Winter
536847,14142426,2018-12-31,2018-12-31 11:16:19,Blue Island Zephyr,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,4PA00H111351F19H,BLUE ISLAND,PANTALON,BEIGE,109.0000,-1,-98.9,9.2661,NaN,Winter

In [11]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]
df

,ID_ORDER,DATE-ADD,TIME-ADD,SEASON,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,66032518,2018-01-01,2018-01-01 12:06:50,Winter,Mehdia,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,...,TUNIS,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0000,NaN
1,80143573,2018-01-01,2018-01-01 16:03:37,Winter,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,...,TUNIS,4PUPH45NRS18H,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN
2,80143576,2018-01-01,2018-01-01 17:38:26,Winter,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,...,TUNIS,6CR04NRS18H,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN
3,80143572,2018-01-01,2018-01-01 14:52:08,Winter,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,...,TUNIS,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN
4,80143574,2018-01-01,2018-01-01 16:56:04,Winter,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,...,TUNIS,6SW00F071556F18H,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31,2018-12-31 13:40:18,Winter,Bizerte,S2020706,BEN HAMIDA,Sonia,NaN,1974,...,ZARZOUNA,17CHC00H10830DC19H,ISLAND CLUB,CHEMISE,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN
536844,24168598,2018-12-31,2018-12-31 13:39:30,Winter,Bizerte,S2020706,BEN HAMIDA,Sonia,NaN,1974,...,ZARZOUNA,17PA00H111360C19H,ISLAND CLUB,PANTALON,MARRON,129.0000,1,NaN,NaN,NaN
536845,24168602,2018-12-31,2018-12-31 14:40:15,Winter,Bizerte,BC0240557,ZEDDINI,Wael,PARTENAIRE,1900,...,NaN,4PU18CND18H,BLUE ISLAND,PULL,GRIS PALE,89.9000,1,NaN,NaN,NaN
536846,14142423,2018-12-31,2018-12-31 11:04:33,Winter,Blue Island Zephyr,BC0080855,BRAIKI,Mariem,PARTENAIRE,1900,...,NaN,27PA00BS1105219H,BLEU & SON,PANTALON,CAMEL,59.9000,-1,-59.8,0.1669,NaN
536847,14142426,2018-12-31,2018-12-31 11:16:19,Winter,Blue Island Zephyr,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,...,TUNIS,4PA00H111351F19H,BLUE ISLAND,PANTALON,BEIGE,109.0000,-1,-98.9,9.2661,NaN

In [12]:
df.iloc[130850,:]

ID_ORDER                   61063036
DATE-ADD        2018-03-21 00:00:00
TIME-ADD        2018-03-21 17:32:41
SEASON                       Spring
LOCATION                  La Soukra
ID_CUSTOMER                SC000004
LAST_NAME         CLIENT de PASSAGE
FIRST_NAME                      NaN
YX_LIBELLE                 PASSAGER
BIRTH_YEAR                        0
TELEX                           NaN
EMAIL                           NaN
ADRESS                          NaN
POSTAL_CODE                    1008
CITY                          TUNIS
ITEM_CODE              6PON07NRS18H
CC_LIBELLE              SASIO FEMME
CC_LIBELLE_1                 PONCHO
DESIGNATION                  MARINE
PVTTC                       79.9000
QTEFACT                           1
PUTTCNET                      31.96
MLR_REMISE                       60
GTR_LIBELLE                  Soldes
Name: 130850, dtype: object

In [13]:
df['COVID']='Pre-Covid'
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','COVID','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]
df

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,ID_ORDER,DATE-ADD,TIME-ADD,SEASON,COVID,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,66032518,2018-01-01,2018-01-01 12:06:50,Winter,Pre-Covid,Mehdia,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,...,TUNIS,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0000,NaN
1,80143573,2018-01-01,2018-01-01 16:03:37,Winter,Pre-Covid,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,...,TUNIS,4PUPH45NRS18H,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN
2,80143576,2018-01-01,2018-01-01 17:38:26,Winter,Pre-Covid,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,...,TUNIS,6CR04NRS18H,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN
3,80143572,2018-01-01,2018-01-01 14:52:08,Winter,Pre-Covid,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,...,TUNIS,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN
4,80143574,2018-01-01,2018-01-01 16:56:04,Winter,Pre-Covid,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,...,TUNIS,6SW00F071556F18H,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31,2018-12-31 13:40:18,Winter,Pre-Covid,Bizerte,S2020706,BEN HAMIDA,Sonia,NaN,...,ZARZOUNA,17CHC00H10830DC19H,ISLAND CLUB,CHEMISE,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN
536844,24168598,2018-12-31,2018-12-31 13:39:30,Winter,Pre-Covid,Bizerte,S2020706,BEN HAMIDA,Sonia,NaN,...,ZARZOUNA,17PA00H111360C19H,ISLAND CLUB,PANTALON,MARRON,129.0000,1,NaN,NaN,NaN
536845,24168602,2018-12-31,2018-12-31 14:40:15,Winter,Pre-Covid,Bizerte,BC0240557,ZEDDINI,Wael,PARTENAIRE,...,NaN,4PU18CND18H,BLUE ISLAND,PULL,GRIS PALE,89.9000,1,NaN,NaN,NaN
536846,14142423,2018-12-31,2018-12-31 11:04:33,Winter,Pre-Covid,Blue Island Zephyr,BC0080855,BRAIKI,Mariem,PARTENAIRE,...,NaN,27PA00BS1105219H,BLEU & SON,PANTALON,CAMEL,59.9000,-1,-59.8,0.1669,NaN
536847,14142426,2018-12-31,2018-12-31 11:16:19,Winter,Pre-Covid,Blue Island Zephyr,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,...,TUNIS,4PA00H111351F19H,BLUE ISLAND,PANTALON,BEIGE,109.0000,-1,-98.9,9.2661,NaN

In [75]:
df['BIRTH_YEAR'] = pd.to_datetime(df['BIRTH_YEAR'],errors='coerce')

In [76]:
df.isnull().sum()

ID_ORDER               0
DATE-ADD               0
TIME-ADD               0
HOUR                   0
SEASON                 0
P_MONTH                0
P_WEEK                 0
COVID                  0
CONFINEMENT            0
CURFEW                 0
LOCATION               0
ID_CUSTOMER            0
LAST_NAME              0
FIRST_NAME        265224
YX_LIBELLE        110432
BIRTH_YEAR             0
AGE                    8
TELEX             269064
EMAIL             402398
ADRESS            358986
POSTAL_CODE            0
CITY               97719
ITEM_CODE              1
CC_LIBELLE           461
CC_LIBELLE_1         461
DESIGNATION          461
PVTTC                  0
QTEFACT                0
PUTTCNET           91573
MLR_REMISE         91634
GTR_LIBELLE        96888
TOTAL_QUANTITY         0
REGION            102338
AREA              102338
CLASS             102338
dtype: int64

In [73]:
df['BIRTH_YEAR'].fillna((df['BIRTH_YEAR'].mean()), inplace=True)

In [1]:
df.isnull().sum()

NameError: name 'df' is not defined

In [17]:
df[df['BIRTH_YEAR']=='2099']
df[df['BIRTH_YEAR']=='1765']
df[df['BIRTH_YEAR']=='1775']

,ID_ORDER,DATE-ADD,TIME-ADD,SEASON,COVID,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
225346,62213164,2018-06-10,2018-06-10 15:13:27,Spring,Pre-Covid,Central Park,SB0621595,MAHDI,El Behi,PARTENAIRE,...,NaN,4TS00H171286F18E,BLUE ISLAND,TEE-SHIRT,BLANC/BLEU,34.9000,1.0000,31.41,10.0,Offre Speciale FidÃ©litÃ©

In [18]:
df.loc[262694,'BIRTH_YEAR'] =None
df.loc[136790,'BIRTH_YEAR'] =None
df.loc[138972,'BIRTH_YEAR'] =None
df.loc[146290,'BIRTH_YEAR'] =None
df.loc[146311,'BIRTH_YEAR'] =None
df.loc[147012,'BIRTH_YEAR'] =None
df.loc[147087,'BIRTH_YEAR'] =None
df.loc[225346,'BIRTH_YEAR'] =None

In [19]:
from datetime import datetime, timedelta
df.loc[((df.BIRTH_YEAR).dt.year < 1018),'BIRTH_YEAR']=None

In [20]:
df['AGE'] = df['DATE-ADD'].dt.year- df['BIRTH_YEAR'].dt.year
df

,ID_ORDER,DATE-ADD,TIME-ADD,SEASON,COVID,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,...,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE,AGE
0,66032518,2018-01-01,2018-01-01 12:06:50,Winter,Pre-Covid,Mehdia,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,...,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0000,NaN,65.0
1,80143573,2018-01-01,2018-01-01 16:03:37,Winter,Pre-Covid,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,...,4PUPH45NRS18H,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN,65.0
2,80143576,2018-01-01,2018-01-01 17:38:26,Winter,Pre-Covid,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,...,6CR04NRS18H,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN,65.0
3,80143572,2018-01-01,2018-01-01 14:52:08,Winter,Pre-Covid,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,...,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN,65.0
4,80143574,2018-01-01,2018-01-01 16:56:04,Winter,Pre-Covid,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,...,6SW00F071556F18H,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31,2018-12-31 13:40:18,Winter,Pre-Covid,Bizerte,S2020706,BEN HAMIDA,Sonia,NaN,...,17CHC00H10830DC19H,ISLAND CLUB,CHEMISE,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN,44.0
536844,24168598,2018-12-31,2018-12-31 13:39:30,Winter,Pre-Covid,Bizerte,S2020706,BEN HAMIDA,Sonia,NaN,...,17PA00H111360C19H,ISLAND CLUB,PANTALON,MARRON,129.0000,1,NaN,NaN,NaN,44.0
536845,24168602,2018-12-31,2018-12-31 14:40:15,Winter,Pre-Covid,Bizerte,BC0240557,ZEDDINI,Wael,PARTENAIRE,...,4PU18CND18H,BLUE ISLAND,PULL,GRIS PALE,89.9000,1,NaN,NaN,NaN,118.0
536846,14142423,2018-12-31,2018-12-31 11:04:33,Winter,Pre-Covid,Blue Island Zephyr,BC0080855,BRAIKI,Mariem,PARTENAIRE,...,27PA00BS1105219H,BLEU & SON,PANTALON,CAMEL,59.9000,-1,-59.8,0.1669,NaN,118.0
536847,14142426,2018-12-31,2018-12-31 11:16:19,Winter,Pre-Covid,Blue Island Zephyr,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,...,4PA00H111351F19H,BLUE ISLAND,PANTALON,BEIGE,109.0000,-1,-98.9,9.2661,NaN,65.0

In [21]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','COVID','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]

In [22]:
df['AGE']=df['AGE']
df['AGE'].value_counts()

65.0     319955
118.0     66840
38.0      10153
39.0       6569
40.0       6430
          ...
127.0         2
122.0         1
80.0          1
148.0         1
116.0         1
Name: AGE, Length: 113, dtype: int64

In [23]:
df['AGE'].value_counts()

65.0     319955
118.0     66840
38.0      10153
39.0       6569
40.0       6430
          ...
127.0         2
122.0         1
80.0          1
148.0         1
116.0         1
Name: AGE, Length: 113, dtype: int64

In [24]:
df['AGE'].max()

159.0

In [25]:
df['AGE'].min()

0.0

In [26]:

q1=df["AGE"].quantile(q=0.25)
q3=df["AGE"].quantile(q=0.75)
IQR=q3-q1
borne_inf = q1-1.5*IQR
borne_sup = q3 +1.5*IQR
df.loc[df.AGE>borne_sup,'AGE']=df["AGE"].mean()
df.loc[df.AGE<borne_inf,'AGE']=df["AGE"].mean()
#df= df[df["age"]<borne_sup]
#df=df[df["age"]>borne_inf]

In [27]:
df['AGE'].max()

84.0

In [28]:
df['AGE'].min()

33.0

In [29]:
df['CONFINEMENT']='NO'
df['CURFEW']='NO'
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','COVID','CONFINEMENT','CURFEW','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]
df

,ID_ORDER,DATE-ADD,TIME-ADD,SEASON,COVID,CONFINEMENT,CURFEW,LOCATION,ID_CUSTOMER,LAST_NAME,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,66032518,2018-01-01,2018-01-01 12:06:50,Winter,Pre-Covid,NO,NO,Mehdia,SC000004,CLIENT de PASSAGE,...,TUNIS,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0000,NaN
1,80143573,2018-01-01,2018-01-01 16:03:37,Winter,Pre-Covid,NO,NO,Lafayette,SC000004,CLIENT de PASSAGE,...,TUNIS,4PUPH45NRS18H,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN
2,80143576,2018-01-01,2018-01-01 17:38:26,Winter,Pre-Covid,NO,NO,Lafayette,SC000004,CLIENT de PASSAGE,...,TUNIS,6CR04NRS18H,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN
3,80143572,2018-01-01,2018-01-01 14:52:08,Winter,Pre-Covid,NO,NO,Lafayette,SC000004,CLIENT de PASSAGE,...,TUNIS,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN
4,80143574,2018-01-01,2018-01-01 16:56:04,Winter,Pre-Covid,NO,NO,Lafayette,SC000004,CLIENT de PASSAGE,...,TUNIS,6SW00F071556F18H,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31,2018-12-31 13:40:18,Winter,Pre-Covid,NO,NO,Bizerte,S2020706,BEN HAMIDA,...,ZARZOUNA,17CHC00H10830DC19H,ISLAND CLUB,CHEMISE,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN
536844,24168598,2018-12-31,2018-12-31 13:39:30,Winter,Pre-Covid,NO,NO,Bizerte,S2020706,BEN HAMIDA,...,ZARZOUNA,17PA00H111360C19H,ISLAND CLUB,PANTALON,MARRON,129.0000,1,NaN,NaN,NaN
536845,24168602,2018-12-31,2018-12-31 14:40:15,Winter,Pre-Covid,NO,NO,Bizerte,BC0240557,ZEDDINI,...,NaN,4PU18CND18H,BLUE ISLAND,PULL,GRIS PALE,89.9000,1,NaN,NaN,NaN
536846,14142423,2018-12-31,2018-12-31 11:04:33,Winter,Pre-Covid,NO,NO,Blue Island Zephyr,BC0080855,BRAIKI,...,NaN,27PA00BS1105219H,BLEU & SON,PANTALON,CAMEL,59.9000,-1,-59.8,0.1669,NaN
536847,14142426,2018-12-31,2018-12-31 11:16:19,Winter,Pre-Covid,NO,NO,Blue Island Zephyr,SC000004,CLIENT de PASSAGE,...,TUNIS,4PA00H111351F19H,BLUE ISLAND,PANTALON,BEIGE,109.0000,-1,-98.9,9.2661,NaN

In [30]:
df['P_MONTH']=0
df['P_MONTH']+=(df['DATE-ADD'].dt.day>10)
df['P_MONTH']+=(df['DATE-ADD'].dt.day>20)
df['P_MONTH']=df['P_MONTH'].astype(int)

In [31]:
month={0:'Start_of_Month',1:'Middle_of_Month',2:'End_of_Month'}
df['P_MONTH'] = df['P_MONTH'].map(month)

In [32]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','P_MONTH','COVID','CONFINEMENT','CURFEW','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]
df

,ID_ORDER,DATE-ADD,TIME-ADD,SEASON,P_MONTH,COVID,CONFINEMENT,CURFEW,LOCATION,ID_CUSTOMER,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,66032518,2018-01-01,2018-01-01 12:06:50,Winter,Start_of_Month,Pre-Covid,NO,NO,Mehdia,SC000004,...,TUNIS,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0000,NaN
1,80143573,2018-01-01,2018-01-01 16:03:37,Winter,Start_of_Month,Pre-Covid,NO,NO,Lafayette,SC000004,...,TUNIS,4PUPH45NRS18H,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN
2,80143576,2018-01-01,2018-01-01 17:38:26,Winter,Start_of_Month,Pre-Covid,NO,NO,Lafayette,SC000004,...,TUNIS,6CR04NRS18H,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN
3,80143572,2018-01-01,2018-01-01 14:52:08,Winter,Start_of_Month,Pre-Covid,NO,NO,Lafayette,SC000004,...,TUNIS,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN
4,80143574,2018-01-01,2018-01-01 16:56:04,Winter,Start_of_Month,Pre-Covid,NO,NO,Lafayette,SC000004,...,TUNIS,6SW00F071556F18H,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31,2018-12-31 13:40:18,Winter,End_of_Month,Pre-Covid,NO,NO,Bizerte,S2020706,...,ZARZOUNA,17CHC00H10830DC19H,ISLAND CLUB,CHEMISE,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN
536844,24168598,2018-12-31,2018-12-31 13:39:30,Winter,End_of_Month,Pre-Covid,NO,NO,Bizerte,S2020706,...,ZARZOUNA,17PA00H111360C19H,ISLAND CLUB,PANTALON,MARRON,129.0000,1,NaN,NaN,NaN
536845,24168602,2018-12-31,2018-12-31 14:40:15,Winter,End_of_Month,Pre-Covid,NO,NO,Bizerte,BC0240557,...,NaN,4PU18CND18H,BLUE ISLAND,PULL,GRIS PALE,89.9000,1,NaN,NaN,NaN
536846,14142423,2018-12-31,2018-12-31 11:04:33,Winter,End_of_Month,Pre-Covid,NO,NO,Blue Island Zephyr,BC0080855,...,NaN,27PA00BS1105219H,BLEU & SON,PANTALON,CAMEL,59.9000,-1,-59.8,0.1669,NaN
536847,14142426,2018-12-31,2018-12-31 11:16:19,Winter,End_of_Month,Pre-Covid,NO,NO,Blue Island Zephyr,SC000004,...,TUNIS,4PA00H111351F19H,BLUE ISLAND,PANTALON,BEIGE,109.0000,-1,-98.9,9.2661,NaN

In [33]:
from datetime import date
import calendar


df['P_WEEK']=df['DATE-ADD'].dt.strftime('%A')
week={'Monday':'Start_of_Week','Tuesday':'Start_of_Week','Wednesday':'Mid_Week','Thursday':'Mid_Week','Friday':'Mid_Week','Saturday':'Week_End','Sunday':'Week_end'}
df['P_WEEK'] = df['P_WEEK'].map(week)

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [34]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','P_MONTH','P_WEEK','COVID','CONFINEMENT','CURFEW','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]
df.iloc[130850,:]

ID_ORDER                             61063036
DATE-ADD                  2018-03-21 00:00:00
TIME-ADD                  2018-03-21 17:32:41
SEASON                                 Spring
P_MONTH                          End_of_Month
P_WEEK                               Mid_Week
COVID                               Pre-Covid
CONFINEMENT                                NO
CURFEW                                     NO
LOCATION                            La Soukra
ID_CUSTOMER                          SC000004
LAST_NAME                   CLIENT de PASSAGE
FIRST_NAME                                NaN
YX_LIBELLE                           PASSAGER
BIRTH_YEAR      1953-10-31 12:04:51.382066496
AGE                                        65
TELEX                                     NaN
EMAIL                                     NaN
ADRESS                                    NaN
POSTAL_CODE                              1008
CITY                                    TUNIS
ITEM_CODE                        6PON07NRS18H
CC_LIBELLE                        SASIO FEMME
CC_LIBELLE_1                           PONCHO
DESIGNATION                            MARINE
PVTTC                                 79.9000
QTEFACT                                     1
PUTTCNET                                31.96
MLR_REMISE                                 60
GTR_LIBELLE                            Soldes
Name: 130850, dtype: object

In [35]:

df['TOTAL_QUANTITY'] = df.groupby(['ID_ORDER'])['DATE-ADD'].transform('count')
df

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,ID_ORDER,DATE-ADD,TIME-ADD,SEASON,P_MONTH,P_WEEK,COVID,CONFINEMENT,CURFEW,LOCATION,...,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE,TOTAL_QUANTITY
0,66032518,2018-01-01,2018-01-01 12:06:50,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Mehdia,...,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0000,NaN,4
1,80143573,2018-01-01,2018-01-01 16:03:37,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Lafayette,...,4PUPH45NRS18H,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN,1
2,80143576,2018-01-01,2018-01-01 17:38:26,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Lafayette,...,6CR04NRS18H,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN,2
3,80143572,2018-01-01,2018-01-01 14:52:08,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Lafayette,...,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN,1
4,80143574,2018-01-01,2018-01-01 16:56:04,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Lafayette,...,6SW00F071556F18H,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31,2018-12-31 13:40:18,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Bizerte,...,17CHC00H10830DC19H,ISLAND CLUB,CHEMISE,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN,2
536844,24168598,2018-12-31,2018-12-31 13:39:30,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Bizerte,...,17PA00H111360C19H,ISLAND CLUB,PANTALON,MARRON,129.0000,1,NaN,NaN,NaN,2
536845,24168602,2018-12-31,2018-12-31 14:40:15,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Bizerte,...,4PU18CND18H,BLUE ISLAND,PULL,GRIS PALE,89.9000,1,NaN,NaN,NaN,2
536846,14142423,2018-12-31,2018-12-31 11:04:33,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Blue Island Zephyr,...,27PA00BS1105219H,BLEU & SON,PANTALON,CAMEL,59.9000,-1,-59.8,0.1669,NaN,5
536847,14142426,2018-12-31,2018-12-31 11:16:19,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Blue Island Zephyr,...,4PA00H111351F19H,BLUE ISLAND,PANTALON,BEIGE,109.0000,-1,-98.9,9.2661,NaN,2

In [36]:
df[df['ID_ORDER'] ==66032518]

,ID_ORDER,DATE-ADD,TIME-ADD,SEASON,P_MONTH,P_WEEK,COVID,CONFINEMENT,CURFEW,LOCATION,...,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE,TOTAL_QUANTITY
0,66032518,2018-01-01,2018-01-01 12:06:50,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Mehdia,...,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0,NaN,4
186,66032518,2018-01-01,2018-01-01 12:06:50,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Mehdia,...,15PA00ROS9118H,IPSOS,PANTALON,NOIR,98.9,-1,NaN,NaN,NaN,4
187,66032518,2018-01-01,2018-01-01 12:06:50,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Mehdia,...,15VE00ROS9018H,IPSOS,VESTE,VIOLET,169.9,1,NaN,NaN,NaN,4
356,66032518,2018-01-01,2018-01-01 12:06:50,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Mehdia,...,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,24.95,50.0,2 eme 50 et le 3 eme 100,4

In [37]:
df2= pd.read_csv(r'C:\Users\sofi\Downloads\train_code_postal.csv')
df2 = df2.rename(columns={'code postal': 'POST_CODE'})
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 969 entries, 0 to 968
Data columns (total 5 columns):
POST_CODE       969 non-null object
Delegation      969 non-null object
poverty rate    969 non-null float64
zone            969 non-null object
orientation     969 non-null object
dtypes: float64(1), object(4)
memory usage: 38.0+ KB

In [38]:
df['QTEFACT'].value_counts()

1.0           363489
1.0000        158783
-1.0            9031
-1.0000         4888
89.9              60
               ...
PRUNE/NOIR         1
159.0              1
139.0              1
389.0              1
0.0                1
Name: QTEFACT, Length: 90, dtype: int64

In [39]:
df[df['QTEFACT'] ==89.9]

,ID_ORDER,DATE-ADD,TIME-ADD,SEASON,P_MONTH,P_WEEK,COVID,CONFINEMENT,CURFEW,LOCATION,...,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE,TOTAL_QUANTITY
34265,410008714,2018-01-31,2018-01-31 11:44:42,Winter,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Ksar Hellal,...,NABEULÂ,26TN00F051316F18H,GRANDE TAILLE ( JASMIN ),TUNIQUE,MARINE/ROSE VIOLINE,89.9,1,62.930,30.0000,2
65879,54131936,2018-02-17,2018-02-17 15:39:51,Winter,Middle_of_Month,Week_End,Pre-Covid,NO,NO,Nabeul,...,BIR MROUA,4PUPH23BNRS18H,ISLD,PULL,PRUNE/BEIGE,89.9,1,53.940,40.0000,1
69132,640070187,2018-02-20,2018-02-20 17:18:30,Winter,Middle_of_Month,Start_of_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031191F18H,SASIO FEMME,PANTALON,PRUNE,89.9,1,62.930,30.0000,3
73001,640070224,2018-02-22,2018-02-23 19:04:02,Winter,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,4PA00H111264F18H,BLUE ISLAND,PANTALON,KAKI,89.9,1,50.344,20.0000,8
73292,640070224,2018-02-22,2018-02-23 19:04:02,Winter,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,4PA00H111264F18H,BLUE ISLAND,PANTALON,KAKI,89.9,1,62.930,30.0000,8
90228,54132258,2018-02-26,2018-02-26 18:00:24,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,4PA00H11960C18A,BLUE ISLAND,PANTALON,BLEU PETROLE,89.9,1,71.920,20.0000,3
96664,640070435,2018-02-28,2018-02-28 16:52:57,Winter,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,27CHSBS1PRF18H,BLEU & SON,CHAUSSURE,NOIR,89.9,1,44.950,50.0000,12
96665,640070435,2018-02-28,2018-02-28 16:52:57,Winter,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,27CHSBS1PRF18H,BLEU & SON,CHAUSSURE,NOIR,89.9,1,35.960,20.0000,12
96763,640070435,2018-02-28,2018-02-28 16:52:57,Winter,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031181F18H,SASIO FEMME,PANTALON,NOIR,89.9,1,50.344,20.0000,12
96781,640070435,2018-02-28,2018-02-28 16:52:57,Winter,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,27BZ00BS1300417H,BLEU & SON,BLOUSON,PRUNE,89.9,1,44.950,50.0000,12
96782,640070435,2018-02-28,2018-02-28 16:52:57,Winter,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,27BZ00BS1300417H,BLEU & SON,BLOUSON,PRUNE,89.9,1,35.960,20.0000,12
96944,640070435,2018-02-28,2018-02-28 16:52:57,Winter,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031181F18H,SASIO FEMME,PANTALON,NOIR,89.9,1,62.930,30.0000,12
114883,640070637,2018-03-07,2018-03-07 19:23:42,Winter,Start_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031173S18H,SASIO FEMME,PANTALON,JEAN DELAVE,89.9,1,71.920,20.0000,1
119431,640070725,2018-03-11,2018-03-11 13:18:34,Winter,Middle_of_Month,Week_end,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031174S18H,SASIO FEMME,PANTALON,JEAN DELAVE,89.9,1,71.920,20.0000,2
121665,640070788,2018-03-14,2018-03-14 18:54:45,Winter,Middle_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NaN,4CHD00H10846BC18H,BLUE ISLAND,CHEMISE,BLEU,89.9,1,71.920,20.0000,1
124140,640070825,2018-03-16,2018-03-16 19:10:29,Winter,Middle_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,15CH00F051371F18H,IPSOS,CHEMISE,NOIR,89.9,1,44.950,50.0000,1
127023,640070865,2018-03-18,2018-03-18 19:01:19,Winter,Middle_of_Month,Week_end,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,26RO00F08626F18H,GRANDE TAILLE ( JASMIN ),ROBE,NOIR/ECRU,89.9,1,44.950,50.0000,3
128554,640070879,2018-03-19,2018-03-19 16:56:37,Winter,Middle_of_Month,Start_of_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,4PA00H111032F17H,BLUE ISLAND,PANTALON,GRIS FONCE,89.9,1,44.950,50.0000,2
128596,640070877,2018-03-19,2018-03-19 16:15:46,Winter,Middle_of_Month,Start_of_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,15CH00F051371F18H,IPSOS,CHEMISE,NOIR,89.9,1,44.950,50.0000,1
129336,640070900,2018-03-20,2018-03-20 15:13:28,Spring,Middle_of_Month,Start_of_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031151S17E,SASIO FEMME,PANTALON,JEAN DELAVE,89.9,1,71.920,20.0000,1
133513,640070970,2018-03-23,2018-03-23 18:52:43,Spring,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,BEJA,27CHSBS1PRF18H,BLEU & SON,CHAUSSURE,CAMEL,89.9,1,26.970,70.0000,10
133958,640070970,2018-03-23,2018-03-23 18:52:43,Spring,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,BEJA,27CHSBS1PRF18H,BLEU & SON,CHAUSSURE,CAMEL,89.9,1,21.576,20.0000,10
136269,54132871,2018-03-24,2018-03-24 19:09:01,Spring,End_of_Month,Week_End,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,4CHMLH10477AMO18H,BLUE ISLAND,CHEMISE,MULTI-COULEURS,89.9,1,35.960,20.0000,4
137724,54132871,2018-03-24,2018-03-24 19:09:01,Spring,End_of_Month,Week_End,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,4CHMLH10477AMO18H,BLUE ISLAND,CHEMISE,MULTI-COULEURS,89.9,1,44.950,50.0000,4
144926,640071047,2018-03-27,2018-03-27 15:19:14,Spring,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6TN00F051436F18H,SASIO FEMME,TUNIQUE,MOUTARDE,89.9,1,71.920,20.0000,3
146806,640071058,2018-03-28,2018-03-28 10:08:11,Spring,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031180S18H,SASIO FEMME,PANTALON,JEAN,89.9,1,71.920,20.0000,3
148762,54132954,2018-03-29,2018-03-29 17:10:41,Spring,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6BL00F051423F18A,SASIO FEMME,BLOUSE,NOIR,89.9,1,35.960,60.0000,1
149466,640071106,2018-03-30,2018-03-30 16:10:12,Spring,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,15TN00ROS8218H,SASIO FEMME,TUNIQUE,CHOCOLAT,89.9,1,35.960,60.0000,1
151004,640071123,2018-03-31,2018-03-31 11:03:19,Spring,End_of_Month,Week_End,Pre-Covid,NO,NO,Nabeul,...,NABEUL,6SACMAC1918E,SASIO FEMME,SAC,NOIR,89.9,1,44.950,50.0000,2
151430,740065460,2018-03-31,2018-03-31 12:03:46,Spring,End_of_Month,Week_End,Pre-Covid,NO,NO,Hammamet,...,HAMMAMET,6PA00F031172S18H,SASIO FEMME,PANTALON,JEAN DELAVE,89.9,1,44.950,50.0000,2
158887,640071209,2018-04-06,2018-04-07 10:14:59,Spring,Start_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEUL,6CHS371PRF18E,SASIO FEMME,CHAUSSURE,ROSE PALE,89.9,1,62.930,30.0000,1
160769,54133138,2018-04-07,2018-04-07 19:33:01,Spring,Start_of_Month,Week_End,Pre-Covid,NO,NO,Nabeul,...,NABEUL,6BL00F051407F18H,SASIO FEMME,BLOUSE,MARINE/VERT,89.9,1,26.970,70.0000,3
238243,54134537,2018-06-23,2018-06-23 19:43:50,Summer,End_of_Month,Week_End,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6SD406CGA18E,SASIO FEMME,SANDALE,ROUGE,89.9,1,69.900,22.2469,1
242262,50125533,2018-06-28,2018-06-28 17:22:34,Summer,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Sasio Carrefour,...,KRAM,20TN00F051416CP17E,CAPSULE,TUNIQUE,MARINE,89.9,1,67.301,25.1383,2
254555,640072879,2018-07-10,2018-07-10 16:27:19,Summer,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,20TN00F051372CP17E,CAPSULE,TUNIQUE,BLANC,89.9,1,19.900,0.0000,2
319600,640074405,2018-08-18,2018-08-18 18:44:27,Summer,Middle_of_Month,Week_End,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,20CH00F051347CP17E,CAPSULE,CHEMISE,SAUMON,89.9,1,35.960,60.0000,14
319694,640074405,2018-08-18,2018-08-18 18:44:27,Summer,Middle_of_Month,Week_End,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,17PO00H171297F18E,ISLAND CLUB,POLO,BLANC/ROUGE,89.9,1,53.940,40.0000,14
324165,640074405,2018-08-18,2018-08-18 18:44:27,Summer,Middle_of_Month,Week_End,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,17PO00H171297F18E,ISLAND CLUB,POLO,BLANC/ROUGE,89.9,1,43.152,20.0000,14
324251,640074405,2018-08-18,2018-08-18 18:44:27,Summer,Middle_of_Month,Week_End,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,20CH00F051347CP17E,CAPSULE,CHEMISE,SAUMON,89.9,1,28.768,20.0000,14
342647,640074803,2018-08-28,2018-08-28 15:09:41,Summer,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031174S18H,SASIO FEMME,PANTALON,JEAN DELAVE,89.9,1,53.940,40.0000,1
345028,640074917,2018-08-30,2018-08-30 19:18:58,Summer,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,4CHC01H10714DF18E,BLUE ISLAND,CHEMISE,BLANC/ROUGE,89.9,1,35.960,20.0000,8
345055,640074917,2018-08-30,2018-08-30 19:18:58,Summer,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,4CHC00H10711DC18E,BLUE ISLAND,CHEMISE,BLEU/MOUTARDE,89.9,1,43.152,20.0000,8
348208,640074917,2018-08-30,2018-08-30 19:18:58,Summer,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,4CHC00H10711DC18E,BLUE ISLAND,CHEMISE,BLEU/MOUTARDE,89.9,1,53.940,40.0000,8
348212,640074917,2018-08-30,2018-08-30 19:18:58,Summer,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,4CHC01H10714DF18E,BLUE ISLAND,CHEMISE,BLANC/ROUGE,89.9,1,44.950,50.0000,8
349069,640074963,2018-08-31,2018-08-31 16:35:54,Summer,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031076F18S,SASIO FEMME,PANTALON,BEIGE,89.9,1,44.950,50.0000,12
349094,640074963,2018-08-31,2018-08-31 16:35:54,Summer,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6MU152CICT18E,SASIO FEMME,MULE,BEIGE,89.9,1,62.930,30.0000,12
349147,640074963,2018-08-31,2018-08-31 16:35:54,Summer,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6TN00F051436F18H,SASIO FEMME,TUNIQUE,NOIR,89.9,1,35.960,60.0000,12
352289,640074963,2018-08-31,2018-08-31 16:35:54,Summer,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6TN00F051436F18H,SASIO FEMME,TUNIQUE,NOIR,89.9,1,28.768,20.0000,12
352638,640074963,2018-08-31,2018-08-31 16:35:54,Summer,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6MU152CICT18E,SASIO FEMME,MULE,BEIGE,89.9,1,50.344,20.0000,12
352648,640074963,2018-08-31,2018-08-31 16:35:54,Summer,End_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031076F18S,SASIO FEMME,PANTALON,BEIGE,89.9,1,35.960,20.0000,12
368624,54136793,2018-09-05,2018-09-05 12:09:15,Summer,Start_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031173S18H,SASIO FEMME,PANTALON,JEAN DELAVE,89.9,1,43.152,20.0000,6
368628,54136793,2018-09-05,2018-09-05 12:09:15,Summer,Start_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031177S18H,SASIO FEMME,PANTALON,GRIS,89.9,1,28.768,20.0000,6
369640,54136793,2018-09-05,2018-09-05 12:09:15,Summer,Start_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031177S18H,SASIO FEMME,PANTALON,GRIS,89.9,1,35.960,60.0000,6
369643,54136793,2018-09-05,2018-09-05 12:09:15,Summer,Start_of_Month,Mid_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PA00F031173S18H,SASIO FEMME,PANTALON,JEAN DELAVE,89.9,1,53.940,40.0000,6
386896,800151799,2018-09-11,2018-09-11 16:42:52,Summer,Middle_of_Month,Start_of_Week,Pre-Covid,NO,NO,Lafayette,...,NABEUL,6RO00F08666CP18E,SASIO FEMME,ROBE,NOIR,89.9,1,43.152,20.0000,6
387919,800151799,2018-09-11,2018-09-11 16:42:52,Summer,Middle_of_Month,Start_of_Week,Pre-Covid,NO,NO,Lafayette,...,NABEUL,6RO00F08666CP18E,SASIO FEMME,ROBE,NOIR,89.9,1,53.940,40.0000,6
421740,640075725,2018-09-25,2018-09-25 17:37:55,Autumn,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,4PA00H11960C18A,BLUE ISLAND,PANTALON,CAMEL,89.9,1,53.940,40.0000,6
421741,640075725,2018-09-25,2018-09-25 17:37:55,Autumn,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,4PA00H11960C18A,BLUE ISLAND,PANTALON,CAMEL,89.9,1,37.758,30.0000,6
441102,54137504,2018-09-30,2018-09-30 17:42:03,Autumn,End_of_Month,Week_end,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,4MU10925RID18E,BLUE ISLAND,MULE,NOIR,89.9,1,26.970,70.0000,1
536110,54138712,2018-12-31,2018-12-31 14:07:12,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Nabeul,...,NABEULÂ,6PU570NRS19H,SASIO FEMME,PULL,MARINE,89.9,1,NaN,NaN,2

In [40]:
hour=df['TIME-ADD'].dt.hour
hour

0         12
1         16
2         17
3         14
4         16
          ..
536843    13
536844    13
536845    14
536846    11
536847    11
Name: TIME-ADD, Length: 536848, dtype: int64

In [41]:
# Create the dictionary for Hour 

H = {0:'Early_morning', 1:'Early_morning', 2:'Early_morning', 3:'Early_morning',4:'Early_morning',5:'Early_morning',6:'Early_morning',7:'Early_morning',8:'Early_morning',9:'Late_morning',10:'Late_morning',11:'Late_morning',12:'Early_afternoon',13:'Early_afternoon',14:'Early_afternoon',15:'Late_afternoon',16:'Late_afternoon',17:'Late_afternoon',18:'Evening',19:'Evening',20:'Evening',21:'Night',22:'Night',23:'Night'}
# Use the dictionary to map the 'Hour'
df['HOUR'] = hour.map(H)
#display the first 5 lines
df

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,ID_ORDER,DATE-ADD,TIME-ADD,SEASON,P_MONTH,P_WEEK,COVID,CONFINEMENT,CURFEW,LOCATION,...,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE,TOTAL_QUANTITY,HOUR
0,66032518,2018-01-01,2018-01-01 12:06:50,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Mehdia,...,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0000,NaN,4,Early_afternoon
1,80143573,2018-01-01,2018-01-01 16:03:37,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Lafayette,...,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN,1,Late_afternoon
2,80143576,2018-01-01,2018-01-01 17:38:26,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Lafayette,...,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN,2,Late_afternoon
3,80143572,2018-01-01,2018-01-01 14:52:08,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Lafayette,...,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN,1,Early_afternoon
4,80143574,2018-01-01,2018-01-01 16:56:04,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,Lafayette,...,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN,1,Late_afternoon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31,2018-12-31 13:40:18,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Bizerte,...,ISLAND CLUB,CHEMISE,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN,2,Early_afternoon
536844,24168598,2018-12-31,2018-12-31 13:39:30,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Bizerte,...,ISLAND CLUB,PANTALON,MARRON,129.0000,1,NaN,NaN,NaN,2,Early_afternoon
536845,24168602,2018-12-31,2018-12-31 14:40:15,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Bizerte,...,BLUE ISLAND,PULL,GRIS PALE,89.9000,1,NaN,NaN,NaN,2,Early_afternoon
536846,14142423,2018-12-31,2018-12-31 11:04:33,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Blue Island Zephyr,...,BLEU & SON,PANTALON,CAMEL,59.9000,-1,-59.8,0.1669,NaN,5,Late_morning
536847,14142426,2018-12-31,2018-12-31 11:16:19,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,Blue Island Zephyr,...,BLUE ISLAND,PANTALON,BEIGE,109.0000,-1,-98.9,9.2661,NaN,2,Late_morning

In [42]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','HOUR','SEASON','P_MONTH','P_WEEK','COVID','CONFINEMENT','CURFEW','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE','TOTAL_QUANTITY']]
df

,ID_ORDER,DATE-ADD,TIME-ADD,HOUR,SEASON,P_MONTH,P_WEEK,COVID,CONFINEMENT,CURFEW,...,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE,TOTAL_QUANTITY
0,66032518,2018-01-01,2018-01-01 12:06:50,Early_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0000,NaN,4
1,80143573,2018-01-01,2018-01-01 16:03:37,Late_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,4PUPH45NRS18H,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN,1
2,80143576,2018-01-01,2018-01-01 17:38:26,Late_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,6CR04NRS18H,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN,2
3,80143572,2018-01-01,2018-01-01 14:52:08,Early_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN,1
4,80143574,2018-01-01,2018-01-01 16:56:04,Late_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,6SW00F071556F18H,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31,2018-12-31 13:40:18,Early_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,17CHC00H10830DC19H,ISLAND CLUB,CHEMISE,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN,2
536844,24168598,2018-12-31,2018-12-31 13:39:30,Early_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,17PA00H111360C19H,ISLAND CLUB,PANTALON,MARRON,129.0000,1,NaN,NaN,NaN,2
536845,24168602,2018-12-31,2018-12-31 14:40:15,Early_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,4PU18CND18H,BLUE ISLAND,PULL,GRIS PALE,89.9000,1,NaN,NaN,NaN,2
536846,14142423,2018-12-31,2018-12-31 11:04:33,Late_morning,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,27PA00BS1105219H,BLEU & SON,PANTALON,CAMEL,59.9000,-1,-59.8,0.1669,NaN,5
536847,14142426,2018-12-31,2018-12-31 11:16:19,Late_morning,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,4PA00H111351F19H,BLUE ISLAND,PANTALON,BEIGE,109.0000,-1,-98.9,9.2661,NaN,2

In [43]:
df['TIME-ADD'] = pd.Series([val.time() for val in df['TIME-ADD']])
df

,ID_ORDER,DATE-ADD,TIME-ADD,HOUR,SEASON,P_MONTH,P_WEEK,COVID,CONFINEMENT,CURFEW,...,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE,TOTAL_QUANTITY
0,66032518,2018-01-01,12:06:50,Early_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,6BL00F051401F18H,SASIO FEMME,BLOUSE,ROUX,79.9,-1,-39.95,50.0000,NaN,4
1,80143573,2018-01-01,16:03:37,Late_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,4PUPH45NRS18H,BLUE ISLAND,PULL,BLEU,79.9,1,NaN,NaN,NaN,1
2,80143576,2018-01-01,17:38:26,Late_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,6CR04NRS18H,SASIO FEMME,CARDIGAN,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN,2
3,80143572,2018-01-01,14:52:08,Early_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,22BL00FR0501518H,REQUEST FEMME,BLOUSE,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN,1
4,80143574,2018-01-01,16:56:04,Late_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,6SW00F071556F18H,SASIO FEMME,SWEAT SHIRT,ROSE CLAIR,59.9,1,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31,13:40:18,Early_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,17CHC00H10830DC19H,ISLAND CLUB,CHEMISE,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN,2
536844,24168598,2018-12-31,13:39:30,Early_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,17PA00H111360C19H,ISLAND CLUB,PANTALON,MARRON,129.0000,1,NaN,NaN,NaN,2
536845,24168602,2018-12-31,14:40:15,Early_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,4PU18CND18H,BLUE ISLAND,PULL,GRIS PALE,89.9000,1,NaN,NaN,NaN,2
536846,14142423,2018-12-31,11:04:33,Late_morning,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,27PA00BS1105219H,BLEU & SON,PANTALON,CAMEL,59.9000,-1,-59.8,0.1669,NaN,5
536847,14142426,2018-12-31,11:16:19,Late_morning,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,4PA00H111351F19H,BLUE ISLAND,PANTALON,BEIGE,109.0000,-1,-98.9,9.2661,NaN,2

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536848 entries, 0 to 536847
Data columns (total 32 columns):
ID_ORDER          536848 non-null int32
DATE-ADD          536848 non-null datetime64[ns]
TIME-ADD          536848 non-null object
HOUR              536848 non-null object
SEASON            536848 non-null object
P_MONTH           536848 non-null object
P_WEEK            536848 non-null object
COVID             536848 non-null object
CONFINEMENT       536848 non-null object
CURFEW            536848 non-null object
LOCATION          536848 non-null object
ID_CUSTOMER       536848 non-null object
LAST_NAME         536848 non-null object
FIRST_NAME        271624 non-null object
YX_LIBELLE        426416 non-null object
BIRTH_YEAR        536840 non-null datetime64[ns]
AGE               536840 non-null float64
TELEX             267784 non-null object
EMAIL             134450 non-null object
ADRESS            177862 non-null object
POSTAL_CODE       439634 non-null object
CITY              439129 non-null object
ITEM_CODE         536847 non-null object
CC_LIBELLE        536387 non-null object
CC_LIBELLE_1      536387 non-null object
DESIGNATION       536387 non-null object
PVTTC             536848 non-null object
QTEFACT           536848 non-null object
PUTTCNET          445275 non-null object
MLR_REMISE        445214 non-null float64
GTR_LIBELLE       439960 non-null object
TOTAL_QUANTITY    536848 non-null int64
dtypes: datetime64[ns](2), float64(2), int32(1), int64(1), object(26)
memory usage: 129.0+ MB

In [45]:
new_row2070 = {'POST_CODE':'2070', 'Delegation':'LA MARSA', 'poverty rate':2.2, 'zone':'urbaine','orientation':'nord-est'}
df2 = df2.append(new_row2070, ignore_index=True)

In [46]:
df['POSTAL_CODE']=df['POSTAL_CODE'].apply(str)
df2['POST_CODE']=df2['POST_CODE'].apply(str)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 5 columns):
POST_CODE       970 non-null object
Delegation      970 non-null object
poverty rate    970 non-null float64
zone            970 non-null object
orientation     970 non-null object
dtypes: float64(1), object(4)
memory usage: 38.0+ KB

In [69]:
df2

    POST_CODE    Delegation  poverty rate     zone orientation class
0        2072       SEJOUMI          11.5  urbaine    nord-est    C+
1        1007       SEJOUMI          11.5  urbaine    nord-est    C+
2        2023   JEBEL JLOUD           9.5  urbaine    nord-est    C+
3        1046   JEBEL JLOUD           9.5  urbaine    nord-est    C+
4        1095  SIDI HASSINE           9.4  urbaine    nord-est    C+
..        ...           ...           ...      ...         ...   ...
965      4273   KEBILI NORD          12.3  urbaine   sud-ouest    C+
966      4237   KEBILI NORD          12.3  urbaine   sud-ouest    C+
967      4232   KEBILI NORD          12.3  urbaine   sud-ouest    C+
968      4235   KEBILI NORD          12.3  urbaine   sud-ouest    C+
969      2070      LA MARSA           2.2  urbaine    nord-est     B

[970 rows x 6 columns]

In [48]:
def get_region(code, train):
  try:
    if str(code) in str(train['POST_CODE'].unique()):
        return str(train[train['POST_CODE']== str(code)]['orientation'].values[0])
  except Exception :
    print (str(code))

In [49]:
df['region'] = df.apply(lambda x: get_region(x.POSTAL_CODE, df2), axis=1)

900
710
710




800
800
800
800
800
800
24
24
803
803
700
700
900
900
142
142
3
3
3
3
3
3
3
3
801
801

In [50]:
df['region'].value_counts()

nord-est        365108
centre-est       36180
nord-ouest       11337
centre-ouest     10319
sud-est           5950
sud-ouest         5616
Name: region, dtype: int64

In [68]:
df['POSTAL_CODE'][df['region'].isnull()]

KeyError: 'region'

In [52]:
df2[df2['POST_CODE']=='2037']

    POST_CODE    Delegation  poverty rate     zone orientation
109      2037  ARIANA Ville           1.3  urbaine    nord-est

In [53]:
df2

    POST_CODE    Delegation  poverty rate     zone orientation
0        2072       SEJOUMI          11.5  urbaine    nord-est
1        1007       SEJOUMI          11.5  urbaine    nord-est
2        2023   JEBEL JLOUD           9.5  urbaine    nord-est
3        1046   JEBEL JLOUD           9.5  urbaine    nord-est
4        1095  SIDI HASSINE           9.4  urbaine    nord-est
..        ...           ...           ...      ...         ...
965      4273   KEBILI NORD          12.3  urbaine   sud-ouest
966      4237   KEBILI NORD          12.3  urbaine   sud-ouest
967      4232   KEBILI NORD          12.3  urbaine   sud-ouest
968      4235   KEBILI NORD          12.3  urbaine   sud-ouest
969      2070      LA MARSA           2.2  urbaine    nord-est

[970 rows x 5 columns]

In [54]:
df.iloc[3575 ,:]

ID_ORDER                         40037874
DATE-ADD              2018-01-05 00:00:00
TIME-ADD                         17:47:14
HOUR                       Late_afternoon
SEASON                             Winter
P_MONTH                    Start_of_Month
P_WEEK                           Mid_Week
COVID                           Pre-Covid
CONFINEMENT                            NO
CURFEW                                 NO
LOCATION                           Ennasr
ID_CUSTOMER                      S2021453
LAST_NAME                          JAOUNI
FIRST_NAME                         Wahida
YX_LIBELLE                            NaN
BIRTH_YEAR            1976-01-01 00:00:00
AGE                                    42
TELEX                            97532141
EMAIL             wjaouini.lawer@yahoo.fr
ADRESS                Rsdbarr B31 Nasser2
POSTAL_CODE                          2038
CITY                               ARIANA
ITEM_CODE                22TN00FR0501418H
CC_LIBELLE                  REQUEST FEMME
CC_LIBELLE_1                      TUNIQUE
DESIGNATION                    NOIR/ROUGE
PVTTC                                59.9
QTEFACT                                 1
PUTTCNET                              NaN
MLR_REMISE                            NaN
GTR_LIBELLE                           NaN
TOTAL_QUANTITY                          2
region                               None
Name: 3575, dtype: object

In [55]:
df.iloc[536836 ,:]

ID_ORDER                     24168610
DATE-ADD          2018-12-31 00:00:00
TIME-ADD                     15:05:22
HOUR                   Late_afternoon
SEASON                         Winter
P_MONTH                  End_of_Month
P_WEEK                  Start_of_Week
COVID                       Pre-Covid
CONFINEMENT                        NO
CURFEW                             NO
LOCATION                      Bizerte
ID_CUSTOMER                 BC0240558
LAST_NAME                    ALLOUCHE
FIRST_NAME                     Mohsen
YX_LIBELLE                 PARTENAIRE
BIRTH_YEAR        1900-01-01 00:00:00
AGE                           64.6614
TELEX                        23568164
EMAIL                             NaN
ADRESS                        Bizerte
POSTAL_CODE                       nan
CITY                              NaN
ITEM_CODE                4DDL046GS19H
CC_LIBELLE                BLUE ISLAND
CC_LIBELLE_1                 DOUDOUNE
DESIGNATION                      NOIR
PVTTC                        229.0000
QTEFACT                             1
PUTTCNET                          NaN
MLR_REMISE                        NaN
GTR_LIBELLE                       NaN
TOTAL_QUANTITY                      2
region                           None
Name: 536836, dtype: object

In [56]:
def get_area(code, train):
  try:
    if str(code) in str(train['POST_CODE'].unique()):
        return str(train[train['POST_CODE']== str(code)]['zone'].values[0])
  except Exception :
    print (str(code))

In [57]:
df['area'] = df.apply(lambda x: get_area(x.POSTAL_CODE, df2), axis=1)

900
710
710




800
800
800
800
800
800
24
24
803
803
700
700
900
900
142
142
3
3
3
3
3
3
3
3
801
801

In [58]:
df['area'].value_counts()

urbaine    434426
rurale         84
Name: area, dtype: int64

In [59]:
df[df['POSTAL_CODE']=='2070']

,ID_ORDER,DATE-ADD,TIME-ADD,HOUR,SEASON,P_MONTH,P_WEEK,COVID,CONFINEMENT,CURFEW,...,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE,TOTAL_QUANTITY,region,area
427,69025950,2018-01-02,18:31:14,Evening,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,TOP,GRIS CLAIR,49.9,1,11.456,77.0416,BON ACHAT,5,nord-est,urbaine
428,69025950,2018-01-02,18:31:14,Evening,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,TOP,GRIS CLAIR,49.9,1,3.767,67.1141,FidÃ©litÃ©,5,nord-est,urbaine
429,69025947,2018-01-02,16:59:39,Late_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,VESTE,KAKI,169.9,1,84.95,50.0000,2 eme 50 et le 3 eme 100,2,nord-est,urbaine
430,69025950,2018-01-02,18:31:14,Evening,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,PULL,MOUTARDE/MARINE,49.9,1,0,100.0000,2 eme 50 et le 3 eme 100,5,nord-est,urbaine
434,69025950,2018-01-02,18:31:14,Evening,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,PANTALON,JEAN DELAVE,79.9,1,18.344,77.0416,BON ACHAT,5,nord-est,urbaine
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534378,37020133,2018-12-31,17:35:26,Late_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,TOP,NOIR/GRIS CLAIR,49.9000,1,0,100.0000,Vente flash,2,nord-est,urbaine
535855,37020129,2018-12-31,16:32:50,Late_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,CHAUSSURE,CAMEL,169.0000,1,NaN,NaN,NaN,2,nord-est,urbaine
535874,37020135,2018-12-31,17:42:02,Late_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,DOUDOUNE,BORDEAUX,249.0000,1,NaN,NaN,NaN,2,nord-est,urbaine
535890,37020133,2018-12-31,17:35:26,Late_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,PULL,BRUN,59.9000,1,NaN,NaN,NaN,2,nord-est,urbaine
536041,420004136,2018-12-31,10:46:31,Late_morning,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,PONCHO,BORDEAUX,69.9000,1,NaN,NaN,NaN,2,nord-est,urbaine

In [60]:
df = df.rename(columns={'region': 'REGION'})
df = df.rename(columns={'area': 'AREA'})

In [61]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 5 columns):
POST_CODE       970 non-null object
Delegation      970 non-null object
poverty rate    970 non-null float64
zone            970 non-null object
orientation     970 non-null object
dtypes: float64(1), object(4)
memory usage: 38.0+ KB

In [62]:
cut_class = ['A', 'B', 'C+','C-', 'D', 'E']
cut_bins =[0, 2, 8, 18, 26, 42, 55]
df2['class'] = pd.cut(df2['poverty rate'], bins=cut_bins, labels = cut_class)
df2

    POST_CODE    Delegation  poverty rate     zone orientation class
0        2072       SEJOUMI          11.5  urbaine    nord-est    C+
1        1007       SEJOUMI          11.5  urbaine    nord-est    C+
2        2023   JEBEL JLOUD           9.5  urbaine    nord-est    C+
3        1046   JEBEL JLOUD           9.5  urbaine    nord-est    C+
4        1095  SIDI HASSINE           9.4  urbaine    nord-est    C+
..        ...           ...           ...      ...         ...   ...
965      4273   KEBILI NORD          12.3  urbaine   sud-ouest    C+
966      4237   KEBILI NORD          12.3  urbaine   sud-ouest    C+
967      4232   KEBILI NORD          12.3  urbaine   sud-ouest    C+
968      4235   KEBILI NORD          12.3  urbaine   sud-ouest    C+
969      2070      LA MARSA           2.2  urbaine    nord-est     B

[970 rows x 6 columns]

In [63]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 6 columns):
POST_CODE       970 non-null object
Delegation      970 non-null object
poverty rate    970 non-null float64
zone            970 non-null object
orientation     970 non-null object
class           970 non-null category
dtypes: category(1), float64(1), object(4)
memory usage: 39.2+ KB

In [64]:
def get_class(code, train):
  try:
    if str(code) in str(train['POST_CODE'].unique()):
      return str(train[train['POST_CODE']== str(code)]['class'].values[0])
  except Exception :
    print (str(code))

In [65]:
df['CLASS'] = df.apply(lambda x: get_class(x.POSTAL_CODE, df2), axis=1)

900
710
710




800
800
800
800
800
800
24
24
803
803
700
700
900
900
142
142
3
3
3
3
3
3
3
3
801
801

In [66]:
df

,ID_ORDER,DATE-ADD,TIME-ADD,HOUR,SEASON,P_MONTH,P_WEEK,COVID,CONFINEMENT,CURFEW,...,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE,TOTAL_QUANTITY,REGION,AREA,CLASS
0,66032518,2018-01-01,12:06:50,Early_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,ROUX,79.9,-1,-39.95,50.0000,NaN,4,nord-est,urbaine,B
1,80143573,2018-01-01,16:03:37,Late_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,BLEU,79.9,1,NaN,NaN,NaN,1,nord-est,urbaine,B
2,80143576,2018-01-01,17:38:26,Late_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,MARINE/ROSE PALE,84.9,1,NaN,NaN,NaN,2,nord-est,urbaine,B
3,80143572,2018-01-01,14:52:08,Early_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,MARINE/ROSE VIOLINE,49.9,1,NaN,NaN,NaN,1,nord-est,urbaine,B
4,80143574,2018-01-01,16:56:04,Late_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,ROSE CLAIR,59.9,1,NaN,NaN,NaN,1,nord-est,urbaine,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536843,24168599,2018-12-31,13:40:18,Early_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,BEIGE/MARRON,109.0000,1,NaN,NaN,NaN,2,nord-est,urbaine,C+
536844,24168598,2018-12-31,13:39:30,Early_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,MARRON,129.0000,1,NaN,NaN,NaN,2,nord-est,urbaine,C+
536845,24168602,2018-12-31,14:40:15,Early_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,GRIS PALE,89.9000,1,NaN,NaN,NaN,2,None,None,None
536846,14142423,2018-12-31,11:04:33,Late_morning,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,CAMEL,59.9000,-1,-59.8,0.1669,NaN,5,None,None,None
536847,14142426,2018-12-31,11:16:19,Late_morning,Winter,End_of_Month,Start_of_Week,Pre-Covid,NO,NO,...,BEIGE,109.0000,-1,-98.9,9.2661,NaN,2,nord-est,urbaine,B

In [67]:
df.isnull().sum()

ID_ORDER               0
DATE-ADD               0
TIME-ADD               0
HOUR                   0
SEASON                 0
P_MONTH                0
P_WEEK                 0
COVID                  0
CONFINEMENT            0
CURFEW                 0
LOCATION               0
ID_CUSTOMER            0
LAST_NAME              0
FIRST_NAME        265224
YX_LIBELLE        110432
BIRTH_YEAR             8
AGE                    8
TELEX             269064
EMAIL             402398
ADRESS            358986
POSTAL_CODE            0
CITY               97719
ITEM_CODE              1
CC_LIBELLE           461
CC_LIBELLE_1         461
DESIGNATION          461
PVTTC                  0
QTEFACT                0
PUTTCNET           91573
MLR_REMISE         91634
GTR_LIBELLE        96888
TOTAL_QUANTITY         0
REGION            102338
AREA              102338
CLASS             102338
dtype: int64