In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats as st
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter
from scipy.stats import chi2_contingency
from collections import Counter
from math import sqrt

In [2]:
df = pd.read_csv(r'C:\Users\sofi\Downloads\wetransfer-3ab4ca\2020.csv',sep=';', encoding = 'ISO-8859-1',
                     names=['ID_ORDER', 'DATE-ADD','TIME-ADD','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE'],
                     dtype={'ID_ORDER':int,'DATE-ADD':object,'TIME-ADD':object,'LOCATION':int,'ID_CUSTOMER':object,'LAST_NAME':object,'FIRST_NAME':object,'YX_LIBELLE':object,'BIRTH_YEAR':object,'TELEX':object,'EMAIL':object,'ADRESS':object,'POSTAL_CODE':object,'CITY':object,'ITEM_CODE':object,'CC_LIBELLE':object,'CC_LIBELLE_1':object})

df

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,800165848,2020-01-01 00:00:00.000,2020-01-01 18:30:31.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4BZ053SCGS20H,BLUE ISLAND,BLOUSON,NOIR,249.0000,1.0,NaN,NaN,NaN
1,800165832,2020-01-01 00:00:00.000,2020-01-01 14:40:21.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6BTS399CPRF19H,SASIO FEMME,BOOTS,NOIR,198.0000,1.0,NaN,NaN,NaN
2,800165836,2020-01-01 00:00:00.000,2020-01-01 15:35:49.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PAJ00H111488F20H,BLUE ISLAND,PANTALON,JEAN DELAVE,139.0000,1.0,NaN,NaN,NaN
3,800165842,2020-01-01 00:00:00.000,2020-01-01 16:46:52.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,13PAJ00H111475C20H,ISLD,PANTALON,JEAN DELAVE,109.0000,1.0,NaN,NaN,NaN
4,800165840,2020-01-01 00:00:00.000,2020-01-01 16:36:19.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,31PA01F031245F19H,STUDIO,PANTALON,NOIR,139.0000,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359445,65047834,2020-12-31 00:00:00.000,2020-12-31 14:51:38.000,65,S2038540,KEBALIA,Houda,NaN,80,98767027,...,BEN AROUS,4PA01H111503F20H,BLUE ISLAND,PANTALON,NOIR,119.0000,1.0,0.0,100.0,2=-100% sur le moins chers
359446,65047822,2020-12-31 00:00:00.000,2020-12-31 12:45:53.000,65,BC0650862,NITCHA,Mouhamed,PARTENAIRE,1900,97514064,...,NaN,4PA00H111493F20H,BLUE ISLAND,PANTALON,BLEU ANTRACITE,119.0000,1.0,0.0,100.0,2=-100% sur le moins chers
359447,65047837,2020-12-31 00:00:00.000,2020-12-31 15:05:23.000,65,B0136604,BELGITH,Yasmine,NaN,1900,23060371,...,NABEUL,4PUBB18BBC21H,BLUE ISLAND,PULL,MOUTARDE,109.0000,1.0,0.0,100.0,2=-100% sur le moins chers
359448,65047817,2020-12-31 00:00:00.000,2020-12-31 10:12:40.000,65,BC0650843,SOFIN,Bel Ate,PARTENAIRE,1900,53419759,...,NaN,4ESPBKT04MKB20E,BLUE ISLAND,ESPADRILLE,NOIR,229.0000,1.0,0.0,100.0,2=-100% sur le moins chers
359449,65047843,2020-12-31 00:00:00.000,2020-12-31 15:55:34.000,65,B0129118,CHARFEDDIN,Amal,NaN,1966,95370670,...,TUNISÂ,17PAJ00H111552F20E,ISLAND CLUB,PANTALON,JEAN DELAVE,149.0000,1.0,0.0,100.0,2=-100% sur le moins chers

In [3]:
df.isnull().sum()

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            1
FIRST_NAME      182770
YX_LIBELLE       65201
BIRTH_YEAR           0
TELEX           185296
EMAIL           281210
ADRESS          252135
POSTAL_CODE      71463
CITY             72085
ITEM_CODE            4
CC_LIBELLE         292
CC_LIBELLE_1       292
DESIGNATION       2014
PVTTC                0
QTEFACT              0
PUTTCNET         99166
MLR_REMISE       99196
GTR_LIBELLE     102947
dtype: int64

In [4]:
df['PVTTC'].value_counts()

89.9000            33493
98.9000            33343
109.0000           32724
4.9000             30968
119.0000           30054
                   ...
GRIS CLAIR/GRIS        1
BLEU ANTRACITE         1
NOIR/ROUX              1
CIEL                   1
ROSE CLAIR             1
Name: PVTTC, Length: 131, dtype: int64

In [5]:
df['PVTTC'] = df['PVTTC'].apply(pd.to_numeric, errors='coerce').fillna(0).astype(float).dropna()

In [6]:
df = df[df.PVTTC != 0]

In [7]:
df

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,800165848,2020-01-01 00:00:00.000,2020-01-01 18:30:31.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4BZ053SCGS20H,BLUE ISLAND,BLOUSON,NOIR,249.0,1.0,NaN,NaN,NaN
1,800165832,2020-01-01 00:00:00.000,2020-01-01 14:40:21.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6BTS399CPRF19H,SASIO FEMME,BOOTS,NOIR,198.0,1.0,NaN,NaN,NaN
2,800165836,2020-01-01 00:00:00.000,2020-01-01 15:35:49.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PAJ00H111488F20H,BLUE ISLAND,PANTALON,JEAN DELAVE,139.0,1.0,NaN,NaN,NaN
3,800165842,2020-01-01 00:00:00.000,2020-01-01 16:46:52.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,13PAJ00H111475C20H,ISLD,PANTALON,JEAN DELAVE,109.0,1.0,NaN,NaN,NaN
4,800165840,2020-01-01 00:00:00.000,2020-01-01 16:36:19.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,31PA01F031245F19H,STUDIO,PANTALON,NOIR,139.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359445,65047834,2020-12-31 00:00:00.000,2020-12-31 14:51:38.000,65,S2038540,KEBALIA,Houda,NaN,80,98767027,...,BEN AROUS,4PA01H111503F20H,BLUE ISLAND,PANTALON,NOIR,119.0,1.0,0.0,100.0,2=-100% sur le moins chers
359446,65047822,2020-12-31 00:00:00.000,2020-12-31 12:45:53.000,65,BC0650862,NITCHA,Mouhamed,PARTENAIRE,1900,97514064,...,NaN,4PA00H111493F20H,BLUE ISLAND,PANTALON,BLEU ANTRACITE,119.0,1.0,0.0,100.0,2=-100% sur le moins chers
359447,65047837,2020-12-31 00:00:00.000,2020-12-31 15:05:23.000,65,B0136604,BELGITH,Yasmine,NaN,1900,23060371,...,NABEUL,4PUBB18BBC21H,BLUE ISLAND,PULL,MOUTARDE,109.0,1.0,0.0,100.0,2=-100% sur le moins chers
359448,65047817,2020-12-31 00:00:00.000,2020-12-31 10:12:40.000,65,BC0650843,SOFIN,Bel Ate,PARTENAIRE,1900,53419759,...,NaN,4ESPBKT04MKB20E,BLUE ISLAND,ESPADRILLE,NOIR,229.0,1.0,0.0,100.0,2=-100% sur le moins chers
359449,65047843,2020-12-31 00:00:00.000,2020-12-31 15:55:34.000,65,B0129118,CHARFEDDIN,Amal,NaN,1966,95370670,...,TUNISÂ,17PAJ00H111552F20E,ISLAND CLUB,PANTALON,JEAN DELAVE,149.0,1.0,0.0,100.0,2=-100% sur le moins chers

In [8]:
df.replace({'0000-00-00': np.nan},inplace=True)

C:\Users\sofi\Anacondaa\lib\site-packages\pandas\core\frame.py:4263: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

In [9]:
#convert DataFrame column to date-time:'GP_DATEPIECE'
df['DATE-ADD'] = pd.to_datetime(df['DATE-ADD'], format = '%Y-%m-%d')
df['DATE-ADD']= pd.to_datetime(df['DATE-ADD'], errors='ignore')

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [10]:
df['TIME-ADD'] = pd.to_datetime(df['TIME-ADD'])
df

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,800165848,2020-01-01,2020-01-01 18:30:31,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4BZ053SCGS20H,BLUE ISLAND,BLOUSON,NOIR,249.0,1.0,NaN,NaN,NaN
1,800165832,2020-01-01,2020-01-01 14:40:21,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6BTS399CPRF19H,SASIO FEMME,BOOTS,NOIR,198.0,1.0,NaN,NaN,NaN
2,800165836,2020-01-01,2020-01-01 15:35:49,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PAJ00H111488F20H,BLUE ISLAND,PANTALON,JEAN DELAVE,139.0,1.0,NaN,NaN,NaN
3,800165842,2020-01-01,2020-01-01 16:46:52,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,13PAJ00H111475C20H,ISLD,PANTALON,JEAN DELAVE,109.0,1.0,NaN,NaN,NaN
4,800165840,2020-01-01,2020-01-01 16:36:19,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,31PA01F031245F19H,STUDIO,PANTALON,NOIR,139.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359445,65047834,2020-12-31,2020-12-31 14:51:38,65,S2038540,KEBALIA,Houda,NaN,80,98767027,...,BEN AROUS,4PA01H111503F20H,BLUE ISLAND,PANTALON,NOIR,119.0,1.0,0.0,100.0,2=-100% sur le moins chers
359446,65047822,2020-12-31,2020-12-31 12:45:53,65,BC0650862,NITCHA,Mouhamed,PARTENAIRE,1900,97514064,...,NaN,4PA00H111493F20H,BLUE ISLAND,PANTALON,BLEU ANTRACITE,119.0,1.0,0.0,100.0,2=-100% sur le moins chers
359447,65047837,2020-12-31,2020-12-31 15:05:23,65,B0136604,BELGITH,Yasmine,NaN,1900,23060371,...,NABEUL,4PUBB18BBC21H,BLUE ISLAND,PULL,MOUTARDE,109.0,1.0,0.0,100.0,2=-100% sur le moins chers
359448,65047817,2020-12-31,2020-12-31 10:12:40,65,BC0650843,SOFIN,Bel Ate,PARTENAIRE,1900,53419759,...,NaN,4ESPBKT04MKB20E,BLUE ISLAND,ESPADRILLE,NOIR,229.0,1.0,0.0,100.0,2=-100% sur le moins chers
359449,65047843,2020-12-31,2020-12-31 15:55:34,65,B0129118,CHARFEDDIN,Amal,NaN,1966,95370670,...,TUNISÂ,17PAJ00H111552F20E,ISLAND CLUB,PANTALON,JEAN DELAVE,149.0,1.0,0.0,100.0,2=-100% sur le moins chers

In [11]:
# Create the dictionary for  ETABLISSEMENT
etab = {44:'Djerba',28:'Sasio Geant',31:'Blue Island Carrefour',62:'Central Park',16:'Sousse',8:'Lafayette',130:'Blue Island Palmarium',50:'Sasio Carrefour',24:'Bizerte',40:'Ennasr',56:'Sasio Manzah VI',14:'Blue Island Zephyr',61:'La Soukra',63:'Sasio Menzah V',54:'Nabeul',37:'Sasio Zephyr',134:'Sasio Palmarium',64:'Nabeul',65:'Blue Island Manar',36:'Sasio Manar',25:'Blue Island Djerba',52:'Blue Island Menzah VI',66:'Mehdia',42:'Lac 2',67:'Sfax',68:'Monastir',51:'Blue Island Menzah V',69:'El Kef',35:'Kairouan',15:'Sasio Mseken',27:'Sasio Mseken',60:'Sasio Djerba',18:'Kelibia',41:'Ksar Hellal',74:'Hammamet'}
df['LOCATION'] = df['LOCATION'].map(etab)
#display the first 5 lines
df.isnull().sum()

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME      182679
YX_LIBELLE       65071
BIRTH_YEAR           0
TELEX           185202
EMAIL           280975
ADRESS          251936
POSTAL_CODE      71360
CITY             71982
ITEM_CODE            0
CC_LIBELLE          52
CC_LIBELLE_1        52
DESIGNATION       1774
PVTTC                0
QTEFACT              0
PUTTCNET         98926
MLR_REMISE       98926
GTR_LIBELLE     102677
dtype: int64

In [12]:
df['DATE-ADD'] = pd.to_datetime(df['DATE-ADD'])

df['SEASON'] = (df['DATE-ADD'].dt.month - 1) // 3
df['SEASON'] += (df['DATE-ADD'].dt.month == 3)&(df['DATE-ADD'].dt.day>=20)
df['SEASON'] += (df['DATE-ADD'].dt.month == 6)&(df['DATE-ADD'].dt.day>=21)
df['SEASON'] += (df['DATE-ADD'].dt.month == 9)&(df['DATE-ADD'].dt.day>=23)
df['SEASON'] -= 3*((df['DATE-ADD'].dt.month == 12)&(df['DATE-ADD'].dt.day>=21)).astype(int)

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [13]:
season={0:'Winter',1:'Spring',2:'Summer',3:'Autumn'}
df['SEASON'] = df['SEASON'].map(season)

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
df['COVID'] = 0
df['COVID'] += (df['DATE-ADD'].dt.month == 3)&(df['DATE-ADD'].dt.day>=2)
df['COVID'] += (df['DATE-ADD'].dt.month > 3)

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [15]:
covid={0:'Pre-Covid',1:'Post-Covid',2:'Post-Covid'}

df['COVID'] = df['COVID'].map(covid)
df.isnull().sum()

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME      182679
YX_LIBELLE       65071
BIRTH_YEAR           0
TELEX           185202
EMAIL           280975
ADRESS          251936
POSTAL_CODE      71360
CITY             71982
ITEM_CODE            0
CC_LIBELLE          52
CC_LIBELLE_1        52
DESIGNATION       1774
PVTTC                0
QTEFACT              0
PUTTCNET         98926
MLR_REMISE       98926
GTR_LIBELLE     102677
SEASON               0
COVID                0
dtype: int64

In [16]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','COVID','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]

In [17]:
df['BIRTH_YEAR'] = pd.to_datetime(df['BIRTH_YEAR'],errors='coerce')
df.isnull().sum()

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
SEASON               0
COVID                0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME      182679
YX_LIBELLE       65071
BIRTH_YEAR      197678
TELEX           185202
EMAIL           280975
ADRESS          251936
POSTAL_CODE      71360
CITY             71982
ITEM_CODE            0
CC_LIBELLE          52
CC_LIBELLE_1        52
DESIGNATION       1774
PVTTC                0
QTEFACT              0
PUTTCNET         98926
MLR_REMISE       98926
GTR_LIBELLE     102677
dtype: int64

In [18]:
df.BIRTH_YEAR[df.BIRTH_YEAR.dt.year > 2020] = np.nan
df.BIRTH_YEAR[df.BIRTH_YEAR.dt.year < 1920] = np.nan
df.isnull().sum()

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
SEASON               0
COVID                0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME      182679
YX_LIBELLE       65071
BIRTH_YEAR      275858
TELEX           185202
EMAIL           280975
ADRESS          251936
POSTAL_CODE      71360
CITY             71982
ITEM_CODE            0
CC_LIBELLE          52
CC_LIBELLE_1        52
DESIGNATION       1774
PVTTC                0
QTEFACT              0
PUTTCNET         98926
MLR_REMISE       98926
GTR_LIBELLE     102677
dtype: int64

In [19]:
df['BIRTH_YEAR'] = pd.to_datetime(df['BIRTH_YEAR'],errors='coerce')

In [20]:
df['AGE'] = df['DATE-ADD'].dt.year- df['BIRTH_YEAR'].dt.year

In [21]:
df['AGE'].max()

98.0

In [22]:
df['AGE'].min()

0.0

In [23]:
max_AGE=df['AGE'].max()
min_AGE=df['AGE'].min()

In [24]:
cut_age = ['Moins de 25 ans','entre 25 et 30 ans', 'entre 30 et 35 ans','entre 35 et 40 ans','entre 40 et 50 ans','Plus de 50 ans']
cut_bins =[min_AGE, 25, 30, 35,40,50, max_AGE]
df['AGE_SEGMENT'] = pd.cut(df['AGE'], bins=cut_bins, labels = cut_age)

In [25]:
df['AGE_SEGMENT'].value_counts()

entre 40 et 50 ans    31003
entre 35 et 40 ans    17760
Plus de 50 ans        14760
entre 30 et 35 ans    10674
entre 25 et 30 ans     6127
Moins de 25 ans        2840
Name: AGE_SEGMENT, dtype: int64

In [26]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','COVID','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','AGE_SEGMENT','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]

In [27]:
df['CONFINEMENT'] = 0
df['CONFINEMENT'] += (df['DATE-ADD'].dt.month == 3)&(df['DATE-ADD'].dt.day>=22)
df['CONFINEMENT'] += (df['DATE-ADD'].dt.month == 4)
df['CONFINEMENT'] += (df['DATE-ADD'].dt.month == 5)&(df['DATE-ADD'].dt.day<4)
df['CONFINEMENT'] += (df['DATE-ADD'].dt.month == 5)&(df['DATE-ADD'].dt.day>=4)
df['CONFINEMENT'] += (df['DATE-ADD'].dt.month > 5)

In [28]:
confinement={0:'NO',1:'YES',2:'YES',3:'YES',4:'NO',5:'NO'}

df['CONFINEMENT'] = df['CONFINEMENT'].map(confinement)
df.isnull().sum()

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
SEASON               0
COVID                0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME      182679
YX_LIBELLE       65071
BIRTH_YEAR      275858
AGE             275858
AGE_SEGMENT     275860
TELEX           185202
EMAIL           280975
ADRESS          251936
POSTAL_CODE      71360
CITY             71982
ITEM_CODE            0
CC_LIBELLE          52
CC_LIBELLE_1        52
DESIGNATION       1774
PVTTC                0
QTEFACT              0
PUTTCNET         98926
MLR_REMISE       98926
GTR_LIBELLE     102677
CONFINEMENT          0
dtype: int64

In [29]:
df['P_MONTH']=0
df['P_MONTH']+=(df['DATE-ADD'].dt.day>10)
df['P_MONTH']+=(df['DATE-ADD'].dt.day>20)
df['P_MONTH']=df['P_MONTH'].astype(int)

In [30]:
month={0:'Start_of_Month',1:'Middle_of_Month',2:'End_of_Month'}
df['P_MONTH'] = df['P_MONTH'].map(month)

In [31]:
from datetime import date
import calendar


df['P_WEEK']=df['DATE-ADD'].dt.strftime('%A')
week={'Monday':'Start_of_Week','Tuesday':'Start_of_Week','Wednesday':'Mid_Week','Thursday':'Mid_Week','Friday':'Mid_Week','Saturday':'Week_End','Sunday':'Week_end'}
df['P_WEEK'] = df['P_WEEK'].map(week)

In [32]:
df['CURFEW'] = 0
df['CURFEW'] += (df['DATE-ADD'].dt.month == 3)&(df['DATE-ADD'].dt.day>=18)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 4)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 5)&(df['DATE-ADD'].dt.day<13)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 5)&(df['DATE-ADD'].dt.day>=13)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 6)&(df['DATE-ADD'].dt.day<8)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 6)&(df['DATE-ADD'].dt.day>=8)
df['CURFEW'] += (df['DATE-ADD'].dt.month > 6)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 10)&(df['DATE-ADD'].dt.day<8)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 10)&(df['DATE-ADD'].dt.day>=8)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 10)&(df['DATE-ADD'].dt.day>=8)&(df['P_WEEK']=='Week_end')
df['CURFEW'] += (df['DATE-ADD'].dt.month ==10)&(df['DATE-ADD'].dt.day>=30)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 10)&(df['DATE-ADD'].dt.day>=30)&(df['P_WEEK']=='Week_end')
df['CURFEW'] += (df['DATE-ADD'].dt.month > 10)
df['CURFEW'] += (df['DATE-ADD'].dt.month > 10)&(df['P_WEEK']=='Week_end')

In [33]:
curfew={0:'NO',1:'de 18h à 6h',2:'de 18h à 6h',3:'de 18h à 6h',4:'de 23h à 5h',5:'de 23h à 5h',6:'NO',7:'NO',8:'NO',9:'de 21h à 5h',10:'de 19h à 5h',11:'de 20h à 5h',12:'de 19h à 5h',13:'de 20h à 5h',14:'de 19h à 5h'}

df['CURFEW'] = df['CURFEW'].map(curfew)
df.isnull().sum()

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
SEASON               0
COVID                0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME      182679
YX_LIBELLE       65071
BIRTH_YEAR      275858
AGE             275858
AGE_SEGMENT     275860
TELEX           185202
EMAIL           280975
ADRESS          251936
POSTAL_CODE      71360
CITY             71982
ITEM_CODE            0
CC_LIBELLE          52
CC_LIBELLE_1        52
DESIGNATION       1774
PVTTC                0
QTEFACT              0
PUTTCNET         98926
MLR_REMISE       98926
GTR_LIBELLE     102677
CONFINEMENT          0
P_MONTH              0
P_WEEK               0
CURFEW               0
dtype: int64

In [34]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','P_MONTH','P_WEEK','COVID','CONFINEMENT','CURFEW','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]

In [35]:
df['QTEFACT'].value_counts()

 1.0     347067
-1.0      11262
 2.0        316
 3.0        137
 4.0         64
 10.0        51
 5.0         43
 6.0         21
 7.0         20
 8.0         16
 9.0          7
 11.0         6
 12.0         3
 16.0         2
-2.0          2
 15.0         2
 31.0         2
 80.0         1
 17.0         1
 0.0          1
Name: QTEFACT, dtype: int64

In [36]:
df = df[df.QTEFACT != 0.0]
df

,ID_ORDER,DATE-ADD,TIME-ADD,SEASON,P_MONTH,P_WEEK,COVID,CONFINEMENT,CURFEW,LOCATION,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,800165848,2020-01-01,2020-01-01 18:30:31,Winter,Start_of_Month,Mid_Week,Pre-Covid,NO,NO,Lafayette,...,TUNIS,4BZ053SCGS20H,BLUE ISLAND,BLOUSON,NOIR,249.0,1.0,NaN,NaN,NaN
1,800165832,2020-01-01,2020-01-01 14:40:21,Winter,Start_of_Month,Mid_Week,Pre-Covid,NO,NO,Lafayette,...,TUNIS,6BTS399CPRF19H,SASIO FEMME,BOOTS,NOIR,198.0,1.0,NaN,NaN,NaN
2,800165836,2020-01-01,2020-01-01 15:35:49,Winter,Start_of_Month,Mid_Week,Pre-Covid,NO,NO,Lafayette,...,TUNIS,4PAJ00H111488F20H,BLUE ISLAND,PANTALON,JEAN DELAVE,139.0,1.0,NaN,NaN,NaN
3,800165842,2020-01-01,2020-01-01 16:46:52,Winter,Start_of_Month,Mid_Week,Pre-Covid,NO,NO,Lafayette,...,TUNIS,13PAJ00H111475C20H,ISLD,PANTALON,JEAN DELAVE,109.0,1.0,NaN,NaN,NaN
4,800165840,2020-01-01,2020-01-01 16:36:19,Winter,Start_of_Month,Mid_Week,Pre-Covid,NO,NO,Lafayette,...,TUNIS,31PA01F031245F19H,STUDIO,PANTALON,NOIR,139.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359445,65047834,2020-12-31,2020-12-31 14:51:38,Winter,End_of_Month,Mid_Week,Post-Covid,YES,de 18h à 6h,Blue Island Manar,...,BEN AROUS,4PA01H111503F20H,BLUE ISLAND,PANTALON,NOIR,119.0,1.0,0.0,100.0,2=-100% sur le moins chers
359446,65047822,2020-12-31,2020-12-31 12:45:53,Winter,End_of_Month,Mid_Week,Post-Covid,YES,de 18h à 6h,Blue Island Manar,...,NaN,4PA00H111493F20H,BLUE ISLAND,PANTALON,BLEU ANTRACITE,119.0,1.0,0.0,100.0,2=-100% sur le moins chers
359447,65047837,2020-12-31,2020-12-31 15:05:23,Winter,End_of_Month,Mid_Week,Post-Covid,YES,de 18h à 6h,Blue Island Manar,...,NABEUL,4PUBB18BBC21H,BLUE ISLAND,PULL,MOUTARDE,109.0,1.0,0.0,100.0,2=-100% sur le moins chers
359448,65047817,2020-12-31,2020-12-31 10:12:40,Winter,End_of_Month,Mid_Week,Post-Covid,YES,de 18h à 6h,Blue Island Manar,...,NaN,4ESPBKT04MKB20E,BLUE ISLAND,ESPADRILLE,NOIR,229.0,1.0,0.0,100.0,2=-100% sur le moins chers
359449,65047843,2020-12-31,2020-12-31 15:55:34,Winter,End_of_Month,Mid_Week,Post-Covid,YES,de 18h à 6h,Blue Island Manar,...,TUNISÂ,17PAJ00H111552F20E,ISLAND CLUB,PANTALON,JEAN DELAVE,149.0,1.0,0.0,100.0,2=-100% sur le moins chers

In [37]:
df['QTEFACT']=df['QTEFACT'].astype(float)

In [38]:
df['TOTAL_QUANTITY'] = df['QTEFACT'].groupby(df['ID_ORDER']).transform('sum')

In [39]:
max_QTE=df['TOTAL_QUANTITY'].max()
min_QTE=df['TOTAL_QUANTITY'].min()

In [40]:
cut_qte = ['1 pièce', "2 pièces", 'Entre 3 et 5 Pièces', 'Entre 6 et 10 Pièces', 'Plus que 10 Pièces']
cut_bins =[0.9,1.5, 2, 5, 10, max_QTE ]
df['TOTAL_QUANTITY_SEGMENTS'] = pd.cut(df['TOTAL_QUANTITY'], bins=cut_bins, labels = cut_qte)

In [41]:
df['TOTAL_QUANTITY_SEGMENTS'].value_counts()

2 pièces                124414
Entre 3 et 5 Pièces     106777
1 pièce                  57411
Entre 6 et 10 Pièces     37033
Plus que 10 Pièces       15566
Name: TOTAL_QUANTITY_SEGMENTS, dtype: int64

In [42]:
df['TOTAL_QUANTITY'].value_counts()

 2.0      124414
 3.0       62544
 1.0       57411
 4.0       31679
 0.0       16755
 6.0       16217
 5.0       12554
 8.0        7204
 7.0        5433
 10.0       4129
 9.0        4050
 12.0       3320
 11.0       1846
 14.0       1460
 15.0       1144
 13.0       1036
 16.0       1035
 18.0        878
-1.0         854
 20.0        659
 17.0        421
 22.0        382
 21.0        330
 24.0        314
 19.0        304
 30.0        240
 27.0        236
 32.0        217
 26.0        214
 28.0        190
 23.0        138
-2.0         132
 34.0        128
 29.0        127
 60.0        120
 25.0        112
 36.0        108
 37.0         74
 35.0         70
 40.0         66
 59.0         59
 50.0         50
 48.0         48
 43.0         43
-5.0          40
 38.0         38
 44.0         38
-3.0          35
 33.0         33
 31.0         31
 39.0         28
 72.0         16
 100.0        10
-4.0           6
 62.0          2
 80.0          1
Name: TOTAL_QUANTITY, dtype: int64

In [43]:
df2= pd.read_csv(r'C:\Users\sofi\Downloads\train_code_postal.csv')
df2 = df2.rename(columns={'code postal': 'POST_CODE'})
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 969 entries, 0 to 968
Data columns (total 5 columns):
POST_CODE       969 non-null object
Delegation      969 non-null object
poverty rate    969 non-null float64
zone            969 non-null object
orientation     969 non-null object
dtypes: float64(1), object(4)
memory usage: 38.0+ KB

In [44]:
hour=df['TIME-ADD'].dt.hour

In [45]:
# Create the dictionary for Hour 

H = {0:'Early_morning', 1:'Early_morning', 2:'Early_morning', 3:'Early_morning',4:'Early_morning',5:'Early_morning',6:'Early_morning',7:'Early_morning',8:'Early_morning',9:'Late_morning',10:'Late_morning',11:'Late_morning',12:'Early_afternoon',13:'Early_afternoon',14:'Early_afternoon',15:'Late_afternoon',16:'Late_afternoon',17:'Late_afternoon',18:'Evening',19:'Evening',20:'Evening',21:'Night',22:'Night',23:'Night'}
# Use the dictionary to map the 'Hour'
df['HOUR'] = hour.map(H)
#display the first 5 lines

In [46]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','HOUR','SEASON','P_MONTH','P_WEEK','COVID','CONFINEMENT','CURFEW','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE','TOTAL_QUANTITY']]

In [47]:
new_row2070 = {'POST_CODE':'2070', 'Delegation':'LA MARSA', 'poverty rate':2.2, 'zone':'urbaine','orientation':'nord-est'}
df2 = df2.append(new_row2070, ignore_index=True)

In [48]:
df['POSTAL_CODE']=df['POSTAL_CODE'].apply(str)
df2['POST_CODE']=df2['POST_CODE'].apply(str)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 5 columns):
POST_CODE       970 non-null object
Delegation      970 non-null object
poverty rate    970 non-null float64
zone            970 non-null object
orientation     970 non-null object
dtypes: float64(1), object(4)
memory usage: 38.0+ KB

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [49]:
DF10=pd.DataFrame()
DF10['codep']=df2['POST_CODE']

In [50]:
def tunis(code,train):
 try:
    if str(code)[:2] == '20':
        return 'Grand-Tunis'
    elif str(code)[:2] == '10':
        return 'Grand-Tunis'
    elif str(code)[:2] == '11':
        return 'Grand-Tunis'
    else :
        return str(train[train['POST_CODE']== str(code)]['orientation'].values[0])
 except Exception :
    print (str(code))

In [51]:
DF10['ORIENTATION']=DF10.apply(lambda x: tunis(x.codep,df2), axis=1)

In [52]:
def get_region(code, train):
  try:
    if str(code) in str(train['codep'].unique()):
        return str(train[train['codep']== str(code)]['ORIENTATION'].values[0])
  except Exception :
    print (str(code))

In [53]:
df['region'] = df.apply(lambda x: get_region(x.POSTAL_CODE, DF10), axis=1)

24
710
710
710
24

In [54]:
def get_area(code, train):
  try:
    if str(code) in str(train['POST_CODE'].unique()):
        return str(train[train['POST_CODE']== str(code)]['zone'].values[0])
  except Exception :
    print (str(code))

In [55]:
df['area'] = df.apply(lambda x: get_area(x.POSTAL_CODE, df2), axis=1)

24
710
710
710
24

In [56]:
df = df.rename(columns={'region': 'REGION'})
df = df.rename(columns={'area': 'AREA'})

In [57]:
cut_class = ['A', 'B', 'C+','C-', 'D', 'E']
cut_bins =[0, 2, 8, 18, 26, 42, 55]
df2['class'] = pd.cut(df2['poverty rate'], bins=cut_bins, labels = cut_class)

In [58]:
def get_class22(code, train):
  try:
    if str(code) in str(train['POST_CODE'].unique()):
      return str(train[train['POST_CODE']== str(code)]['class'].values[0])
  except Exception :
    print (str(code))

In [59]:
df['CLASS'] = df.apply(lambda x: get_class22(x.POSTAL_CODE, df2), axis=1)

24
710
710
710
24

In [60]:
df.isnull().sum()

ID_ORDER               0
DATE-ADD               0
TIME-ADD               0
HOUR                   0
SEASON                 0
P_MONTH                0
P_WEEK                 0
COVID                  0
CONFINEMENT            0
CURFEW                 0
LOCATION               0
ID_CUSTOMER            0
LAST_NAME              0
FIRST_NAME        182679
YX_LIBELLE         65071
BIRTH_YEAR        275857
AGE               275857
TELEX             185202
EMAIL             280974
ADRESS            251935
POSTAL_CODE            0
CITY               71981
ITEM_CODE              0
CC_LIBELLE            52
CC_LIBELLE_1          52
DESIGNATION         1774
PVTTC                  0
QTEFACT                0
PUTTCNET           98925
MLR_REMISE         98925
GTR_LIBELLE       102676
TOTAL_QUANTITY         0
REGION             73638
AREA               73638
CLASS              73638
dtype: int64

In [61]:
df = df.rename(columns={'BIRTH_YEAR': 'BIRTHDAY'})
df = df.rename(columns={'ITEM_CODE': 'PRODUCT_ID'})
df = df.rename(columns={'CC_LIBELLE_1': 'PRODUCT_NAME'})
df = df.rename(columns={'CC_LIBELLE': 'LABEL'})
df = df.rename(columns={'DESIGNATION': 'COLOR'})
df = df.rename(columns={'PVTTC': 'PRODUCT_PRICE'})
df = df.rename(columns={'PUTTCNET': 'PRODUCT_PRICE_AFTER_REDUCTION'})
df = df.rename(columns={'QTEFACT': 'PRODUCT_QUANTITY'})
df = df.rename(columns={'MLR_REMISE': 'REDUCTION_PERCENT'})
df = df.rename(columns={'GTR_LIBELLE': 'REDUCTION_TYPE'})
df = df.rename(columns={'YX_LIBELLE': 'CUSTOMER_DESCRIPTION'})

In [62]:
data= pd.read_csv(r'C:\Users\sofi\Downloads\train_gender.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 5 columns):
name        1989 non-null object
gender 1    1989 non-null int64
gender 2    1989 non-null int64
score 1     1989 non-null float64
score 2     1989 non-null float64
dtypes: float64(2), int64(2), object(1)
memory usage: 77.8+ KB

In [63]:
df['REDUCTION_PERCENT'] = df['REDUCTION_PERCENT'].replace(np.nan,0)

In [64]:
max_red=df['REDUCTION_PERCENT'].max()
min_red=df['REDUCTION_PERCENT'].min()

In [65]:
min_red

-233.3333

In [66]:
max_red

100.0

In [67]:
cut_qte = ['Sans remise', "Inférieur à 30%", 'de 30 à 40%', 'de 40 à 50%','Plus que 50%' ]
cut_bins =[-0.000000001,0.000000001, 30, 40, 50, max_red ]
df['REDUCTION_PERCENT_SEGMENTS'] = pd.cut(df['REDUCTION_PERCENT'], bins=cut_bins, labels = cut_qte)

In [68]:
df.isnull().sum()

ID_ORDER                              0
DATE-ADD                              0
TIME-ADD                              0
HOUR                                  0
SEASON                                0
P_MONTH                               0
P_WEEK                                0
COVID                                 0
CONFINEMENT                           0
CURFEW                                0
LOCATION                              0
ID_CUSTOMER                           0
LAST_NAME                             0
FIRST_NAME                       182679
CUSTOMER_DESCRIPTION              65071
BIRTHDAY                         275857
AGE                              275857
TELEX                            185202
EMAIL                            280974
ADRESS                           251935
POSTAL_CODE                           0
CITY                              71981
PRODUCT_ID                            0
LABEL                                52
PRODUCT_NAME                         52
COLOR                              1774
PRODUCT_PRICE                         0
PRODUCT_QUANTITY                      0
PRODUCT_PRICE_AFTER_REDUCTION     98925
REDUCTION_PERCENT                     0
REDUCTION_TYPE                   102676
TOTAL_QUANTITY                        0
REGION                            73638
AREA                              73638
CLASS                             73638
REDUCTION_PERCENT_SEGMENTS          376
dtype: int64

In [69]:
df['REDUCTION_PERCENT_SEGMENTS'].value_counts()

Sans remise        98976
Plus que 50%       93921
Inférieur à 30%    82069
de 40 à 50%        42546
de 30 à 40%        41135
Name: REDUCTION_PERCENT_SEGMENTS, dtype: int64

In [70]:
df['TOTAL_BASKET']=df['PRODUCT_PRICE_AFTER_REDUCTION'].astype(float)*df['PRODUCT_QUANTITY']

In [71]:
df['TOTAL_BASKET'][df['PRODUCT_PRICE_AFTER_REDUCTION'].isna()]=df['PRODUCT_PRICE']*df['PRODUCT_QUANTITY']

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [72]:
df.isnull().sum()

ID_ORDER                              0
DATE-ADD                              0
TIME-ADD                              0
HOUR                                  0
SEASON                                0
P_MONTH                               0
P_WEEK                                0
COVID                                 0
CONFINEMENT                           0
CURFEW                                0
LOCATION                              0
ID_CUSTOMER                           0
LAST_NAME                             0
FIRST_NAME                       182679
CUSTOMER_DESCRIPTION              65071
BIRTHDAY                         275857
AGE                              275857
TELEX                            185202
EMAIL                            280974
ADRESS                           251935
POSTAL_CODE                           0
CITY                              71981
PRODUCT_ID                            0
LABEL                                52
PRODUCT_NAME                         52
COLOR                              1774
PRODUCT_PRICE                         0
PRODUCT_QUANTITY                      0
PRODUCT_PRICE_AFTER_REDUCTION     98925
REDUCTION_PERCENT                     0
REDUCTION_TYPE                   102676
TOTAL_QUANTITY                        0
REGION                            73638
AREA                              73638
CLASS                             73638
REDUCTION_PERCENT_SEGMENTS          376
TOTAL_BASKET                          0
dtype: int64

In [73]:
df['TOTAL_TICKET']=df['TOTAL_BASKET'].groupby(df['ID_ORDER']).transform('sum')

In [74]:
df.isnull().sum()

ID_ORDER                              0
DATE-ADD                              0
TIME-ADD                              0
HOUR                                  0
SEASON                                0
P_MONTH                               0
P_WEEK                                0
COVID                                 0
CONFINEMENT                           0
CURFEW                                0
LOCATION                              0
ID_CUSTOMER                           0
LAST_NAME                             0
FIRST_NAME                       182679
CUSTOMER_DESCRIPTION              65071
BIRTHDAY                         275857
AGE                              275857
TELEX                            185202
EMAIL                            280974
ADRESS                           251935
POSTAL_CODE                           0
CITY                              71981
PRODUCT_ID                            0
LABEL                                52
PRODUCT_NAME                         52
COLOR                              1774
PRODUCT_PRICE                         0
PRODUCT_QUANTITY                      0
PRODUCT_PRICE_AFTER_REDUCTION     98925
REDUCTION_PERCENT                     0
REDUCTION_TYPE                   102676
TOTAL_QUANTITY                        0
REGION                            73638
AREA                              73638
CLASS                             73638
REDUCTION_PERCENT_SEGMENTS          376
TOTAL_BASKET                          0
TOTAL_TICKET                          0
dtype: int64

In [75]:
max_v=df['TOTAL_TICKET'].max()
min_v=df['TOTAL_TICKET'].min()

In [76]:
cut_ticket = ['Inférieur à 100 DT', 'Entre 100 et 200 DT', 'Entre 200 et 300 DT','Supérieur à 300 DT']
cut_bins =[min_v, 100,200,300,max_v ]
df['TICKET_VALUE'] = pd.cut(df['TOTAL_TICKET'], bins=cut_bins, labels = cut_ticket)

In [77]:
df['TICKET_VALUE'].value_counts()

Inférieur à 100 DT     148831
Entre 100 et 200 DT    114514
Entre 200 et 300 DT     49837
Supérieur à 300 DT      45838
Name: TICKET_VALUE, dtype: int64

In [78]:
df_g= pd.read_csv(r'C:\Users\sofi\Downloads\train_gender.csv')
df_g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 5 columns):
name        1989 non-null object
gender 1    1989 non-null int64
gender 2    1989 non-null int64
score 1     1989 non-null float64
score 2     1989 non-null float64
dtypes: float64(2), int64(2), object(1)
memory usage: 77.8+ KB

In [79]:
def word2vec(word):
    # Count the number of characters in each word.
    count_characters = Counter(word)
    # Gets the set of characters and calculates the "length" of the vector.
    set_characters = set(count_characters)
    length = sqrt(sum(c*c for c in count_characters.values()))
    return count_characters, set_characters, length, word

In [80]:
def cosine_similarity(vector1, vector2, ndigits):
    # Get the common characters between the two character sets
    common_characters = vector1[1].intersection(vector2[1])
    # Sum of the product of each intersection character.
    product_summation = sum(vector1[0][character] * vector2[0][character] for character in common_characters)
    # Gets the length of each vector from the word2vec output.
    length = vector1[2] * vector2[2]
    # Calculates cosine similarity and rounds the value to ndigits decimal places.
    if length == 0:
        # Set value to 0 if word is empty.
        similarity = 0
    else:
        similarity = round(product_summation/length, ndigits)
    return similarity

In [81]:
vector_list = [word2vec(str(i)) for i in df_g['name'].unique()]

In [82]:
def find_similar(vector_list,request_word,threshold):
    # Initiate an empty list to store results.
    results_list = []
    # Two loops to compare each vector with another vector only once.
    vector2= word2vec(str(request_word))
    max_similarity = 0 
    similar_word = None
    for i in range(len(vector_list)):
        vector1 = vector_list[i]
        # Calculate cosine similarity
        similarity_score = cosine_similarity(vector1, vector2, 3)
        # Append to results list if similarity score is between 1 and the threshold.
        # Note that scores of 1 can be ignored here if we want to exclude people with the same name.
        if similarity_score> threshold :
            if 1 >= similarity_score>=  max_similarity:
                max_similarity = similarity_score
                similar_word = vector1
    if max_similarity>0 :
        return similar_word[3], max_similarity
    return None,0

In [83]:
#generating genders from firstnames and lastnames

def get_gender(firstname,lastname,train):
    similar_firstname , similarity_score_firstname = find_similar(vector_list,firstname,0.5)
    similar_lastname , similarity_score_lastname = find_similar(vector_list,lastname,0.5)
    if lastname =='CLIENT de PASSAGE' :
        return None
    if similarity_score_firstname > 0 :
        
        gender_firstname=str(train[train['name']== str(similar_firstname)]["gender 1"].values[0])
        if similarity_score_lastname> 0 :
            
            gender_lastname= str(train[train['name']== str(similar_lastname)]["gender 1"].values[0])
            if gender_firstname!=gender_lastname : 
                if similarity_score_firstname>= similarity_score_lastname :
                    return gender_firstname
                else :
                    return gender_lastname
            else:
                return gender_firstname
        elif similarity_score_lastname> 0:
            gender_lastname= str(train[train['name']== str(similar_lastname)]["gender 1"].values[0])
            return gender_lastname

In [84]:
#defining the scores of each name
def get_score(firstname,lastname, train):
  try:
    similar_firstname , similarity_score_firstname = find_similar(vector_list,firstname,0.5)
    similar_lastname , similarity_score_lastname = find_similar(vector_list,lastname,0.5)
    if lastname =='CLIENT de PASSAGE' :
        return 0
    if similarity_score_firstname > 0 :
      if similarity_score_lastname> 0 :
        return max(similarity_score_firstname,similarity_score_lastname)
    elif similarity_score_lastname> 0:
      return similarity_score_lastname
    else :
      return 0.5
  except Exception as e :
    print (e)

In [85]:
df["FIRST_NAME"]=df["FIRST_NAME"].apply(str)
df["LAST_NAME"]=df["LAST_NAME"].apply(str)

In [86]:
df = df.rename(columns={'FIRST_NAME': 'firstname'})
df = df.rename(columns={'LAST_NAME': 'lastname'})

In [87]:
df['gender'] = df.apply(lambda x: get_gender(x.firstname, x.lastname,df_g), axis=1)
df["score"]=df.apply( lambda x: get_score(x.firstname, x.lastname,df_g), axis=1)

In [88]:
df['gender'] = df['gender'].replace(0,'femme')

In [89]:
df['gender'] = df['gender'].replace(1,'homme')

In [90]:
df['gender'].value_counts()

0    100894
1     75146
Name: gender, dtype: int64

In [91]:
df.isnull().sum()

ID_ORDER                              0
DATE-ADD                              0
TIME-ADD                              0
HOUR                                  0
SEASON                                0
P_MONTH                               0
P_WEEK                                0
COVID                                 0
CONFINEMENT                           0
CURFEW                                0
LOCATION                              0
ID_CUSTOMER                           0
lastname                              0
firstname                             0
CUSTOMER_DESCRIPTION              65071
BIRTHDAY                         275857
AGE                              275857
TELEX                            185202
EMAIL                            280974
ADRESS                           251935
POSTAL_CODE                           0
CITY                              71981
PRODUCT_ID                            0
LABEL                                52
PRODUCT_NAME                         52
COLOR                              1774
PRODUCT_PRICE                         0
PRODUCT_QUANTITY                      0
PRODUCT_PRICE_AFTER_REDUCTION     98925
REDUCTION_PERCENT                     0
REDUCTION_TYPE                   102676
TOTAL_QUANTITY                        0
REGION                            73638
AREA                              73638
CLASS                             73638
REDUCTION_PERCENT_SEGMENTS          376
TOTAL_BASKET                          0
TOTAL_TICKET                          0
TICKET_VALUE                          3
gender                           182983
score                                18
dtype: int64

In [92]:
df['PRODUCT_QUANTITY'].value_counts()

 1.0     347067
-1.0      11262
 2.0        316
 3.0        137
 4.0         64
 10.0        51
 5.0         43
 6.0         21
 7.0         20
 8.0         16
 9.0          7
 11.0         6
 12.0         3
-2.0          2
 31.0         2
 15.0         2
 16.0         2
 17.0         1
 80.0         1
Name: PRODUCT_QUANTITY, dtype: int64

In [93]:
df.to_excel(r'C:\Users\sofi\Desktop\2021.xlsx', index = False)