In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats as st
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter
from scipy.stats import chi2_contingency
from collections import Counter
from math import sqrt

In [2]:
df = pd.read_csv(r'C:\Users\sofi\Downloads\wetransfer-3ab4ca\2019.csv',sep=';', encoding = 'ISO-8859-1',
                     names=['ID_ORDER', 'DATE-ADD','TIME-ADD','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE'],
                     dtype={'ID_ORDER':int,'DATE-ADD':object,'TIME-ADD':object,'LOCATION':int,'ID_CUSTOMER':object,'LAST_NAME':object,'FIRST_NAME':object,'YX_LIBELLE':object,'BIRTH_YEAR':object,'TELEX':object,'EMAIL':object,'ADRESS':object,'POSTAL_CODE':object,'CITY':object,'ITEM_CODE':object,'CC_LIBELLE':object,'CC_LIBELLE_1':object})

df

C:\Users\sofi\Anacondaa\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,800155370,2019-01-01 00:00:00.000,2019-01-01 14:12:00.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PA00H111364F19H,BLUE ISLAND,PANTALON,BLEU,89.9000,1,NaN,NaN,NaN
1,800155372,2019-01-01 00:00:00.000,2019-01-01 16:20:03.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PA00H111364F19H,BLUE ISLAND,PANTALON,BLEU,89.9000,1,NaN,NaN,NaN
2,800155367,2019-01-01 00:00:00.000,2019-01-01 14:01:35.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4BZSC745SC19H,BLUE ISLAND,BLOUSON,BLEU,189.9000,1,NaN,NaN,NaN
3,800155369,2019-01-01 00:00:00.000,2019-01-01 14:07:08.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PA00H111358C19H,BLUE ISLAND,PANTALON,BRUN,89.9000,1,NaN,NaN,NaN
4,800155368,2019-01-01 00:00:00.000,2019-01-01 14:06:46.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4BZ0113311F19H,BLUE ISLAND,BLOUSON,NOIR,149.0000,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471576,800165808,2019-12-31 00:00:00.000,2019-12-31 14:12:20.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,31MA00F01129F20A,STUDIO,MANTEAU,NOIR,269.0000,-1,-161.4,40.0,NaN
471577,62241295,2019-12-31 00:00:00.000,2019-12-31 11:44:36.000,62,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PUB013BBC20H,BLUE ISLAND,PULL,NOIR/BORDEAUX,109.0000,-1,0.0,100.0,NaN
471578,62241294,2019-12-31 00:00:00.000,2019-12-31 11:42:59.000,62,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6TN01F051620F20A,SASIO FEMME,TUNIQUE,NOIR/ECRU,129.0000,-1,0.0,100.0,NaN
471579,680067576,2019-12-31 00:00:00.000,2019-12-31 18:14:16.000,68,B0127330,MELYEN,Moez,NaN,1975,58642647,...,MONASTIR,4PUTN10TU20H,BLUE ISLAND,PULL,CARAMEL,109.0000,-1,0.0,100.0,NaN
471580,680067555,2019-12-31 00:00:00.000,2019-12-31 16:15:03.000,68,BC0680670,BOUSSETTA,Foued,PARTENAIRE,1900,55942482,...,MONASTIRÂ,4PUGH9GAT20H,BLUE ISLAND,PULL,MARINE,79.9000,-1,0.0,100.0,NaN

In [3]:
df.isnull().sum()

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME      240233
YX_LIBELLE       91694
BIRTH_YEAR           1
TELEX           243519
EMAIL           364553
ADRESS          319717
POSTAL_CODE      82826
CITY             83458
ITEM_CODE            0
CC_LIBELLE         451
CC_LIBELLE_1       451
DESIGNATION        451
PVTTC                0
QTEFACT              0
PUTTCNET         71059
MLR_REMISE       71088
GTR_LIBELLE      79835
dtype: int64

In [4]:
df['PVTTC'].value_counts()

98.9000          64007
89.9000          59525
79.9000          43944
119.0000         38841
69.9000          32756
                 ...
399.9000             1
ROUX/VERT            1
CAMEL/NOIR           1
GRIS/NOIR            1
MOUTARDE/NOIR        1
Name: PVTTC, Length: 162, dtype: int64

In [5]:
df['PVTTC'] = df['PVTTC'].apply(pd.to_numeric, errors='coerce').fillna(0).astype(float).dropna()

In [6]:
df[df['PVTTC']==0]

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
428,54138740,2019-01-01 00:00:00.000,2019-01-01 14:29:25.000,54,BC0640283,GZARA,Atef,PARTENAIRE,1979,98248859,...,8052,NABEULÂ,4PU2BBBC19H,BLUE ISLAND,PULL,0.0,89.9,1.0,NaN,NaN
1191,54138740,2019-01-01 00:00:00.000,2019-01-01 14:29:25.000,54,BC0640283,GZARA,Atef,PARTENAIRE,1979,98248859,...,8052,NABEULÂ,4PU10BBBC19H,BLUE ISLAND,PULL,0.0,89.9,1.0,0.0,100.0000
2176,270012956,2019-01-03 00:00:00.000,2019-01-03 11:23:26.000,27,B1008529,BDAY,Ahmed,NaN,1982,50531275,...,MSAKEN,VA,NaN,NaN,NaN,0.0,1,NaN,NaN,NaN
3270,270012961,2019-01-05 00:00:00.000,2019-01-05 16:54:48.000,27,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,VA,NaN,NaN,NaN,0.0,1,NaN,NaN,NaN
3274,270012960,2019-01-05 00:00:00.000,2019-01-05 16:54:26.000,27,SB0270390,MAGROUN,Layla,PARTENAIRE,1900,52550735,...,NaN,VA,NaN,NaN,NaN,0.0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466234,15040998,2019-12-29 00:00:00.000,2019-12-29 16:48:46.000,15,SB0272603,CHATTI,Sana,PARTENAIRE,1900,21761151,...,NaN,VA,NaN,NaN,NaN,0.0,1,NaN,NaN,NaN
468536,680067510,2019-12-30 00:00:00.000,2019-12-30 13:30:18.000,68,B1010767,AIDA,Jamoussi,NaN,1974,95366195,...,MONASTIRÂ,VA,NaN,NaN,NaN,0.0,1,NaN,NaN,NaN
469426,16293861,2019-12-30 00:00:00.000,2019-12-30 17:58:19.000,16,BC0622262,TRABELSSI,Khaled,PARTENAIRE,1977,21824184,...,NaN,VA,NaN,NaN,NaN,0.0,1,NaN,NaN,NaN
469554,270015175,2019-12-31 00:00:00.000,2019-12-31 17:02:45.000,27,S2009058,BEN ARBIA,Moufida,NaN,1976,50699126,...,MSAKEN,VA,NaN,NaN,NaN,0.0,1,NaN,NaN,NaN
469559,270015176,2019-12-31 00:00:00.000,2019-12-31 19:52:31.000,27,S2009064,AWATEF,Saadaoui Chatti,NaN,1974,24608275,...,MSAKEN,VA,NaN,NaN,NaN,0.0,1,NaN,NaN,NaN

In [7]:
df = df[df.PVTTC != 0]

In [8]:
df

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,800155370,2019-01-01 00:00:00.000,2019-01-01 14:12:00.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PA00H111364F19H,BLUE ISLAND,PANTALON,BLEU,89.9,1,NaN,NaN,NaN
1,800155372,2019-01-01 00:00:00.000,2019-01-01 16:20:03.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PA00H111364F19H,BLUE ISLAND,PANTALON,BLEU,89.9,1,NaN,NaN,NaN
2,800155367,2019-01-01 00:00:00.000,2019-01-01 14:01:35.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4BZSC745SC19H,BLUE ISLAND,BLOUSON,BLEU,189.9,1,NaN,NaN,NaN
3,800155369,2019-01-01 00:00:00.000,2019-01-01 14:07:08.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PA00H111358C19H,BLUE ISLAND,PANTALON,BRUN,89.9,1,NaN,NaN,NaN
4,800155368,2019-01-01 00:00:00.000,2019-01-01 14:06:46.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4BZ0113311F19H,BLUE ISLAND,BLOUSON,NOIR,149.0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471576,800165808,2019-12-31 00:00:00.000,2019-12-31 14:12:20.000,8,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,31MA00F01129F20A,STUDIO,MANTEAU,NOIR,269.0,-1,-161.4,40.0,NaN
471577,62241295,2019-12-31 00:00:00.000,2019-12-31 11:44:36.000,62,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PUB013BBC20H,BLUE ISLAND,PULL,NOIR/BORDEAUX,109.0,-1,0.0,100.0,NaN
471578,62241294,2019-12-31 00:00:00.000,2019-12-31 11:42:59.000,62,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6TN01F051620F20A,SASIO FEMME,TUNIQUE,NOIR/ECRU,129.0,-1,0.0,100.0,NaN
471579,680067576,2019-12-31 00:00:00.000,2019-12-31 18:14:16.000,68,B0127330,MELYEN,Moez,NaN,1975,58642647,...,MONASTIR,4PUTN10TU20H,BLUE ISLAND,PULL,CARAMEL,109.0,-1,0.0,100.0,NaN
471580,680067555,2019-12-31 00:00:00.000,2019-12-31 16:15:03.000,68,BC0680670,BOUSSETTA,Foued,PARTENAIRE,1900,55942482,...,MONASTIRÂ,4PUGH9GAT20H,BLUE ISLAND,PULL,MARINE,79.9,-1,0.0,100.0,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 470958 entries, 0 to 471580
Data columns (total 23 columns):
ID_ORDER        470958 non-null int32
DATE-ADD        470958 non-null object
TIME-ADD        470958 non-null object
LOCATION        470958 non-null int32
ID_CUSTOMER     470958 non-null object
LAST_NAME       470958 non-null object
FIRST_NAME      230836 non-null object
YX_LIBELLE      379434 non-null object
BIRTH_YEAR      470958 non-null object
TELEX           227558 non-null object
EMAIL           106653 non-null object
ADRESS          151459 non-null object
POSTAL_CODE     388236 non-null object
CITY            387605 non-null object
ITEM_CODE       470958 non-null object
CC_LIBELLE      470830 non-null object
CC_LIBELLE_1    470830 non-null object
DESIGNATION     470830 non-null object
PVTTC           470958 non-null float64
QTEFACT         470958 non-null object
PUTTCNET        400221 non-null float64
MLR_REMISE      400221 non-null float64
GTR_LIBELLE     391475 non-null object
dtypes: float64(3), int32(2), object(18)
memory usage: 82.6+ MB

In [10]:
df.replace({'0000-00-00': np.nan},inplace=True)

C:\Users\sofi\Anacondaa\lib\site-packages\pandas\core\frame.py:4263: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

In [11]:
df.isnull().sum()

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME      240122
YX_LIBELLE       91524
BIRTH_YEAR           0
TELEX           243400
EMAIL           364305
ADRESS          319499
POSTAL_CODE      82722
CITY             83353
ITEM_CODE            0
CC_LIBELLE         128
CC_LIBELLE_1       128
DESIGNATION        128
PVTTC                0
QTEFACT              0
PUTTCNET         70737
MLR_REMISE       70737
GTR_LIBELLE      79483
dtype: int64

In [12]:
#convert DataFrame column to date-time:'GP_DATEPIECE'
df['DATE-ADD'] = pd.to_datetime(df['DATE-ADD'], format = '%Y-%m-%d')
df['DATE-ADD']= pd.to_datetime(df['DATE-ADD'], errors='ignore')

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [13]:
df['TIME-ADD'] = pd.to_datetime(df['TIME-ADD'])

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [14]:
# Create the dictionary for  ETABLISSEMENT
etab = {44:'Djerba',28:'Sasio Geant',31:'Blue Island Carrefour',62:'Central Park',16:'Sousse',8:'Lafayette',130:'Blue Island Palmarium',50:'Sasio Carrefour',24:'Bizerte',40:'Ennasr',56:'Sasio Manzah VI',14:'Blue Island Zephyr',61:'La Soukra',63:'Sasio Menzah V',54:'Nabeul',37:'Sasio Zephyr',134:'Sasio Palmarium',64:'Nabeul',65:'Blue Island Manar',36:'Sasio Manar',25:'Blue Island Djerba',52:'Blue Island Menzah VI',66:'Mehdia',42:'Lac 2',67:'Sfax',68:'Monastir',51:'Blue Island Menzah V',69:'El Kef',35:'Kairouan',15:'Sasio Mseken',27:'Sasio Mseken',60:'Sasio Djerba',18:'Kelibia',41:'Ksar Hellal',74:'Hammamet'}
df['LOCATION'] = df['LOCATION'].map(etab)
#display the first 5 lines
df

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,800155370,2019-01-01,2019-01-01 14:12:00,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PA00H111364F19H,BLUE ISLAND,PANTALON,BLEU,89.9,1,NaN,NaN,NaN
1,800155372,2019-01-01,2019-01-01 16:20:03,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PA00H111364F19H,BLUE ISLAND,PANTALON,BLEU,89.9,1,NaN,NaN,NaN
2,800155367,2019-01-01,2019-01-01 14:01:35,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4BZSC745SC19H,BLUE ISLAND,BLOUSON,BLEU,189.9,1,NaN,NaN,NaN
3,800155369,2019-01-01,2019-01-01 14:07:08,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PA00H111358C19H,BLUE ISLAND,PANTALON,BRUN,89.9,1,NaN,NaN,NaN
4,800155368,2019-01-01,2019-01-01 14:06:46,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4BZ0113311F19H,BLUE ISLAND,BLOUSON,NOIR,149.0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471576,800165808,2019-12-31,2019-12-31 14:12:20,Lafayette,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,31MA00F01129F20A,STUDIO,MANTEAU,NOIR,269.0,-1,-161.4,40.0,NaN
471577,62241295,2019-12-31,2019-12-31 11:44:36,Central Park,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4PUB013BBC20H,BLUE ISLAND,PULL,NOIR/BORDEAUX,109.0,-1,0.0,100.0,NaN
471578,62241294,2019-12-31,2019-12-31 11:42:59,Central Park,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,6TN01F051620F20A,SASIO FEMME,TUNIQUE,NOIR/ECRU,129.0,-1,0.0,100.0,NaN
471579,680067576,2019-12-31,2019-12-31 18:14:16,Monastir,B0127330,MELYEN,Moez,NaN,1975,58642647,...,MONASTIR,4PUTN10TU20H,BLUE ISLAND,PULL,CARAMEL,109.0,-1,0.0,100.0,NaN
471580,680067555,2019-12-31,2019-12-31 16:15:03,Monastir,BC0680670,BOUSSETTA,Foued,PARTENAIRE,1900,55942482,...,MONASTIRÂ,4PUGH9GAT20H,BLUE ISLAND,PULL,MARINE,79.9,-1,0.0,100.0,NaN

In [15]:
df.isnull().sum()

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME      240122
YX_LIBELLE       91524
BIRTH_YEAR           0
TELEX           243400
EMAIL           364305
ADRESS          319499
POSTAL_CODE      82722
CITY             83353
ITEM_CODE            0
CC_LIBELLE         128
CC_LIBELLE_1       128
DESIGNATION        128
PVTTC                0
QTEFACT              0
PUTTCNET         70737
MLR_REMISE       70737
GTR_LIBELLE      79483
dtype: int64

In [16]:
df['DATE-ADD'] = pd.to_datetime(df['DATE-ADD'])

df['SEASON'] = (df['DATE-ADD'].dt.month - 1) // 3
df['SEASON'] += (df['DATE-ADD'].dt.month == 3)&(df['DATE-ADD'].dt.day>=20)
df['SEASON'] += (df['DATE-ADD'].dt.month == 6)&(df['DATE-ADD'].dt.day>=21)
df['SEASON'] += (df['DATE-ADD'].dt.month == 9)&(df['DATE-ADD'].dt.day>=23)
df['SEASON'] -= 3*((df['DATE-ADD'].dt.month == 12)&(df['DATE-ADD'].dt.day>=21)).astype(int)

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [17]:
season={0:'Winter',1:'Spring',2:'Summer',3:'Autumn'}

df['SEASON'] = df['SEASON'].map(season)

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [18]:
df['COVID']='Pre-Covid'
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','COVID','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [19]:
df.isnull().sum()

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
SEASON               0
COVID                0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME      240122
YX_LIBELLE       91524
BIRTH_YEAR           0
TELEX           243400
EMAIL           364305
ADRESS          319499
POSTAL_CODE      82722
CITY             83353
ITEM_CODE            0
CC_LIBELLE         128
CC_LIBELLE_1       128
DESIGNATION        128
PVTTC                0
QTEFACT              0
PUTTCNET         70737
MLR_REMISE       70737
GTR_LIBELLE      79483
dtype: int64

In [20]:
df['BIRTH_YEAR'].value_counts()

0       258321
1900     98962
1980      7030
1979      5105
1976      4900
         ...
49           1
10           1
1075         1
2            1
1908         1
Name: BIRTH_YEAR, Length: 184, dtype: int64

In [21]:
df['BIRTH_YEAR'] = pd.to_datetime(df['BIRTH_YEAR'],errors='coerce')
df.isnull().sum()

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
SEASON               0
COVID                0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME      240122
YX_LIBELLE       91524
BIRTH_YEAR      261458
TELEX           243400
EMAIL           364305
ADRESS          319499
POSTAL_CODE      82722
CITY             83353
ITEM_CODE            0
CC_LIBELLE         128
CC_LIBELLE_1       128
DESIGNATION        128
PVTTC                0
QTEFACT              0
PUTTCNET         70737
MLR_REMISE       70737
GTR_LIBELLE      79483
dtype: int64

In [22]:
df['BIRTH_YEAR'].value_counts()

1900-01-01    98962
1980-01-01     7030
1979-01-01     5105
1976-01-01     4900
1978-01-01     4777
              ...
1915-01-01        2
2010-01-01        1
1908-01-01        1
1935-01-01        1
1914-01-01        1
Name: BIRTH_YEAR, Length: 111, dtype: int64

In [23]:
df.BIRTH_YEAR[df.BIRTH_YEAR.dt.year > 2019] = np.nan
df.BIRTH_YEAR[df.BIRTH_YEAR.dt.year < 1919] = np.nan
df.isnull().sum()

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
SEASON               0
COVID                0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME      240122
YX_LIBELLE       91524
BIRTH_YEAR      360607
TELEX           243400
EMAIL           364305
ADRESS          319499
POSTAL_CODE      82722
CITY             83353
ITEM_CODE            0
CC_LIBELLE         128
CC_LIBELLE_1       128
DESIGNATION        128
PVTTC                0
QTEFACT              0
PUTTCNET         70737
MLR_REMISE       70737
GTR_LIBELLE      79483
dtype: int64

In [24]:
df['BIRTH_YEAR'] = pd.to_datetime(df['BIRTH_YEAR'],errors='coerce')

In [25]:
df['AGE'] = df['DATE-ADD'].dt.year- df['BIRTH_YEAR'].dt.year

In [26]:
df['AGE'].value_counts()

39.0    7030
40.0    5105
43.0    4900
41.0    4777
37.0    4535
        ...
1.0        3
8.0        3
80.0       3
84.0       1
9.0        1
Name: AGE, Length: 88, dtype: int64

In [27]:
df['AGE'].max()

100.0

In [28]:
df['AGE'].min()

1.0

In [29]:
max_AGE=df['AGE'].max()
min_AGE=df['AGE'].min()

In [30]:
cut_age=['Moins de 25 ans','entre 25 et 30 ans','entre 30 et 35 ans','entre 35 et 40 ans','entre 40 et 50 ans','Plus de 50 ans']
cut_bins =[min_AGE, 25, 30, 35,40,50, max_AGE]
df['AGE_SEGMENT'] = pd.cut(df['AGE'], bins=cut_bins, labels = cut_age)

In [31]:
df['AGE_SEGMENT'].value_counts()

entre 40 et 50 ans    38845
entre 35 et 40 ans    25071
Plus de 50 ans        17368
entre 30 et 35 ans    15806
entre 25 et 30 ans     8820
Moins de 25 ans        4438
Name: AGE_SEGMENT, dtype: int64

In [32]:
df['CONFINEMENT']='NON'
df['CURFEW']='NON'
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','COVID','CONFINEMENT','CURFEW','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]

In [33]:
df['P_MONTH']=0
df['P_MONTH']+=(df['DATE-ADD'].dt.day>10)
df['P_MONTH']+=(df['DATE-ADD'].dt.day>20)
df['P_MONTH']=df['P_MONTH'].astype(int)

In [34]:
month={0:'Start_of_Month',1:'Middle_of_Month',2:'End_of_Month'}
df['P_MONTH'] = df['P_MONTH'].map(month)

In [35]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','P_MONTH','COVID','CONFINEMENT','CURFEW','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]

In [36]:
from datetime import date
import calendar


df['P_WEEK']=df['DATE-ADD'].dt.strftime('%A')
week={'Monday':'Start_of_Week','Tuesday':'Start_of_Week','Wednesday':'Mid_Week','Thursday':'Mid_Week','Friday':'Mid_Week','Saturday':'Week_End','Sunday':'Week_end'}
df['P_WEEK'] = df['P_WEEK'].map(week)

In [37]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','P_MONTH','P_WEEK','COVID','CONFINEMENT','CURFEW','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]

In [38]:
df['QTEFACT'].value_counts()

1.0        426087
1.0000      31845
-1.0        12009
-1.0000       886
2.0            67
3.0            10
5.0            10
4.0             9
9.0             6
0.0             5
6.0             4
-2.0            4
11.0            2
8.0             2
7.0             2
14.0            2
2.0000          2
10.0            2
-3.0            1
12.0            1
18.0            1
13.0            1
Name: QTEFACT, dtype: int64

In [39]:
df['QTEFACT']=df['QTEFACT'].astype(float)

In [40]:
df['TOTAL_QUANTITY'] = df['QTEFACT'].groupby(df['ID_ORDER']).transform('sum')

In [41]:
df['TOTAL_QUANTITY'].value_counts()

 2.0     165677
 1.0      86429
 4.0      57935
 3.0      50575
 6.0      23978
          ...
 70.0        22
-8.0         20
-7.0          9
-5.0          7
-6.0          6
Name: TOTAL_QUANTITY, Length: 63, dtype: int64

In [42]:
max_QTE=df['TOTAL_QUANTITY'].max()
min_QTE=df['TOTAL_QUANTITY'].min()

In [43]:
cut_qte = ['1 pièce', "2 pièces", 'Entre 3 et 5 Pièces', 'Entre 6 et 10 Pièces', 'Plus que 10 Pièces']
cut_bins =[0.9,1.5, 2, 5, 10, max_QTE ]
df['TOTAL_QUANTITY_SEGMENTS'] = pd.cut(df['TOTAL_QUANTITY'], bins=cut_bins, labels = cut_qte)

In [44]:
df['TOTAL_QUANTITY_SEGMENTS'].value_counts()

2 pièces                165677
Entre 3 et 5 Pièces     121465
1 pièce                  86429
Entre 6 et 10 Pièces     54254
Plus que 10 Pièces       23068
Name: TOTAL_QUANTITY_SEGMENTS, dtype: int64

In [45]:
df2= pd.read_csv(r'C:\Users\sofi\Downloads\train_code_postal.csv')
df2 = df2.rename(columns={'code postal': 'POST_CODE'})
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 969 entries, 0 to 968
Data columns (total 5 columns):
POST_CODE       969 non-null object
Delegation      969 non-null object
poverty rate    969 non-null float64
zone            969 non-null object
orientation     969 non-null object
dtypes: float64(1), object(4)
memory usage: 38.0+ KB

In [46]:
hour=df['TIME-ADD'].dt.hour

In [47]:
# Create the dictionary for Hour 

H = {0:'Early_morning', 1:'Early_morning', 2:'Early_morning', 3:'Early_morning',4:'Early_morning',5:'Early_morning',6:'Early_morning',7:'Early_morning',8:'Early_morning',9:'Late_morning',10:'Late_morning',11:'Late_morning',12:'Early_afternoon',13:'Early_afternoon',14:'Early_afternoon',15:'Late_afternoon',16:'Late_afternoon',17:'Late_afternoon',18:'Evening',19:'Evening',20:'Evening',21:'Night',22:'Night',23:'Night'}
# Use the dictionary to map the 'Hour'
df['HOUR'] = hour.map(H)
#display the first 5 lines

In [48]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','HOUR','SEASON','P_MONTH','P_WEEK','COVID','CONFINEMENT','CURFEW','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE','TOTAL_QUANTITY']]

In [49]:
new_row2070 = {'POST_CODE':'2070', 'Delegation':'LA MARSA', 'poverty rate':2.2, 'zone':'urbaine','orientation':'nord-est'}
df2 = df2.append(new_row2070, ignore_index=True)

In [50]:
df['POSTAL_CODE']=df['POSTAL_CODE'].apply(str)
df2['POST_CODE']=df2['POST_CODE'].apply(str)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 5 columns):
POST_CODE       970 non-null object
Delegation      970 non-null object
poverty rate    970 non-null float64
zone            970 non-null object
orientation     970 non-null object
dtypes: float64(1), object(4)
memory usage: 38.0+ KB

In [51]:
DF10=pd.DataFrame()
DF10['codep']=df2['POST_CODE']
DF10

    codep
0    2072
1    1007
2    2023
3    1046
4    1095
..    ...
965  4273
966  4237
967  4232
968  4235
969  2070

[970 rows x 1 columns]

In [52]:
def tunis(code,train):
 try:
    if str(code)[:2] == '20':
        return 'Grand-Tunis'
    elif str(code)[:2] == '10':
        return 'Grand-Tunis'
    elif str(code)[:2] == '11':
        return 'Grand-Tunis'
    else :
        return str(train[train['POST_CODE']== str(code)]['orientation'].values[0])
 except Exception :
    print (str(code))

In [53]:
DF10['ORIENTATION']=DF10.apply(lambda x: tunis(x.codep,df2), axis=1)

In [54]:
def get_region(code, train):
  try:
    if str(code) in str(train['codep'].unique()):
        return str(train[train['codep']== str(code)]['ORIENTATION'].values[0])
  except Exception :
    print (str(code))

In [55]:
df['region'] = df.apply(lambda x: get_region(x.POSTAL_CODE, DF10), axis=1)

710
710
710
710
800
24
24
24
800
0
710

In [56]:
def get_area(code, train):
  try:
    if str(code) in str(train['POST_CODE'].unique()):
        return str(train[train['POST_CODE']== str(code)]['zone'].values[0])
  except Exception :
    print (str(code))

In [57]:
df['area'] = df.apply(lambda x: get_area(x.POSTAL_CODE, df2), axis=1)

710
710
710
710
800
24
24
24
800
0
710

In [58]:
df = df.rename(columns={'region': 'REGION'})
df = df.rename(columns={'area': 'AREA'})

In [59]:
cut_class = ['A', 'B', 'C+','C-', 'D', 'E']
cut_bins =[0, 2, 8, 18, 26, 42, 55]
df2['class'] = pd.cut(df2['poverty rate'], bins=cut_bins, labels = cut_class)
df2

    POST_CODE    Delegation  poverty rate     zone orientation class
0        2072       SEJOUMI          11.5  urbaine    nord-est    C+
1        1007       SEJOUMI          11.5  urbaine    nord-est    C+
2        2023   JEBEL JLOUD           9.5  urbaine    nord-est    C+
3        1046   JEBEL JLOUD           9.5  urbaine    nord-est    C+
4        1095  SIDI HASSINE           9.4  urbaine    nord-est    C+
..        ...           ...           ...      ...         ...   ...
965      4273   KEBILI NORD          12.3  urbaine   sud-ouest    C+
966      4237   KEBILI NORD          12.3  urbaine   sud-ouest    C+
967      4232   KEBILI NORD          12.3  urbaine   sud-ouest    C+
968      4235   KEBILI NORD          12.3  urbaine   sud-ouest    C+
969      2070      LA MARSA           2.2  urbaine    nord-est     B

[970 rows x 6 columns]

In [60]:
def get_class22(code, train):
  try:
    if str(code) in str(train['POST_CODE'].unique()):
      return str(train[train['POST_CODE']== str(code)]['class'].values[0])
  except Exception :
    print (str(code))

In [61]:
df['CLASS'] = df.apply(lambda x: get_class22(x.POSTAL_CODE, df2), axis=1)

710
710
710
710
800
24
24
24
800
0
710

In [62]:
df.isnull().sum()

ID_ORDER               0
DATE-ADD               0
TIME-ADD               0
HOUR                   0
SEASON                 0
P_MONTH                0
P_WEEK                 0
COVID                  0
CONFINEMENT            0
CURFEW                 0
LOCATION               0
ID_CUSTOMER            0
LAST_NAME              0
FIRST_NAME        240122
YX_LIBELLE         91524
BIRTH_YEAR        360607
AGE               360607
TELEX             243400
EMAIL             364305
ADRESS            319499
POSTAL_CODE            0
CITY               83353
ITEM_CODE              0
CC_LIBELLE           128
CC_LIBELLE_1         128
DESIGNATION          128
PVTTC                  0
QTEFACT                0
PUTTCNET           70737
MLR_REMISE         70737
GTR_LIBELLE        79483
TOTAL_QUANTITY         0
REGION             85990
AREA               85990
CLASS              85990
dtype: int64

In [63]:
df = df.rename(columns={'BIRTH_YEAR': 'BIRTHDAY'})
df = df.rename(columns={'ITEM_CODE': 'PRODUCT_ID'})
df = df.rename(columns={'CC_LIBELLE_1': 'PRODUCT_NAME'})
df = df.rename(columns={'CC_LIBELLE': 'LABEL'})
df = df.rename(columns={'DESIGNATION': 'COLOR'})
df = df.rename(columns={'PVTTC': 'PRODUCT_PRICE'})
df = df.rename(columns={'PUTTCNET': 'PRODUCT_PRICE_AFTER_REDUCTION'})
df = df.rename(columns={'QTEFACT': 'PRODUCT_QUANTITY'})
df = df.rename(columns={'MLR_REMISE': 'REDUCTION_PERCENT'})
df = df.rename(columns={'GTR_LIBELLE': 'REDUCTION_TYPE'})
df = df.rename(columns={'YX_LIBELLE': 'CUSTOMER_DESCRIPTION'})

In [64]:
data= pd.read_csv(r'C:\Users\sofi\Downloads\train_gender.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 5 columns):
name        1989 non-null object
gender 1    1989 non-null int64
gender 2    1989 non-null int64
score 1     1989 non-null float64
score 2     1989 non-null float64
dtypes: float64(2), int64(2), object(1)
memory usage: 77.8+ KB

In [65]:
df['REDUCTION_PERCENT'].value_counts()

 20.0000    75827
 40.0000    71882
 30.0000    71102
 70.0000    68375
 50.0000    61662
            ...
-16.4659        1
-10.5820        1
 11.1732        1
 50.6329        1
 30.3101        1
Name: REDUCTION_PERCENT, Length: 1285, dtype: int64

In [66]:
df['REDUCTION_PERCENT'] = df['REDUCTION_PERCENT'].replace(np.nan,0)

In [67]:
df.isnull().sum()

ID_ORDER                              0
DATE-ADD                              0
TIME-ADD                              0
HOUR                                  0
SEASON                                0
P_MONTH                               0
P_WEEK                                0
COVID                                 0
CONFINEMENT                           0
CURFEW                                0
LOCATION                              0
ID_CUSTOMER                           0
LAST_NAME                             0
FIRST_NAME                       240122
CUSTOMER_DESCRIPTION              91524
BIRTHDAY                         360607
AGE                              360607
TELEX                            243400
EMAIL                            364305
ADRESS                           319499
POSTAL_CODE                           0
CITY                              83353
PRODUCT_ID                            0
LABEL                               128
PRODUCT_NAME                        128
COLOR                               128
PRODUCT_PRICE                         0
PRODUCT_QUANTITY                      0
PRODUCT_PRICE_AFTER_REDUCTION     70737
REDUCTION_PERCENT                     0
REDUCTION_TYPE                    79483
TOTAL_QUANTITY                        0
REGION                            85990
AREA                              85990
CLASS                             85990
dtype: int64

In [68]:
max_red=df['REDUCTION_PERCENT'].max()
min_red=df['REDUCTION_PERCENT'].min()

In [69]:
min_red

-235.3468

In [70]:
max_red

100.0

In [71]:
cut_qte = ['Sans remise', "Inférieur à 30%", 'de 30 à 40%', 'de 40 à 50%','Plus que 50%' ]
cut_bins =[-0.000000001,0.000000001, 30, 40, 50, max_red ]
df['REDUCTION_PERCENT_SEGMENTS'] = pd.cut(df['REDUCTION_PERCENT'], bins=cut_bins, labels = cut_qte)

In [72]:
df.isnull().sum()

ID_ORDER                              0
DATE-ADD                              0
TIME-ADD                              0
HOUR                                  0
SEASON                                0
P_MONTH                               0
P_WEEK                                0
COVID                                 0
CONFINEMENT                           0
CURFEW                                0
LOCATION                              0
ID_CUSTOMER                           0
LAST_NAME                             0
FIRST_NAME                       240122
CUSTOMER_DESCRIPTION              91524
BIRTHDAY                         360607
AGE                              360607
TELEX                            243400
EMAIL                            364305
ADRESS                           319499
POSTAL_CODE                           0
CITY                              83353
PRODUCT_ID                            0
LABEL                               128
PRODUCT_NAME                        128
COLOR                               128
PRODUCT_PRICE                         0
PRODUCT_QUANTITY                      0
PRODUCT_PRICE_AFTER_REDUCTION     70737
REDUCTION_PERCENT                     0
REDUCTION_TYPE                    79483
TOTAL_QUANTITY                        0
REGION                            85990
AREA                              85990
CLASS                             85990
REDUCTION_PERCENT_SEGMENTS          223
dtype: int64

In [73]:
df['TOTAL_BASKET']=df['PRODUCT_PRICE_AFTER_REDUCTION'].astype(float)*df['PRODUCT_QUANTITY']

In [74]:
df['TOTAL_BASKET'][df['PRODUCT_PRICE_AFTER_REDUCTION'].isna()]=df['PRODUCT_PRICE']*df['PRODUCT_QUANTITY']

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [75]:
df.isnull().sum()

ID_ORDER                              0
DATE-ADD                              0
TIME-ADD                              0
HOUR                                  0
SEASON                                0
P_MONTH                               0
P_WEEK                                0
COVID                                 0
CONFINEMENT                           0
CURFEW                                0
LOCATION                              0
ID_CUSTOMER                           0
LAST_NAME                             0
FIRST_NAME                       240122
CUSTOMER_DESCRIPTION              91524
BIRTHDAY                         360607
AGE                              360607
TELEX                            243400
EMAIL                            364305
ADRESS                           319499
POSTAL_CODE                           0
CITY                              83353
PRODUCT_ID                            0
LABEL                               128
PRODUCT_NAME                        128
COLOR                               128
PRODUCT_PRICE                         0
PRODUCT_QUANTITY                      0
PRODUCT_PRICE_AFTER_REDUCTION     70737
REDUCTION_PERCENT                     0
REDUCTION_TYPE                    79483
TOTAL_QUANTITY                        0
REGION                            85990
AREA                              85990
CLASS                             85990
REDUCTION_PERCENT_SEGMENTS          223
TOTAL_BASKET                          0
dtype: int64

In [76]:
df['TOTAL_TICKET']=df['TOTAL_BASKET'].groupby(df['ID_ORDER']).transform('sum')

In [77]:
df.isnull().sum()

ID_ORDER                              0
DATE-ADD                              0
TIME-ADD                              0
HOUR                                  0
SEASON                                0
P_MONTH                               0
P_WEEK                                0
COVID                                 0
CONFINEMENT                           0
CURFEW                                0
LOCATION                              0
ID_CUSTOMER                           0
LAST_NAME                             0
FIRST_NAME                       240122
CUSTOMER_DESCRIPTION              91524
BIRTHDAY                         360607
AGE                              360607
TELEX                            243400
EMAIL                            364305
ADRESS                           319499
POSTAL_CODE                           0
CITY                              83353
PRODUCT_ID                            0
LABEL                               128
PRODUCT_NAME                        128
COLOR                               128
PRODUCT_PRICE                         0
PRODUCT_QUANTITY                      0
PRODUCT_PRICE_AFTER_REDUCTION     70737
REDUCTION_PERCENT                     0
REDUCTION_TYPE                    79483
TOTAL_QUANTITY                        0
REGION                            85990
AREA                              85990
CLASS                             85990
REDUCTION_PERCENT_SEGMENTS          223
TOTAL_BASKET                          0
TOTAL_TICKET                          0
dtype: int64

In [78]:
max_v=df['TOTAL_TICKET'].max()
min_v=df['TOTAL_TICKET'].min()

In [79]:
cut_ticket = ['Inférieur à 100 DT', 'Entre 100 et 200 DT', 'Entre 200 et 300 DT','Supérieur à 300 DT']
cut_bins =[min_v, 100,200,300,max_v ]
df['TICKET_VALUE'] = pd.cut(df['TOTAL_TICKET'], bins=cut_bins, labels = cut_ticket)

In [80]:
df_g= pd.read_csv(r'C:\Users\sofi\Downloads\train_gender.csv')
df_g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 5 columns):
name        1989 non-null object
gender 1    1989 non-null int64
gender 2    1989 non-null int64
score 1     1989 non-null float64
score 2     1989 non-null float64
dtypes: float64(2), int64(2), object(1)
memory usage: 77.8+ KB

In [81]:
def word2vec(word):
    # Count the number of characters in each word.
    count_characters = Counter(word)
    # Gets the set of characters and calculates the "length" of the vector.
    set_characters = set(count_characters)
    length = sqrt(sum(c*c for c in count_characters.values()))
    return count_characters, set_characters, length, word

In [82]:
def cosine_similarity(vector1, vector2, ndigits):
    # Get the common characters between the two character sets
    common_characters = vector1[1].intersection(vector2[1])
    # Sum of the product of each intersection character.
    product_summation = sum(vector1[0][character] * vector2[0][character] for character in common_characters)
    # Gets the length of each vector from the word2vec output.
    length = vector1[2] * vector2[2]
    # Calculates cosine similarity and rounds the value to ndigits decimal places.
    if length == 0:
        # Set value to 0 if word is empty.
        similarity = 0
    else:
        similarity = round(product_summation/length, ndigits)
    return similarity

In [83]:
vector_list = [word2vec(str(i)) for i in df_g['name'].unique()]

In [84]:
def find_similar(vector_list,request_word,threshold):
    # Initiate an empty list to store results.
    results_list = []
    # Two loops to compare each vector with another vector only once.
    vector2= word2vec(str(request_word))
    max_similarity = 0 
    similar_word = None
    for i in range(len(vector_list)):
        vector1 = vector_list[i]
        # Calculate cosine similarity
        similarity_score = cosine_similarity(vector1, vector2, 3)
        # Append to results list if similarity score is between 1 and the threshold.
        # Note that scores of 1 can be ignored here if we want to exclude people with the same name.
        if similarity_score> threshold :
            if 1 >= similarity_score>=  max_similarity:
                max_similarity = similarity_score
                similar_word = vector1
    if max_similarity>0 :
        return similar_word[3], max_similarity
    return None,0

In [85]:
#generating genders from firstnames and lastnames

def get_gender(firstname,lastname,train):
    similar_firstname , similarity_score_firstname = find_similar(vector_list,firstname,0.5)
    similar_lastname , similarity_score_lastname = find_similar(vector_list,lastname,0.5)
    if lastname =='CLIENT de PASSAGE' :
        return None
    elif similarity_score_firstname > 0 :
        
        gender_firstname=str(train[train['name']== str(similar_firstname)]["gender 1"].values[0])
        if similarity_score_lastname> 0 :
            
            gender_lastname= str(train[train['name']== str(similar_lastname)]["gender 1"].values[0])
            if gender_firstname!=gender_lastname : 
                if similarity_score_firstname>= similarity_score_lastname :
                    return gender_firstname
                else :
                    return gender_lastname
            else:
                return gender_firstname
    elif similarity_score_lastname> 0:
        gender_lastname= str(train[train['name']== str(similar_lastname)]["gender 1"].values[0])
        return gender_lastname

In [86]:
#defining the scores of each name
def get_score(firstname,lastname, train):
  try:
    similar_firstname , similarity_score_firstname = find_similar(vector_list,firstname,0.5)
    similar_lastname , similarity_score_lastname = find_similar(vector_list,lastname,0.5)
    if lastname =='CLIENT de PASSAGE' :
        return 0
    if similarity_score_firstname > 0 :
      if similarity_score_lastname> 0 :
        return max(similarity_score_firstname,similarity_score_lastname)
    elif similarity_score_lastname> 0:
      return similarity_score_lastname
    else :
      return 0.5
  except Exception as e :
    print (e)

In [87]:
df["FIRST_NAME"]=df["FIRST_NAME"].apply(str)
df["LAST_NAME"]=df["LAST_NAME"].apply(str)

In [88]:
df = df.rename(columns={'FIRST_NAME': 'firstname'})
df = df.rename(columns={'LAST_NAME': 'lastname'})

In [89]:
df['gender'] = df.apply(lambda x: get_gender(x.firstname, x.lastname,df_g), axis=1)
df["score"]=df.apply( lambda x: get_score(x.firstname, x.lastname,df_g), axis=1)

In [90]:
df.isnull().sum()

ID_ORDER                              0
DATE-ADD                              0
TIME-ADD                              0
HOUR                                  0
SEASON                                0
P_MONTH                               0
P_WEEK                                0
COVID                                 0
CONFINEMENT                           0
CURFEW                                0
LOCATION                              0
ID_CUSTOMER                           0
lastname                              0
firstname                             0
CUSTOMER_DESCRIPTION              91524
BIRTHDAY                         360607
AGE                              360607
TELEX                            243400
EMAIL                            364305
ADRESS                           319499
POSTAL_CODE                           0
CITY                              83353
PRODUCT_ID                            0
LABEL                               128
PRODUCT_NAME                        128
COLOR                               128
PRODUCT_PRICE                         0
PRODUCT_QUANTITY                      0
PRODUCT_PRICE_AFTER_REDUCTION     70737
REDUCTION_PERCENT                     0
REDUCTION_TYPE                    79483
TOTAL_QUANTITY                        0
REGION                            85990
AREA                              85990
CLASS                             85990
REDUCTION_PERCENT_SEGMENTS          223
TOTAL_BASKET                          0
TOTAL_TICKET                          0
TICKET_VALUE                          6
gender                           240429
score                                21
dtype: int64

In [91]:
df['gender'].value_counts()

0    136486
1     94043
Name: gender, dtype: int64

In [92]:
df['PRODUCT_QUANTITY'].value_counts()

 1.0     457932
-1.0      12895
 2.0         69
 3.0         10
 5.0         10
 4.0          9
 9.0          6
 0.0          5
 6.0          4
-2.0          4
 7.0          2
 14.0         2
 8.0          2
 10.0         2
 11.0         2
-3.0          1
 12.0         1
 18.0         1
 13.0         1
Name: PRODUCT_QUANTITY, dtype: int64

In [93]:
df=df[df.PRODUCT_QUANTITY!=0.0]

In [94]:
df['PRODUCT_QUANTITY'].value_counts()

 1.0     457932
-1.0      12895
 2.0         69
 3.0         10
 5.0         10
 4.0          9
 9.0          6
 6.0          4
-2.0          4
 7.0          2
 8.0          2
 10.0         2
 14.0         2
 11.0         2
-3.0          1
 13.0         1
 18.0         1
 12.0         1
Name: PRODUCT_QUANTITY, dtype: int64

In [95]:
df

,ID_ORDER,DATE-ADD,TIME-ADD,HOUR,SEASON,P_MONTH,P_WEEK,COVID,CONFINEMENT,CURFEW,...,TOTAL_QUANTITY,REGION,AREA,CLASS,REDUCTION_PERCENT_SEGMENTS,TOTAL_BASKET,TOTAL_TICKET,TICKET_VALUE,gender,score
0,800155370,2019-01-01,2019-01-01 14:12:00,Early_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NON,NON,...,2.0,Grand-Tunis,urbaine,B,Sans remise,89.9,89.9,Inférieur à 100 DT,None,0.0
1,800155372,2019-01-01,2019-01-01 16:20:03,Late_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NON,NON,...,2.0,Grand-Tunis,urbaine,B,Sans remise,89.9,89.9,Inférieur à 100 DT,None,0.0
2,800155367,2019-01-01,2019-01-01 14:01:35,Early_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NON,NON,...,2.0,Grand-Tunis,urbaine,B,Sans remise,189.9,189.9,Entre 100 et 200 DT,None,0.0
3,800155369,2019-01-01,2019-01-01 14:07:08,Early_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NON,NON,...,2.0,Grand-Tunis,urbaine,B,Sans remise,89.9,89.9,Inférieur à 100 DT,None,0.0
4,800155368,2019-01-01,2019-01-01 14:06:46,Early_afternoon,Winter,Start_of_Month,Start_of_Week,Pre-Covid,NON,NON,...,2.0,Grand-Tunis,urbaine,B,Sans remise,149.0,149.0,Entre 100 et 200 DT,None,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471576,800165808,2019-12-31,2019-12-31 14:12:20,Early_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NON,NON,...,0.0,Grand-Tunis,urbaine,B,de 30 à 40%,161.4,486.8,Supérieur à 300 DT,None,0.0
471577,62241295,2019-12-31,2019-12-31 11:44:36,Late_morning,Winter,End_of_Month,Start_of_Week,Pre-Covid,NON,NON,...,0.0,Grand-Tunis,urbaine,B,Plus que 50%,-0.0,0.0,Inférieur à 100 DT,None,0.0
471578,62241294,2019-12-31,2019-12-31 11:42:59,Late_morning,Winter,End_of_Month,Start_of_Week,Pre-Covid,NON,NON,...,0.0,Grand-Tunis,urbaine,B,Plus que 50%,-0.0,0.0,Inférieur à 100 DT,None,0.0
471579,680067576,2019-12-31,2019-12-31 18:14:16,Evening,Winter,End_of_Month,Start_of_Week,Pre-Covid,NON,NON,...,0.0,centre-est,urbaine,B,Plus que 50%,-0.0,0.0,Inférieur à 100 DT,1,1.0
471580,680067555,2019-12-31,2019-12-31 16:15:03,Late_afternoon,Winter,End_of_Month,Start_of_Week,Pre-Covid,NON,NON,...,0.0,centre-est,urbaine,B,Plus que 50%,-0.0,0.0,Inférieur à 100 DT,1,1.0

In [96]:
df['gender'] = df['gender'].replace(0,'femme')

In [97]:
df['gender'] = df['gender'].replace(1,'homme')

In [98]:
df.to_excel(r'C:\Users\sofi\Desktop\2019.xlsx', index = False)