In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats as st
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter
from scipy.stats import chi2_contingency
from collections import Counter
from math import sqrt

In [2]:
df = pd.read_csv(r'C:\Users\sofi\Downloads\wetransfer-3ab4ca\2021.csv',sep=';', encoding = 'ISO-8859-1',
                     names=['ID_ORDER', 'DATE-ADD','TIME-ADD','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE'],
                     dtype={'ID_ORDER':int,'DATE-ADD':object,'TIME-ADD':object,'LOCATION':int,'ID_CUSTOMER':object,'LAST_NAME':object,'FIRST_NAME':object,'YX_LIBELLE':object,'BIRTH_YEAR':object,'TELEX':object,'EMAIL':object,'ADRESS':object,'POSTAL_CODE':object,'CITY':object,'ITEM_CODE':object,'CC_LIBELLE':object,'CC_LIBELLE_1':object})

df

C:\Users\sofi\Anacondaa\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,14154176,2021-01-01 00:00:00.000,2021-01-13 09:53:21.000,14,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4MS0521H,BLUE ISLAND,MASQUE,MULTI-COULEURS,5.0000,1,0.00,100.0,NaN
1,14154176,2021-01-01 00:00:00.000,2021-01-13 09:53:21.000,14,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4MS0521H,BLUE ISLAND,MASQUE,MULTI-COULEURS,5.0000,1,0.00,100.0,NaN
2,16300705,2021-01-01 00:00:00.000,2021-01-12 10:27:38.000,16,SB0163132,AKKARI,Imen,PARTENAIRE,1982,50962163,...,NaN,17PA00H111495F20H,ISLAND CLUB,PANTALON,MARINE,139.0000,-1,-69.50,50.0,NaN
3,18129947,2021-01-01 00:00:00.000,2021-01-14 08:47:46.000,18,BC0180394,FATHALLAH,Mahdi,PARTENAIRE,1996,25458963,...,NABEULÂ,4COCACHE7NF21H,BLUE ISLAND,CACHE COL,MULTI-COULEURS,39.9000,1,0.00,100.0,NaN
4,35045780,2021-01-01 00:00:00.000,2021-01-04 16:22:30.000,35,BC0352006,BEN ARBI,Riadh,PARTENAIRE,1900,97374143,...,NaN,4CHR00H10843DC20S,BLUE ISLAND,CHEMISE,BLEU/BLANC,79.9000,-1,0.00,100.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212218,800175502,2021-07-04 00:00:00.000,2021-07-04 16:10:00.000,8,B1001570,BEJI,Yosra,NaN,1985,99642600,...,LAOUINA,26ROJ00F08814S21E,GRANDE TAILLE ( JASMIN ),ROBE,JEAN DELAVE,139.0000,-1,-97.30,30.0,NaN
212219,25039066,2021-07-04 00:00:00.000,2021-07-04 18:16:22.000,25,BC0441100,CLIENT,Etranger,PARTENAIRE,1900,00000000,...,NaN,13TS00H171679C21E,ISLD,TEE-SHIRT,BLANC,29.9000,-1,-20.93,30.0,NaN
212220,800175503,2021-07-04 00:00:00.000,2021-07-04 16:17:59.000,8,B1001570,BEJI,Yosra,NaN,1985,99642600,...,LAOUINA,6SND00913IN21E,SASIO FEMME,SANDALE,NOIR,109.0000,-1,-76.30,30.0,NaN
212221,24194826,2021-07-04 00:00:00.000,2021-07-04 13:06:51.000,24,SB0241194,HKIRI,Neila,PARTENAIRE,1900,27498664,...,BIZERTEÂ,4CHU00H10483Y21S,BLUE ISLAND,CHEMISE,BLANC,69.9000,-1,-48.93,30.0,NaN
212222,24194827,2021-07-04 00:00:00.000,2021-07-04 13:08:13.000,24,SB0241194,HKIRI,Neila,PARTENAIRE,1900,27498664,...,BIZERTEÂ,4PA00H11960C20S,BLUE ISLAND,PANTALON,BEIGE,129.0000,-1,-90.30,30.0,NaN

In [3]:
df.isnull().sum()

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            5
FIRST_NAME       43072
YX_LIBELLE       48017
BIRTH_YEAR           0
TELEX            45068
EMAIL           146053
ADRESS          118527
POSTAL_CODE      79864
CITY             80647
ITEM_CODE            0
CC_LIBELLE          83
CC_LIBELLE_1        83
DESIGNATION       3017
PVTTC                0
QTEFACT              0
PUTTCNET         42004
MLR_REMISE       42027
GTR_LIBELLE      44859
dtype: int64

In [4]:
df['PVTTC'].value_counts()

109.0000        19260
119.0000        19154
79.9000         19008
98.9000         18608
89.9000         17870
                ...
BLANC/DORE          1
MARINE/ROUGE        1
PANTALON            1
ROUX/MARINE         1
VERT FORET          1
Name: PVTTC, Length: 126, dtype: int64

In [5]:
df['PVTTC'] = df['PVTTC'].apply(pd.to_numeric, errors='coerce').fillna(0).astype(float).dropna()

In [6]:
df = df[df.PVTTC != 0]

In [7]:
df

,ID_ORDER,DATE-ADD,TIME-ADD,LOCATION,ID_CUSTOMER,LAST_NAME,FIRST_NAME,YX_LIBELLE,BIRTH_YEAR,TELEX,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,14154176,2021-01-01 00:00:00.000,2021-01-13 09:53:21.000,14,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4MS0521H,BLUE ISLAND,MASQUE,MULTI-COULEURS,5.0,1,0.00,100.0,NaN
1,14154176,2021-01-01 00:00:00.000,2021-01-13 09:53:21.000,14,SC000004,CLIENT de PASSAGE,NaN,PASSAGER,0,NaN,...,TUNIS,4MS0521H,BLUE ISLAND,MASQUE,MULTI-COULEURS,5.0,1,0.00,100.0,NaN
2,16300705,2021-01-01 00:00:00.000,2021-01-12 10:27:38.000,16,SB0163132,AKKARI,Imen,PARTENAIRE,1982,50962163,...,NaN,17PA00H111495F20H,ISLAND CLUB,PANTALON,MARINE,139.0,-1,-69.50,50.0,NaN
3,18129947,2021-01-01 00:00:00.000,2021-01-14 08:47:46.000,18,BC0180394,FATHALLAH,Mahdi,PARTENAIRE,1996,25458963,...,NABEULÂ,4COCACHE7NF21H,BLUE ISLAND,CACHE COL,MULTI-COULEURS,39.9,1,0.00,100.0,NaN
4,35045780,2021-01-01 00:00:00.000,2021-01-04 16:22:30.000,35,BC0352006,BEN ARBI,Riadh,PARTENAIRE,1900,97374143,...,NaN,4CHR00H10843DC20S,BLUE ISLAND,CHEMISE,BLEU/BLANC,79.9,-1,0.00,100.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212218,800175502,2021-07-04 00:00:00.000,2021-07-04 16:10:00.000,8,B1001570,BEJI,Yosra,NaN,1985,99642600,...,LAOUINA,26ROJ00F08814S21E,GRANDE TAILLE ( JASMIN ),ROBE,JEAN DELAVE,139.0,-1,-97.30,30.0,NaN
212219,25039066,2021-07-04 00:00:00.000,2021-07-04 18:16:22.000,25,BC0441100,CLIENT,Etranger,PARTENAIRE,1900,00000000,...,NaN,13TS00H171679C21E,ISLD,TEE-SHIRT,BLANC,29.9,-1,-20.93,30.0,NaN
212220,800175503,2021-07-04 00:00:00.000,2021-07-04 16:17:59.000,8,B1001570,BEJI,Yosra,NaN,1985,99642600,...,LAOUINA,6SND00913IN21E,SASIO FEMME,SANDALE,NOIR,109.0,-1,-76.30,30.0,NaN
212221,24194826,2021-07-04 00:00:00.000,2021-07-04 13:06:51.000,24,SB0241194,HKIRI,Neila,PARTENAIRE,1900,27498664,...,BIZERTEÂ,4CHU00H10483Y21S,BLUE ISLAND,CHEMISE,BLANC,69.9,-1,-48.93,30.0,NaN
212222,24194827,2021-07-04 00:00:00.000,2021-07-04 13:08:13.000,24,SB0241194,HKIRI,Neila,PARTENAIRE,1900,27498664,...,BIZERTEÂ,4PA00H11960C20S,BLUE ISLAND,PANTALON,BEIGE,129.0,-1,-90.30,30.0,NaN

In [8]:
df.replace({'0000-00-00': np.nan},inplace=True)

C:\Users\sofi\Anacondaa\lib\site-packages\pandas\core\frame.py:4263: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

In [9]:
#convert DataFrame column to date-time:'GP_DATEPIECE'
df['DATE-ADD'] = pd.to_datetime(df['DATE-ADD'], format = '%Y-%m-%d')
df['DATE-ADD']= pd.to_datetime(df['DATE-ADD'], errors='ignore')

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [10]:
df['TIME-ADD'] = pd.to_datetime(df['TIME-ADD'])

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [11]:
# Create the dictionary for  ETABLISSEMENT
etab = {45:'Gabes',44:'Djerba',28:'Sasio Geant',31:'Blue Island Carrefour',62:'Central Park',16:'Sousse',8:'Lafayette',130:'Blue Island Palmarium',50:'Sasio Carrefour',24:'Bizerte',40:'Ennasr',56:'Sasio Manzah VI',14:'Blue Island Zephyr',61:'La Soukra',63:'Sasio Menzah V',54:'Nabeul',37:'Sasio Zephyr',134:'Sasio Palmarium',64:'Nabeul',65:'Blue Island Manar',36:'Sasio Manar',25:'Blue Island Djerba',52:'Blue Island Menzah VI',66:'Mehdia',42:'Lac 2',67:'Sfax',68:'Monastir',51:'Blue Island Menzah V',69:'El Kef',35:'Kairouan',15:'Sasio Mseken',27:'Sasio Mseken',60:'Sasio Djerba',18:'Kelibia',41:'Ksar Hellal',74:'Hammamet'}
df['LOCATION'] = df['LOCATION'].map(etab)
#display the first 5 lines
df.isnull().sum()

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME       43038
YX_LIBELLE       47960
BIRTH_YEAR           0
TELEX            45004
EMAIL           145976
ADRESS          118452
POSTAL_CODE      79831
CITY             80614
ITEM_CODE            0
CC_LIBELLE           0
CC_LIBELLE_1         0
DESIGNATION       2934
PVTTC                0
QTEFACT              0
PUTTCNET         41921
MLR_REMISE       41921
GTR_LIBELLE      44749
dtype: int64

In [12]:
df['DATE-ADD'] = pd.to_datetime(df['DATE-ADD'])

df['SEASON'] = (df['DATE-ADD'].dt.month - 1) // 3
df['SEASON'] += (df['DATE-ADD'].dt.month == 3)&(df['DATE-ADD'].dt.day>=20)
df['SEASON'] += (df['DATE-ADD'].dt.month == 6)&(df['DATE-ADD'].dt.day>=21)
df['SEASON'] += (df['DATE-ADD'].dt.month == 9)&(df['DATE-ADD'].dt.day>=23)
df['SEASON'] -= 3*((df['DATE-ADD'].dt.month == 12)&(df['DATE-ADD'].dt.day>=21)).astype(int)

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [13]:
season={0:'Winter',1:'Spring',2:'Summer',3:'Autumn'}

df['SEASON'] = df['SEASON'].map(season)

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [14]:
df['COVID']='Post-Covid'
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','COVID','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [15]:
df['BIRTH_YEAR'] = pd.to_datetime(df['BIRTH_YEAR'],errors='coerce')
df.isnull().sum()

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
SEASON               0
COVID                0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME       43038
YX_LIBELLE       47960
BIRTH_YEAR       54630
TELEX            45004
EMAIL           145976
ADRESS          118452
POSTAL_CODE      79831
CITY             80614
ITEM_CODE            0
CC_LIBELLE           0
CC_LIBELLE_1         0
DESIGNATION       2934
PVTTC                0
QTEFACT              0
PUTTCNET         41921
MLR_REMISE       41921
GTR_LIBELLE      44749
dtype: int64

In [16]:
df.BIRTH_YEAR[df.BIRTH_YEAR.dt.year > 2021] = np.nan
df.BIRTH_YEAR[df.BIRTH_YEAR.dt.year < 1921] = np.nan
df.isnull().sum()

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
SEASON               0
COVID                0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME       43038
YX_LIBELLE       47960
BIRTH_YEAR      140655
TELEX            45004
EMAIL           145976
ADRESS          118452
POSTAL_CODE      79831
CITY             80614
ITEM_CODE            0
CC_LIBELLE           0
CC_LIBELLE_1         0
DESIGNATION       2934
PVTTC                0
QTEFACT              0
PUTTCNET         41921
MLR_REMISE       41921
GTR_LIBELLE      44749
dtype: int64

In [17]:
df['BIRTH_YEAR'] = pd.to_datetime(df['BIRTH_YEAR'],errors='coerce')

In [18]:
df['AGE'] = df['DATE-ADD'].dt.year- df['BIRTH_YEAR'].dt.year

In [19]:
df['AGE'].max()

100.0

In [20]:
df['AGE'].min()

0.0

In [21]:
max_AGE=df['AGE'].max()
min_AGE=df['AGE'].min()

In [22]:
cut_age = ['Moins de 25 ans','entre 25 et 30 ans', 'entre 30 et 35 ans','entre 35 et 40 ans','entre 40 et 50 ans','Plus de 50 ans']
cut_bins =[min_AGE, 25, 30, 35,40,50, max_AGE]
df['AGE_SEGMENT'] = pd.cut(df['AGE'], bins=cut_bins, labels = cut_age)

In [23]:
df['AGE_SEGMENT'].value_counts()

entre 40 et 50 ans    26303
Plus de 50 ans        15525
entre 35 et 40 ans    13278
entre 30 et 35 ans     8730
entre 25 et 30 ans     5007
Moins de 25 ans        2463
Name: AGE_SEGMENT, dtype: int64

In [24]:
df['CONFINEMENT'] = 0
df['CONFINEMENT'] += (df['DATE-ADD'].dt.month == 1)&(df['DATE-ADD'].dt.day>=14)&(df['DATE-ADD'].dt.day<18)
df['CONFINEMENT'] += (df['DATE-ADD'].dt.month == 1)&(df['DATE-ADD'].dt.day>=18)
df['CONFINEMENT'] += (df['DATE-ADD'].dt.month > 1)
df['CONFINEMENT'] += (df['DATE-ADD'].dt.month == 5)&(df['DATE-ADD'].dt.day>=9)&(df['DATE-ADD'].dt.day<17)
df['CONFINEMENT'] += (df['DATE-ADD'].dt.month == 5)&(df['DATE-ADD'].dt.day>=17)
df['CONFINEMENT'] += (df['DATE-ADD'].dt.month > 5)

In [25]:
confinement={0:'NO',1:'YES',2:'NO',3:'NO',4:'YES',5:'NO',6:'NO'}

df['CONFINEMENT'] = df['CONFINEMENT'].map(confinement)
df.isnull().sum()

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
SEASON               0
COVID                0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME       43038
YX_LIBELLE       47960
BIRTH_YEAR      140655
TELEX            45004
EMAIL           145976
ADRESS          118452
POSTAL_CODE      79831
CITY             80614
ITEM_CODE            0
CC_LIBELLE           0
CC_LIBELLE_1         0
DESIGNATION       2934
PVTTC                0
QTEFACT              0
PUTTCNET         41921
MLR_REMISE       41921
GTR_LIBELLE      44749
AGE             140655
AGE_SEGMENT     140659
CONFINEMENT          0
dtype: int64

In [26]:
df['P_MONTH']=0
df['P_MONTH']+=(df['DATE-ADD'].dt.day>10)
df['P_MONTH']+=(df['DATE-ADD'].dt.day>20)
df['P_MONTH']=df['P_MONTH'].astype(int)

In [27]:
month={0:'Start_of_Month',1:'Middle_of_Month',2:'End_of_Month'}
df['P_MONTH'] = df['P_MONTH'].map(month)

In [28]:
from datetime import date
import calendar


df['P_WEEK']=df['DATE-ADD'].dt.strftime('%A')
week={'Monday':'Start_of_Week','Tuesday':'Start_of_Week','Wednesday':'Mid_Week','Thursday':'Mid_Week','Friday':'Mid_Week','Saturday':'Week_End','Sunday':'Week_End'}
df['P_WEEK'] = df['P_WEEK'].map(week)

In [29]:
df['CURFEW'] = 0
df['CURFEW'] += (df['DATE-ADD'].dt.month == 1)&(df['DATE-ADD'].dt.day>=12)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 1)&(df['DATE-ADD'].dt.day<18)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 1)&(df['DATE-ADD'].dt.day>=18)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 2)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 3)&(df['DATE-ADD'].dt.day<8)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 3)&(df['DATE-ADD'].dt.day>=8)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 4)&(df['DATE-ADD'].dt.day<9)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 4)&(df['DATE-ADD'].dt.day>=9)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 5)&(df['DATE-ADD'].dt.day<17)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 5)&(df['DATE-ADD'].dt.day>=17)
df['CURFEW'] += (df['DATE-ADD'].dt.month ==6)
df['CURFEW'] += (df['DATE-ADD'].dt.month == 7)

In [30]:
curfew={0:'de 20h à 5h',1:'de 18h à 6h',2:'de 18h à 6h',3:'de 20h à 5h',4:'de 20h à 5h',5:'de 20h à 5h',6:'de 22h à 5h',7:'de 22h à 5h',8:'de 19h à 5h',9:'de 19h à 5h',10:'de 22h à 5h',11:'de 22h à 5h',12:'de 22h à 5h'}

df['CURFEW'] = df['CURFEW'].map(curfew)
df.isnull().sum()

ID_ORDER             0
DATE-ADD             0
TIME-ADD             0
SEASON               0
COVID                0
LOCATION             0
ID_CUSTOMER          0
LAST_NAME            0
FIRST_NAME       43038
YX_LIBELLE       47960
BIRTH_YEAR      140655
TELEX            45004
EMAIL           145976
ADRESS          118452
POSTAL_CODE      79831
CITY             80614
ITEM_CODE            0
CC_LIBELLE           0
CC_LIBELLE_1         0
DESIGNATION       2934
PVTTC                0
QTEFACT              0
PUTTCNET         41921
MLR_REMISE       41921
GTR_LIBELLE      44749
AGE             140655
AGE_SEGMENT     140659
CONFINEMENT          0
P_MONTH              0
P_WEEK               0
CURFEW               0
dtype: int64

In [31]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','SEASON','P_MONTH','P_WEEK','COVID','CONFINEMENT','CURFEW','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE']]

In [32]:
df['QTEFACT'].value_counts()

1.0        173374
1.0000      31708
-1.0         5646
-1.0000      1006
2.0            63
3.0            30
4.0            29
9.0            18
5.0            17
17.0           17
12.0           12
8.0            10
10.0           10
2.0000          6
6.0             6
3.0000          3
-2.0            2
6.0000          2
7.0000          1
22.0000         1
11.0000         1
0.0000          1
20.0000         1
0.0             1
Name: QTEFACT, dtype: int64

In [39]:
df = df[df.QTEFACT != '0.0000']

In [40]:
df['QTEFACT'].value_counts()

1.0        173374
1.0000      31708
-1.0         5646
-1.0000      1006
2.0            63
3.0            30
4.0            29
9.0            18
5.0            17
17.0           17
12.0           12
8.0            10
10.0           10
2.0000          6
6.0             6
3.0000          3
6.0000          2
-2.0            2
7.0000          1
22.0000         1
20.0000         1
11.0000         1
Name: QTEFACT, dtype: int64

In [41]:
df

,ID_ORDER,DATE-ADD,TIME-ADD,SEASON,P_MONTH,P_WEEK,COVID,CONFINEMENT,CURFEW,LOCATION,...,CITY,ITEM_CODE,CC_LIBELLE,CC_LIBELLE_1,DESIGNATION,PVTTC,QTEFACT,PUTTCNET,MLR_REMISE,GTR_LIBELLE
0,14154176,2021-01-01,2021-01-13 09:53:21,Winter,Start_of_Month,Mid_Week,Post-Covid,NO,de 18h à 6h,Blue Island Zephyr,...,TUNIS,4MS0521H,BLUE ISLAND,MASQUE,MULTI-COULEURS,5.0,1,0.00,100.0,NaN
1,14154176,2021-01-01,2021-01-13 09:53:21,Winter,Start_of_Month,Mid_Week,Post-Covid,NO,de 18h à 6h,Blue Island Zephyr,...,TUNIS,4MS0521H,BLUE ISLAND,MASQUE,MULTI-COULEURS,5.0,1,0.00,100.0,NaN
2,16300705,2021-01-01,2021-01-12 10:27:38,Winter,Start_of_Month,Mid_Week,Post-Covid,NO,de 18h à 6h,Sousse,...,NaN,17PA00H111495F20H,ISLAND CLUB,PANTALON,MARINE,139.0,-1,-69.50,50.0,NaN
3,18129947,2021-01-01,2021-01-14 08:47:46,Winter,Start_of_Month,Mid_Week,Post-Covid,NO,de 18h à 6h,Kelibia,...,NABEULÂ,4COCACHE7NF21H,BLUE ISLAND,CACHE COL,MULTI-COULEURS,39.9,1,0.00,100.0,NaN
4,35045780,2021-01-01,2021-01-04 16:22:30,Winter,Start_of_Month,Mid_Week,Post-Covid,NO,de 18h à 6h,Kairouan,...,NaN,4CHR00H10843DC20S,BLUE ISLAND,CHEMISE,BLEU/BLANC,79.9,-1,0.00,100.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212218,800175502,2021-07-04,2021-07-04 16:10:00,Summer,Start_of_Month,Week_end,Post-Covid,NO,de 18h à 6h,Lafayette,...,LAOUINA,26ROJ00F08814S21E,GRANDE TAILLE ( JASMIN ),ROBE,JEAN DELAVE,139.0,-1,-97.30,30.0,NaN
212219,25039066,2021-07-04,2021-07-04 18:16:22,Summer,Start_of_Month,Week_end,Post-Covid,NO,de 18h à 6h,Blue Island Djerba,...,NaN,13TS00H171679C21E,ISLD,TEE-SHIRT,BLANC,29.9,-1,-20.93,30.0,NaN
212220,800175503,2021-07-04,2021-07-04 16:17:59,Summer,Start_of_Month,Week_end,Post-Covid,NO,de 18h à 6h,Lafayette,...,LAOUINA,6SND00913IN21E,SASIO FEMME,SANDALE,NOIR,109.0,-1,-76.30,30.0,NaN
212221,24194826,2021-07-04,2021-07-04 13:06:51,Summer,Start_of_Month,Week_end,Post-Covid,NO,de 18h à 6h,Bizerte,...,BIZERTEÂ,4CHU00H10483Y21S,BLUE ISLAND,CHEMISE,BLANC,69.9,-1,-48.93,30.0,NaN
212222,24194827,2021-07-04,2021-07-04 13:08:13,Summer,Start_of_Month,Week_end,Post-Covid,NO,de 18h à 6h,Bizerte,...,BIZERTEÂ,4PA00H11960C20S,BLUE ISLAND,PANTALON,BEIGE,129.0,-1,-90.30,30.0,NaN

In [42]:
df['QTEFACT']=df['QTEFACT'].astype(float)

In [43]:
df['TOTAL_QUANTITY'] = df['QTEFACT'].groupby(df['ID_ORDER']).transform('sum')

In [44]:
max_QTE=df['TOTAL_QUANTITY'].max()
min_QTE=df['TOTAL_QUANTITY'].min()

In [45]:
cut_qte = ['1 pièce', "2 pièces", 'Entre 3 et 5 Pièces', 'Entre 6 et 10 Pièces', 'Plus que 10 Pièces']
cut_bins =[0.9,1.5, 2, 5, 10, max_QTE ]
df['TOTAL_QUANTITY_SEGMENTS'] = pd.cut(df['TOTAL_QUANTITY'], bins=cut_bins, labels = cut_qte)

In [46]:
df['TOTAL_QUANTITY_SEGMENTS'].value_counts()

2 pièces                73421
Entre 3 et 5 Pièces     65426
Entre 6 et 10 Pièces    27170
1 pièce                 25284
Plus que 10 Pièces      10146
Name: TOTAL_QUANTITY_SEGMENTS, dtype: int64

In [47]:
df['TOTAL_QUANTITY'].value_counts()

 2.0      73421
 3.0      29965
 4.0      27833
 1.0      25284
 6.0      11517
 0.0       9774
 5.0       7628
 8.0       6501
 7.0       3818
 10.0      3133
 9.0       2201
 12.0      2086
 11.0      1243
 14.0      1222
 16.0       836
 13.0       754
 18.0       576
-1.0        511
 15.0       399
 20.0       380
 17.0       374
 22.0       198
 19.0       190
 24.0       159
-2.0        156
 30.0       150
 21.0       147
 28.0       140
 23.0       126
 115.0      115
 32.0        99
 40.0        83
 27.0        81
 25.0        80
 78.0        78
 26.0        78
 468.0       72
 31.0        62
 61.0        61
 29.0        58
-3.0         53
 53.0        53
 52.0        52
 45.0        45
 41.0        41
 39.0        39
 436.0       36
 33.0        33
-4.0         22
Name: TOTAL_QUANTITY, dtype: int64

In [48]:
df2= pd.read_csv(r'C:\Users\sofi\Downloads\train_code_postal.csv')
df2 = df2.rename(columns={'code postal': 'POST_CODE'})
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 969 entries, 0 to 968
Data columns (total 5 columns):
POST_CODE       969 non-null object
Delegation      969 non-null object
poverty rate    969 non-null float64
zone            969 non-null object
orientation     969 non-null object
dtypes: float64(1), object(4)
memory usage: 38.0+ KB

In [49]:
hour=df['TIME-ADD'].dt.hour

In [50]:
# Create the dictionary for Hour 

H = {0:'Early_morning', 1:'Early_morning', 2:'Early_morning', 3:'Early_morning',4:'Early_morning',5:'Early_morning',6:'Early_morning',7:'Early_morning',8:'Early_morning',9:'Late_morning',10:'Late_morning',11:'Late_morning',12:'Early_afternoon',13:'Early_afternoon',14:'Early_afternoon',15:'Late_afternoon',16:'Late_afternoon',17:'Late_afternoon',18:'Evening',19:'Evening',20:'Evening',21:'Night',22:'Night',23:'Night'}
# Use the dictionary to map the 'Hour'
df['HOUR'] = hour.map(H)

In [51]:
df = df[['ID_ORDER', 'DATE-ADD','TIME-ADD','HOUR','SEASON','P_MONTH','P_WEEK','COVID','CONFINEMENT','CURFEW','LOCATION','ID_CUSTOMER','LAST_NAME','FIRST_NAME','YX_LIBELLE','BIRTH_YEAR','AGE','TELEX','EMAIL','ADRESS','POSTAL_CODE','CITY','ITEM_CODE','CC_LIBELLE','CC_LIBELLE_1','DESIGNATION','PVTTC','QTEFACT','PUTTCNET','MLR_REMISE','GTR_LIBELLE','TOTAL_QUANTITY']]

In [52]:
new_row2070 = {'POST_CODE':'2070', 'Delegation':'LA MARSA', 'poverty rate':2.2, 'zone':'urbaine','orientation':'nord-est'}
df2 = df2.append(new_row2070, ignore_index=True)

In [53]:
df['POSTAL_CODE']=df['POSTAL_CODE'].apply(str)
df2['POST_CODE']=df2['POST_CODE'].apply(str)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 5 columns):
POST_CODE       970 non-null object
Delegation      970 non-null object
poverty rate    970 non-null float64
zone            970 non-null object
orientation     970 non-null object
dtypes: float64(1), object(4)
memory usage: 38.0+ KB

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [54]:
DF10=pd.DataFrame()
DF10['codep']=df2['POST_CODE']
DF10

    codep
0    2072
1    1007
2    2023
3    1046
4    1095
..    ...
965  4273
966  4237
967  4232
968  4235
969  2070

[970 rows x 1 columns]

In [55]:
def tunis(code,train):
 try:
    if str(code)[:2] == '20':
        return 'Grand-Tunis'
    elif str(code)[:2] == '10':
        return 'Grand-Tunis'
    elif str(code)[:2] == '11':
        return 'Grand-Tunis'
    else :
        return str(train[train['POST_CODE']== str(code)]['orientation'].values[0])
 except Exception :
    print (str(code))

In [56]:
DF10['ORIENTATION']=DF10.apply(lambda x: tunis(x.codep,df2), axis=1)

In [57]:
def get_region(code, train):
  try:
    if str(code) in str(train['codep'].unique()):
        return str(train[train['codep']== str(code)]['ORIENTATION'].values[0])
  except Exception :
    print (str(code))

In [58]:
df['region'] = df.apply(lambda x: get_region(x.POSTAL_CODE, DF10), axis=1)

500
800
3
3
3
3
3
3
3
3
3
3
3
3
800
3
3
3
3
3
3
3
3
3
3
3
3
240
240
240
800
800
24

In [59]:
df['region'].value_counts()

Grand-Tunis     71028
nord-est        27172
centre-est      15080
sud-est          7276
nord-ouest       4426
centre-ouest     3686
sud-ouest        1392
Name: region, dtype: int64

In [60]:
def get_area(code, train):
  try:
    if str(code) in str(train['POST_CODE'].unique()):
        return str(train[train['POST_CODE']== str(code)]['zone'].values[0])
  except Exception :
    print (str(code))

In [61]:
df['area'] = df.apply(lambda x: get_area(x.POSTAL_CODE, df2), axis=1)

500
800
3
3
3
3
3
3
3
3
3
3
3
3
800
3
3
3
3
3
3
3
3
3
3
3
3
240
240
240
800
800
24

In [62]:
df['area'].value_counts()

urbaine    129978
rurale         82
Name: area, dtype: int64

In [63]:
df = df.rename(columns={'region': 'REGION'})
df = df.rename(columns={'area': 'AREA'})

In [64]:
cut_class = ['A', 'B', 'C+','C-', 'D', 'E']
cut_bins =[0, 2, 8, 18, 26, 42, 55]
df2['class'] = pd.cut(df2['poverty rate'], bins=cut_bins, labels = cut_class)
df2

    POST_CODE    Delegation  poverty rate     zone orientation class
0        2072       SEJOUMI          11.5  urbaine    nord-est    C+
1        1007       SEJOUMI          11.5  urbaine    nord-est    C+
2        2023   JEBEL JLOUD           9.5  urbaine    nord-est    C+
3        1046   JEBEL JLOUD           9.5  urbaine    nord-est    C+
4        1095  SIDI HASSINE           9.4  urbaine    nord-est    C+
..        ...           ...           ...      ...         ...   ...
965      4273   KEBILI NORD          12.3  urbaine   sud-ouest    C+
966      4237   KEBILI NORD          12.3  urbaine   sud-ouest    C+
967      4232   KEBILI NORD          12.3  urbaine   sud-ouest    C+
968      4235   KEBILI NORD          12.3  urbaine   sud-ouest    C+
969      2070      LA MARSA           2.2  urbaine    nord-est     B

[970 rows x 6 columns]

In [65]:
def get_class22(code, train):
  try:
    if str(code) in str(train['POST_CODE'].unique()):
      return str(train[train['POST_CODE']== str(code)]['class'].values[0])
  except Exception :
    print (str(code))

In [66]:
df['CLASS'] = df.apply(lambda x: get_class22(x.POSTAL_CODE, df2), axis=1)

500
800
3
3
3
3
3
3
3
3
3
3
3
3
800
3
3
3
3
3
3
3
3
3
3
3
3
240
240
240
800
800
24

In [67]:
df['CLASS'].value_counts()

B     93005
C+    19106
A      8871
C-     8237
D       835
E         6
Name: CLASS, dtype: int64

In [68]:
df.isnull().sum()

ID_ORDER               0
DATE-ADD               0
TIME-ADD               0
HOUR                   0
SEASON                 0
P_MONTH                0
P_WEEK                 0
COVID                  0
CONFINEMENT            0
CURFEW                 0
LOCATION               0
ID_CUSTOMER            0
LAST_NAME              0
FIRST_NAME         43036
YX_LIBELLE         47960
BIRTH_YEAR        140653
AGE               140653
TELEX              45002
EMAIL             145974
ADRESS            118450
POSTAL_CODE            0
CITY               80614
ITEM_CODE              0
CC_LIBELLE             0
CC_LIBELLE_1           0
DESIGNATION         2934
PVTTC                  0
QTEFACT                0
PUTTCNET           41920
MLR_REMISE         41920
GTR_LIBELLE        44748
TOTAL_QUANTITY         0
REGION             81903
AREA               81903
CLASS              81903
dtype: int64

In [69]:
df = df.rename(columns={'BIRTH_YEAR': 'BIRTHDAY'})
df = df.rename(columns={'ITEM_CODE': 'PRODUCT_ID'})
df = df.rename(columns={'CC_LIBELLE_1': 'PRODUCT_NAME'})
df = df.rename(columns={'CC_LIBELLE': 'LABEL'})
df = df.rename(columns={'DESIGNATION': 'COLOR'})
df = df.rename(columns={'PVTTC': 'PRODUCT_PRICE'})
df = df.rename(columns={'PUTTCNET': 'PRODUCT_PRICE_AFTER_REDUCTION'})
df = df.rename(columns={'QTEFACT': 'PRODUCT_QUANTITY'})
df = df.rename(columns={'MLR_REMISE': 'REDUCTION_PERCENT'})
df = df.rename(columns={'GTR_LIBELLE': 'REDUCTION_TYPE'})
df = df.rename(columns={'YX_LIBELLE': 'CUSTOMER_DESCRIPTION'})

In [70]:
data= pd.read_csv(r'C:\Users\sofi\Downloads\train_gender.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 5 columns):
name        1989 non-null object
gender 1    1989 non-null int64
gender 2    1989 non-null int64
score 1     1989 non-null float64
score 2     1989 non-null float64
dtypes: float64(2), int64(2), object(1)
memory usage: 77.8+ KB

In [71]:
df['REDUCTION_PERCENT'] = df['REDUCTION_PERCENT'].replace(np.nan,0)

In [72]:
df.isnull().sum()

ID_ORDER                              0
DATE-ADD                              0
TIME-ADD                              0
HOUR                                  0
SEASON                                0
P_MONTH                               0
P_WEEK                                0
COVID                                 0
CONFINEMENT                           0
CURFEW                                0
LOCATION                              0
ID_CUSTOMER                           0
LAST_NAME                             0
FIRST_NAME                        43036
CUSTOMER_DESCRIPTION              47960
BIRTHDAY                         140653
AGE                              140653
TELEX                             45002
EMAIL                            145974
ADRESS                           118450
POSTAL_CODE                           0
CITY                              80614
PRODUCT_ID                            0
LABEL                                 0
PRODUCT_NAME                          0
COLOR                              2934
PRODUCT_PRICE                         0
PRODUCT_QUANTITY                      0
PRODUCT_PRICE_AFTER_REDUCTION     41920
REDUCTION_PERCENT                     0
REDUCTION_TYPE                    44748
TOTAL_QUANTITY                        0
REGION                            81903
AREA                              81903
CLASS                             81903
dtype: int64

In [73]:
max_red=df['REDUCTION_PERCENT'].max()
min_red=df['REDUCTION_PERCENT'].min()

In [74]:
min_red

-240.0

In [75]:
max_red

200.0

In [76]:
cut_qte = ['Sans remise', "Inférieur à 30%", 'de 30 à 40%', 'de 40 à 50%','Plus que 50%' ]
cut_bins =[-0.000000001,0.000000001, 30, 40, 50, max_red ]
df['REDUCTION_PERCENT_SEGMENTS'] = pd.cut(df['REDUCTION_PERCENT'], bins=cut_bins, labels = cut_qte)

In [77]:
df['REDUCTION_PERCENT_SEGMENTS'].value_counts()

Inférieur à 30%    88602
Plus que 50%       60305
Sans remise        41921
de 40 à 50%        11080
de 30 à 40%         9833
Name: REDUCTION_PERCENT_SEGMENTS, dtype: int64

In [78]:
df['TOTAL_BASKET']=df['PRODUCT_PRICE_AFTER_REDUCTION'].astype(float)*df['PRODUCT_QUANTITY']

In [79]:
df['TOTAL_BASKET'][df['PRODUCT_PRICE_AFTER_REDUCTION'].isna()]=df['PRODUCT_PRICE']*df['PRODUCT_QUANTITY']

C:\Users\sofi\Anacondaa\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [81]:
df['TOTAL_TICKET']=df['TOTAL_BASKET'].groupby(df['ID_ORDER']).transform('sum')

In [82]:
max_v=df['TOTAL_TICKET'].max()
min_v=df['TOTAL_TICKET'].min()

In [83]:
cut_ticket = ['Inférieur à 100 DT', 'Entre 100 et 200 DT', 'Entre 200 et 300 DT','Supérieur à 300 DT']
cut_bins =[min_v, 100,200,300,max_v ]
df['TICKET_VALUE'] = pd.cut(df['TOTAL_TICKET'], bins=cut_bins, labels = cut_ticket)

In [84]:
df['TICKET_VALUE'].value_counts()

Inférieur à 100 DT     83194
Entre 100 et 200 DT    66353
Supérieur à 300 DT     34513
Entre 200 et 300 DT    27898
Name: TICKET_VALUE, dtype: int64

In [85]:
df_g= pd.read_csv(r'C:\Users\sofi\Downloads\train_gender.csv')
df_g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 5 columns):
name        1989 non-null object
gender 1    1989 non-null int64
gender 2    1989 non-null int64
score 1     1989 non-null float64
score 2     1989 non-null float64
dtypes: float64(2), int64(2), object(1)
memory usage: 77.8+ KB

In [86]:
def word2vec(word):
    # Count the number of characters in each word.
    count_characters = Counter(word)
    # Gets the set of characters and calculates the "length" of the vector.
    set_characters = set(count_characters)
    length = sqrt(sum(c*c for c in count_characters.values()))
    return count_characters, set_characters, length, word

In [87]:
def cosine_similarity(vector1, vector2, ndigits):
    # Get the common characters between the two character sets
    common_characters = vector1[1].intersection(vector2[1])
    # Sum of the product of each intersection character.
    product_summation = sum(vector1[0][character] * vector2[0][character] for character in common_characters)
    # Gets the length of each vector from the word2vec output.
    length = vector1[2] * vector2[2]
    # Calculates cosine similarity and rounds the value to ndigits decimal places.
    if length == 0:
        # Set value to 0 if word is empty.
        similarity = 0
    else:
        similarity = round(product_summation/length, ndigits)
    return similarity

In [88]:
vector_list = [word2vec(str(i)) for i in df_g['name'].unique()]

In [89]:
def find_similar(vector_list,request_word,threshold):
    # Initiate an empty list to store results.
    results_list = []
    # Two loops to compare each vector with another vector only once.
    vector2= word2vec(str(request_word))
    max_similarity = 0 
    similar_word = None
    for i in range(len(vector_list)):
        vector1 = vector_list[i]
        # Calculate cosine similarity
        similarity_score = cosine_similarity(vector1, vector2, 3)
        # Append to results list if similarity score is between 1 and the threshold.
        # Note that scores of 1 can be ignored here if we want to exclude people with the same name.
        if similarity_score> threshold :
            if 1 >= similarity_score>=  max_similarity:
                max_similarity = similarity_score
                similar_word = vector1
    if max_similarity>0 :
        return similar_word[3], max_similarity
    return None,0

In [90]:

def get_gender(firstname,lastname,train):
    similar_firstname , similarity_score_firstname = find_similar(vector_list,firstname,0.5)
    similar_lastname , similarity_score_lastname = find_similar(vector_list,lastname,0.5)
    if lastname =='CLIENT de PASSAGE' :
        return None
    if similarity_score_firstname > 0 :
        
        gender_firstname=str(train[train['name']== str(similar_firstname)]["gender 1"].values[0])
        if similarity_score_lastname> 0 :
            
            gender_lastname= str(train[train['name']== str(similar_lastname)]["gender 1"].values[0])
            if gender_firstname!=gender_lastname : 
                if similarity_score_firstname>= similarity_score_lastname :
                    return gender_firstname
                else :
                    return gender_lastname
            else:
                return gender_firstname
        elif similarity_score_lastname> 0:
            gender_lastname= str(train[train['name']== str(similar_lastname)]["gender 1"].values[0])
            return gender_lastname

In [91]:
#defining the scores of each name
def get_score(firstname,lastname, train):
  try:
    similar_firstname , similarity_score_firstname = find_similar(vector_list,firstname,0.5)
    similar_lastname , similarity_score_lastname = find_similar(vector_list,lastname,0.5)
    if lastname =='CLIENT de PASSAGE' :
        return 0
    if similarity_score_firstname > 0 :
      if similarity_score_lastname> 0 :
        return max(similarity_score_firstname,similarity_score_lastname)
    elif similarity_score_lastname> 0:
      return similarity_score_lastname
    else :
      return 0.5
  except Exception as e :
    print (e)

In [92]:
df["FIRST_NAME"]=df["FIRST_NAME"].apply(str)
df["LAST_NAME"]=df["LAST_NAME"].apply(str)

In [93]:
df = df.rename(columns={'FIRST_NAME': 'firstname'})
df = df.rename(columns={'LAST_NAME': 'lastname'})

In [94]:
df['gender'] = df.apply(lambda x: get_gender(x.firstname, x.lastname,df_g), axis=1)
df["score"]=df.apply( lambda x: get_score(x.firstname, x.lastname,df_g), axis=1)

In [95]:
df['gender'].value_counts()

0    93459
1    75261
Name: gender, dtype: int64

In [97]:
df.isnull().sum()

ID_ORDER                              0
DATE-ADD                              0
TIME-ADD                              0
HOUR                                  0
SEASON                                0
P_MONTH                               0
P_WEEK                                0
COVID                                 0
CONFINEMENT                           0
CURFEW                                0
LOCATION                              0
ID_CUSTOMER                           0
lastname                              0
firstname                             0
CUSTOMER_DESCRIPTION              47960
BIRTHDAY                         140653
AGE                              140653
TELEX                             45002
EMAIL                            145974
ADRESS                           118450
POSTAL_CODE                           0
CITY                              80614
PRODUCT_ID                            0
LABEL                                 0
PRODUCT_NAME                          0
COLOR                              2934
PRODUCT_PRICE                         0
PRODUCT_QUANTITY                      0
PRODUCT_PRICE_AFTER_REDUCTION     41920
REDUCTION_PERCENT                     0
REDUCTION_TYPE                    44748
TOTAL_QUANTITY                        0
REGION                            81903
AREA                              81903
CLASS                             81903
REDUCTION_PERCENT_SEGMENTS          222
TOTAL_BASKET                          0
TOTAL_TICKET                          0
TICKET_VALUE                          5
gender                            43243
score                                74
dtype: int64

In [98]:
df['gender'] = df['gender'].replace(0,'femme')

In [ ]:
df['gender'] = df['gender'].replace(1,'homme')

In [100]:
df.to_excel(r'C:\Users\sofi\Desktop\2021.xlsx', index = False)